### ISSUE TITLE
Cannot install logstash plugin using this chart

### ISSUE THREAD

**Issue by lukeplausin** [elastic/helm-charts#1014]
**Chart version:**

7.10

**Kubernetes version:**

1.16

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)

**Helm Version:**

3

Hi, I'm trying to get on board with the helm logstash chart.
It seems that there is no way to install plugins using the chart here.

I've tried
- Using an init container (I can't see any way to bind mount the plugins directory)
- Adding lines to the logstash container cmd (there seems to be no facility in the helm chart for doing this)

Is there any way to do this? At the moment this chart is totally unusable since my pipeline needs the CSV codec to run properly which isn't installed by default.

Thanks

**Comment by jmlrt** [comment]
Hi @lukeplausin,
The recommended way to install plugins is described in the FAQ: https://github.com/elastic/helm-charts/tree/master/logstash#how-to-install-plugins
