### ISSUE TITLE
["error","elasticsearch","data"],"pid":6,"message":"[TimeoutError]: Request timed out"}

### ISSUE THREAD

**Issue by amit1411** [elastic/helm-charts#1024]
**Chart version:**

3.4

**Kubernetes version:**

v1.17.9

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)

AKS

**Helm Version:**

3

At kibana startup , following messages started coming up
{"type":"log","@timestamp":"2021-01-18T16:02:55Z","tags":["error","savedobjects-service"],"pid":6,"message":"Unable to retrieve version information from Elasticsearch nodes."}
{"type":"log","@timestamp":"2021-01-18T17:18:58Z","tags":["error","elasticsearch","data"],"pid":6,"message":"[TimeoutError]: Request timed out"}
Although all elasticsearch nodes are reachable from the Kibana pod, still i see the timeouts. I restarted the Kibana deployment and then issues started occuring. ES and Kibana are on same version which is 7.10.0

**Comment by ebuildy** [comment]
Can you print full Kibana values.yaml somewhere?
