### ISSUE TITLE
Please Add Info On Running Elasticsearch/Example helm-charts Back To The Readme

### ISSUE THREAD

**Issue by MorrieAtElastic** [elastic/helm-charts#1029]
As far as I can see, the instructions for running the various Example helm-charts under Elasticsearch aren't included in the current README that one accesses at [https://github.com/elastic/helm-charts/blob/master/README.md](https://github.com/elastic/helm-charts/blob/master/README.md) or at [https://github.com/elastic/helm-charts/blob/master/elasticsearch/README.md](https://github.com/elastic/helm-charts/blob/master/elasticsearch/README.md).

These instructions were included in [https://github.com/elastic/helm-charts/blob/6.5.2-alpha1/elasticsearch/README.md#try-it-out](https://github.com/elastic/helm-charts/blob/6.5.2-alpha1/elasticsearch/README.md#try-it-out), but seem to have been removed at some point. At least to someone unfamiliar with helm charts, It's not intuitive as to how the examples are run, and it would be helpful to have these instructions clearly available.

**Comment by jmlrt** [comment]
Hi @MorrieAtElastic,

The link to examples directory is still in the README in the [Usage Notes](https://github.com/elastic/helm-charts/blob/master/elasticsearch/README.md#usage-notes):

>* This repo includes a number of [examples][] configurations which can be used
as a reference. They are also used in the automated testing of this chart.
[examples](https://github.com/elastic/helm-charts/tree/master/elasticsearch/examples/)

There is also direct links to the examples in most sections of the [FAQ](https://github.com/elastic/helm-charts/blob/master/elasticsearch/README.md#faq).

**Comment by MorrieAtElastic** [comment]
The examples and the purpose of each example are clearly present - and very well documented and very useful. 

What I am not finding in the current repo is instructions on how to generate and execute the examples: as far as I can see, this information is only available at [https://github.com/elastic/helm-charts/blob/6.5.2-alpha1/elasticsearch/README.md#try-it-out](https://github.com/elastic/helm-charts/blob/6.5.2-alpha1/elasticsearch/README.md#try-it-out): 

```
Default
To deploy a cluster with all default values and run the integration tests

cd examples/default
make
Multi
A cluster with dedicated node types

cd examples/multi
make
```

**Comment by jmlrt** [comment]
The instructions are directly documented into each example own README pages, ie: https://github.com/elastic/helm-charts/tree/master/elasticsearch/examples/security, this is easier to scale as we're adding newer examples.

>and then, once the specific example configuration has been built, how to execute it from the "base" chart.

not sure about what you mean here, the examples instruction with the `make` commands are directly deploying the Helm charts with the examples values.

**Comment by MorrieAtElastic** [comment]
Oh - there they are! Now that I know where to look I can find them. I didn't know where to look. 

I would have included a general README with instructions on how to generate each example in the top of the Examples repo; I'll leave this to your choice. As I said previously I had to go hunting around to find the instructions on how to run the example helm charts. 

I'll close this ticket.

**Comment by jmlrt** [comment]
> I would have included a general README with instructions on how to generate each example in the top of the Examples repo;

That's a great idea 👍.
I think that's something we can do. I'll let the issue opened to add the general example README, when I have more time.
