### ISSUE TITLE
no way to specify loadBalancerIP in service

### ISSUE THREAD

**Issue by justinasjaronis** [elastic/helm-charts#1031]
Currently this chart does not provide way to specify static IP address for LoadBalancer type of service. Which is trivial if You need to run it as LoadBalancer.

Service should contain additional value i.e. extraSpec which should allow setting any custom variable to service spec.

extraSpec:
    loadBalancerIP: xx.yy.zz.ww

**Comment by jmlrt** [comment]
Hi @justinasjaronis, could you give a bit more details about your request?
Telling what chart need `LoadBalancerIP` would be a good start.

**Comment by ebuildy** [comment]
what chart are you talking about?

I know Kibana implements it already: https://github.com/elastic/helm-charts/blob/master/kibana/templates/service.yaml#L17 .

I am going to do a such PR for APM-server

**Comment by justinasjaronis** [comment]
Yeah sorry, it was about logstash chart. In my business case it's particularly important as You won't be able to use ingress for TCP input.

**Comment by davidcharbonnier** [comment]
Hello @ebuildy,
Seems your PR has been merged, are you able to submit your changes for Logstash chart? I am looking for this feature on my side. Please let me know if you need help with this :)

**Comment by ebuildy** [comment]
Also I am thinking (sometimes this happen...), should we add a different service to expose only logstash API (for monitoring purposes)?
