### ISSUE TITLE
[logstash] Add podAffinity

### ISSUE THREAD

**Issue by ebuildy** [elastic/helm-charts#1032]
**Describe the feature:**

Be able to declare the STS ``podAffinity`` .

**Describe a specific use case for the feature:**

Logstash is an ETL, as such, it's very important logstash pod run closer as possible than input source or output target.

In our use case: 

"we run a 3 RabbitMQ nodes cluster as logstash input, we want logstash to run on same node than rabbitMQ"

**Comment by jmlrt** [comment]
Hi @ebuildy,
That make a lot of sense.
Do you think you could provide a PR for that?

**Comment by ebuildy** [comment]
hey, yes sure, I am on it right now!

**Comment by ebuildy** [comment]
Hello @jmlrt , here the PR >> https://github.com/elastic/helm-charts/pull/1043

merci !
