### ISSUE TITLE
Add support for PodSecurityPolicy on Elastic Helm Charts

### ISSUE THREAD

**Issue by asreich** [elastic/helm-charts#1034]
**Describe the feature:**

It'd be great if support for [PodSecurityPolicies](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) could be added in the Elastic Helm charts for those of us who need such security requirements enabled.

**Describe a specific use case for the feature:**

My organization uses the old public helm charts for [filebeat](https://github.com/helm/charts/tree/master/stable/filebeat) and [metricbeat](https://github.com/helm/charts/tree/master/stable/metricbeat). I was looking to update these references to use the ones from these repos but they appear to be lacking PodSecurityPolicy support like the old version had ([example](https://github.com/helm/charts/blob/master/stable/filebeat/templates/podsecuritypolicy.yaml)) so I am forced to use the old unmaintained versions. 

I could fork the repo and add this myself but I'd rather not maintain it. I'd even be willing to add this feature myself if I could get input from the maintainers. If there's a way to do handle this PodSecurityPolicy that I have somehow overlooked in these charts please let me know.

**Comment by jmlrt** [comment]
Hi @asreich,
`PodSecurityPolicies` are currently supported by Elasticsearch (https://github.com/elastic/helm-charts/blob/master/elasticsearch/templates/podsecuritypolicy.yaml) and Logstash (https://github.com/elastic/helm-charts/blob/master/logstash/templates/podsecuritypolicy.yaml) but not the other charts.

A PR to add it for other charts in the same way that what is currently done for Elasticsearch and Logstash would be awesome 👍

**Comment by jmlrt** [comment]
still valid

**Comment by asreich** [comment]
Sorry been busy, looking into this now thanks.

**Comment by jmlrt** [comment]
still valid
