### ISSUE TITLE
Optional resource settings for Helm charts

### ISSUE THREAD

**Issue by Vaproc** [elastic/helm-charts#1048]
**Describe the feature:**
As already stated in the Elastic Docu (see [here](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-managing-compute-resources.html)), there is an issue with CPU limits and throttling. However, all Helm charts (at least ES, Kibana, Filebeat and Metricbeat) specify a CPU limit in the values.yaml files. Therefore it is not possible to remove the limit. The resource config (or at least the resource.limit) should be optional.

Tested with limit.cpu: null
`error validating "": error validating data: unknown object type "nil" in spec.containers[0].resources.limits.cpu`

Tested with limit.cpu: 0
`invalid: spec.containers[0].resources.requests: Invalid value: "200m": must be less than or equal to cpu limit`

Tested with limit: null
-> Works, but the limit for memory is then unset too.

**Describe a specific use case for the feature:**
Clusters affected by the CPU limit throttling issue don't have a set limit.

**Comment by jmlrt** [comment]
Hey @Vaproc,
This has been already discussed in #409.
Using `--set resources.limits.cpu=null` is working fine for me:

```console
$ helm install es elastic/elasticsearch --set resources.limits.cpu=null      
NAME: es
LAST DEPLOYED: Wed Mar 17 16:33:53 2021
NAMESPACE: jmlrt-test
STATUS: deployed
REVISION: 1
NOTES:
1. Watch all cluster members come up.
  $ kubectl get pods --namespace=jmlrt-test -l app=elasticsearch-master -w
2. Test cluster health using Helm test.
  $ helm test es

$ kubectl get pod elasticsearch-master-0 -o yaml
...
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
...
```

**Comment by jmlrt** [comment]
Setting values in yaml file also seem to work fine:
```console
$ cat << EOF >> 1048.yaml
resources:
  limits:
    cpu: null
EOF
$ helm install es elastic/elasticsearch -f 1048.yaml                   
NAME: es
LAST DEPLOYED: Wed Mar 17 16:40:09 2021
NAMESPACE: jmlrt-test
STATUS: deployed
REVISION: 1
NOTES:
1. Watch all cluster members come up.
  $ kubectl get pods --namespace=jmlrt-test -l app=elasticsearch-master -w
2. Test cluster health using Helm test.
  $ helm test es
$ kubectl get pod elasticsearch-master-0 -o yaml
...
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
...
```

Can you post your exact values?
