### ISSUE TITLE
Use already existing PVC for data

### ISSUE THREAD

**Issue by Pommes9485** [elastic/helm-charts#105]
Hey,

we already deployed elasticsearch 6.6.0 and would like to use helm for the next update. Is it possible to use the "old" pvc containting our data without having copy it somewhere?

Right know, after reading the docs, I thought of:
- mounting it as an additional volume
- setting the data path in elasticsearch.yml
- setting the size of existing data volume from 30Gi to 0Gi to prevent wasting storage

Is there any easier way?

**Comment by Crazybus** [comment]
> Is it possible to use the "old" pvc containting our data without having copy it somewhere?

Have you tested this out? I think it may not work depending on your Kubernetes environment. One of the "tricks" that statefulsets do is to make sure that a pod gets correctly scheduled onto a node that is able to attach its storage. As an example, if you deploy a statefulset to a multi-zone cluster the statefulset will make sure to deploy the pod into the same zone that the storage was created in. 

> Is there any easier way?

https://github.com/elastic/helm-charts/tree/master/elasticsearch/examples/migration is an example for how to migrate from the helm/charts/elasticsearch version but most of it is relevant for any Kubernetes deployment.

**Comment by titansmc** [comment]
I would also be interested on it, since helm v3 is not supported yet for the official helm chart
