### ISSUE TITLE
Example for deploying to GCP

### ISSUE THREAD

**Issue by cedricve** [elastic/helm-charts#1060]
I cannot find an example to deploy the helm charts to GCP. Current examples are using local storage. There should be a section for explaining the onboarding of pv and storageclass.

**Comment by cedricve** [comment]
Please add this to the documentation somewhere or create a new example dir

    storageClassName: "standard"

**Comment by jmlrt** [comment]
Hi @cedricve,

All our charts are fully tested and used internally on GCP with default values.

`volumeClaimTemplate` is defined without `storageClassName` in default [values](https://github.com/elastic/helm-charts/blob/ffd109085023a37211c259302e2d076d84eeca94/elasticsearch/values.yaml#L99-L103) to make sure it's using the default storage class from your Kubernetes cluster.

`storageClassName` is only defined in examples for deploying chart in specific K8S providers which require a different storage class (for example: Docker for Mac, MiniKube, Kind, ...).

Can you be a bit more specific about the issue you have on GCP?
