### ISSUE TITLE
Modify argument of the *beat* container

### ISSUE THREAD

**Issue by oyoyo14** [elastic/helm-charts#1064]
**Describe the feature:**

Base on Filebeat chart, arguments of the filebeat container are hardcoded into the chart. It could be useful to be able to custom those arguments to modify the filebeat behaviour.

Example:

values.yml
```
daemonset:
  args:
  - "-e"
  - "-E"
  - "http.enabled=true"
  - "-c /other/path/filebeat.yml"
```

**Describe a specific use case for the feature:**

This would be useful when you use a sidecar or an initcontainer to forge the configuration file (with ```consul-template``` for example). The configuration file need to be mounted through a shared volume, and can't be mounted to ```/usr/share/filebeat/filebeat.yml``` (because the mount already exist for the original filebeat.yml). 

Providing custom arguments to the filebeat provide us the way to feed him with a different configuration file.

Draft on my repo:
https://github.com/oyoyo14/helm-charts/tree/filebeat-access-to-cmd-args

**Comment by jmlrt** [comment]
Hi @oyoyo14,
Thanks for submitting this request 👍

**Comment by oyoyo14** [comment]
Hi @jmlrt,

I can make a PR from my repo if you want :)

**Comment by jmlrt** [comment]
> I can make a PR from my repo if you want :)

Thanks for the proposal, I think we'll need to investigate a bit before creating a PR for that.

**Comment by jmlrt** [comment]
still valid

**Comment by oyoyo14** [comment]
yes still interested by that :)

**Comment by jmlrt** [comment]
still valid
