### ISSUE TITLE
Kibana GCE ingress with GKE seems to be broken

### ISSUE THREAD

**Issue by rubans** [elastic/helm-charts#1069]
**Chart version:**
7.10.2
**Kubernetes version:**
1.18+
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
GKE
**Helm Version:**
7.10.2

**`helm get release` output**

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting.*

*If you find some secrets in plain text in `helm get release` output you should use [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) to managed them is a secure way (see [Security Example](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/security/values.yaml#L23-L38)).*

<details>
<summary>Output of helm get release</summary>

```
```

</details>

**Describe the bug:**
ingress endpoints showing up as unhealthy
(Does this not get tested at Elastic?)
  ingress.kubernetes.io/forwarding-rule:  k8s2-fr-amdywtns-default-kibana-kibana-22o6euqp
  ingress.kubernetes.io/target-proxy:     k8s2-tp-amdywtns-default-kibana-kibana-22o6euqp
  ingress.kubernetes.io/url-map:          k8s2-um-amdywtns-default-kibana-kibana-22o6euqp
  meta.helm.sh/release-name:              kibana
  meta.helm.sh/release-namespace:         default
  ingress.kubernetes.io/backends:         {"k8s-be-32613--8f6281d6e56b87d8":"HEALTHY","k8s1-8f6281d6-default-kibana-kibana-5601-5f6d412c":"UNHEALTHY"}
**Steps to reproduce:**

1.helm install nginx-ingress stable/nginx-ingress
2.helm install kibana elastic/kibana --set ingress.enabled=true --set ingress.hosts[0]=test.com

Seems it seems to use the GCP ingress rather than nginx ingress controller. Is this correct?

**Expected behavior:**

**Provide logs and/or server output (if relevant):**

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting*

```
```

**Any additional context:**

**Comment by jmlrt** [comment]
Hi @rubans,
Thanks for opening this issue.
Unfortunately we currently don't have time to investigate every tickets so please be patient.
