### ISSUE TITLE
[kubernetes v1.19.7] filebeat doesn`t add kubernetes metadata 

### ISSUE THREAD

**Issue by iluwaa** [elastic/helm-charts#1076]
**Chart version:** 7.6.2

**Kubernetes version:** v1.19.7

**Kubernetes provider:** aws

**Helm Version:** Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"

**Describe the bug:**
after kubernetes update to v1.19.7 filebeat doesn`t add kubernetes.metadata, so conditions like
```
- drop_event.when.not.or:
  - equals.kubernetes.namespace: "namespace"
```
is not working

**Comment by jmlrt** [comment]
Hi @iluwaa,
Thanks for opening this issue.
Unfortunately we currently don't have time to investigate every tickets so please be patient.

**Comment by jmlrt** [comment]
still valid
