### ISSUE TITLE
Can we disable the  default setting of JVM heap size in statefulset.yaml?

### ISSUE THREAD

**Issue by zhu733756** [elastic/helm-charts#1083]
[Starting from version 7.11, Elasticsearch automatically sizes JVM heap based on a node’s roles and total memory.](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-jvm-heap-size.html) 
With this higher-order version,  someone don't want to set the  default setting of JVM heap size,  the corresponding templates needs to be configured.
from `elasticsearch/templates/statefulset.yaml`
``` 
318           - name: ES_JAVA_OPTS
319             value: "{{ .Values.esJavaOpts }}"
```
Change the configuration to this below maybe work:
```
{{- if .Values.esJavaOpts  }}
          - name: ES_JAVA_OPTS
            value: "{{ .Values.esJavaOpts }}"
{{- end }}
```
With the higher-order version, we can overwrite  `esJavaOpts` to null in custom configrations.

**Comment by zhu733756** [comment]
By the way, after applying the configurations above.
In order to build a cluster in multi mode( refers to elasticsearch/examples/multi/),  I add custom data yaml like this below:
```
clusterName: "elasticsearch"
nodeGroup: "data"

roles:
  master: "false"
  ingest: "true"
  data: "true"
  ml: "false"
  remote_cluster_client: "false"

esJavaOpts: null

resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "4000m"
    memory: "32Gi"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 30Gi
```
but it seems not work:
```
$ kubectl get pods
NAME                     READY   STATUS             RESTARTS   AGE
busybox-sleep            1/1     Running            1          25h
elasticsearch-data-0     0/1     Running            6          9m11s
elasticsearch-data-1     0/1     CrashLoopBackOff   6          9m6s
elasticsearch-data-2     0/1     CrashLoopBackOff   6          8m37s
elasticsearch-master-0   1/1     Running            0          102s
elasticsearch-master-1   1/1     Running            0          5m3s
elasticsearch-master-2   1/1     Running            0          8m37s
```
```
  Normal   Scheduled  <unknown>               default-scheduler     Successfully assigned default/elasticsearch-data-1 to worker-p001
  Normal   Pulled     9m53s                   kubelet, worker-p001  Container image "docker.elastic.co/elasticsearch/elasticsearch:7.11.1" already present on machine
  Normal   Created    9m53s                   kubelet, worker-p001  Created container configure-sysctl
  Normal   Started    9m53s                   kubelet, worker-p001  Started container configure-sysctl
  Warning  Unhealthy  9m27s                   kubelet, worker-p001  Readiness probe errored: rpc error: code = Unknown desc = container not running (9192f925b5b063bc848a8daeeff57b732b8e4190c0bb53a3e5c4131bcbe021aa)
  Normal   Pulled     8m21s (x4 over 9m52s)   kubelet, worker-p001  Container image "docker.elastic.co/elasticsearch/elasticsearch:7.11.1" already present on machine
  Normal   Created    8m21s (x4 over 9m52s)   kubelet, worker-p001  Created container elasticsearch
  Normal   Started    8m20s (x4 over 9m52s)   kubelet, worker-p001  Started container elasticsearch
  Warning  Unhealthy  8m (x7 over 9m27s)      kubelet, worker-p001  Readiness probe failed: cannot exec in a stopped state: unknown
  Warning  BackOff    4m41s (x13 over 8m35s)  kubelet, worker-p001  Back-off restarting failed container

```

**Comment by zhu733756** [comment]
After adjusting suitable limits, it works for me now:
resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "2000m"
    memory: "4Gi"

**Comment by ebuildy** [comment]
You should request more CPU, elasticsearch use this value to build thread pool, and this is not dynamic (as far I know)

**Comment by zhu733756** [comment]
@ebuildy 
Thanks for your reply, I think you are right.

**Comment by mehta-ankit** [comment]
I agree this is a problem.
Is there a way on the chart to not get default ES_JAVA_OPTS ? If not then with this chart its hard to make use of dynamic heap setting
https://www.elastic.co/guide/en/elasticsearch/reference/7.11/important-settings.html#heap-size-settings

**Comment by zhu733756** [comment]
@mehta-ankit Yeah, this is what i am concerned about. As a supplement, the max memory size of my cluster is 16Gi.  Once exceeded (the memory of the limits resource set to 32Gi),  it brought in  unpredictable problems.

**Comment by jmlrt** [comment]
Hi, thank you for submitting this issue 👍

**Comment by zhu733756** [comment]
@jmlrt Thanks  for your recognition. I will continue to pay attention to this issue and your pr.

**Comment by zhu733756** [comment]
@jmlrt Thanks for your recognition.
