### ISSUE TITLE
PVCs in migration guide looks incorrect

### ISSUE THREAD

**Issue by dkirrane** [elastic/helm-charts#110]
In the [migration example](https://github.com/elastic/helm-charts/tree/master/elasticsearch/examples/migration) I can see a couple of issues:

- Client node defines a PVC
- Data node doesn't define a PVC

Also, even there doesn't seem to be a way to disable PVC creation for a Client node. PVC always gets created.

**Comment by Crazybus** [comment]
> Client node defines a PVC

We had an issue discussing this but it looks like it was closed for some reason. Right now it isn't possible to disable the PVC but is as simple as adding a value to disable it. If no one else picks it up I'll get around to it shortly. 

https://github.com/elastic/helm-charts/issues/58#issuecomment-463651388

> Data node doesn't define a PVC

It does, although right now it uses the default https://github.com/elastic/helm-charts/blob/edf05174431a57beb93f54dcad3e968a1d4053f9/elasticsearch/values.yaml#L72-L76 values that are specified

I'll make this the new "allow creation of pvcs to be disabled" issue

**Comment by Crazybus** [comment]
Opened https://github.com/elastic/helm-charts/pull/114 which makes it possible to disable the persistent volume and updated the migration guide.
