### ISSUE TITLE
Network Policy - Additonnal Rule

### ISSUE THREAD

**Issue by noe-charmet** [elastic/helm-charts#1106]
Chart version: 7.12

Describe the bug:

In the NetworkPolicy definition, `.Values.networkPolicy.transport.additionalRules` is used in both the `http` and `transport` blocks. The http block should use `.Values.networkPolicy.http.additionalRules` as defined in the `values.yaml` file.

Problematic line:
https://github.com/elastic/helm-charts/blob/90f71e7faa1bd838ce8aff9455e9acae07809625/elasticsearch/templates/networkpolicy.yaml#L31

**Comment by jmlrt** [comment]
Hi @noe-charmet, thanks for reporting it, will be fixed in #1111
