### ISSUE TITLE
[elasticsearch] HPA for the clients node group

### ISSUE THREAD

**Issue by adrobisch** [elastic/helm-charts#1110]
**Describe the feature:**
Allow to specify an HPA for the `client` node group of the `elasticsearch` chart.

**Describe a specific use case for the feature:**

This would allow a simple auto-scaling for the client nodes based on a given metric (usually cpu utilization).
We are aware that it would not be a good idea to have metrics based scaling on the data / master nodes and that the clients also maintain some state, but in our experiments an (externally defined) HPA for clients seems to work fine.

Maybe we are missing some cases or scenarios where this could break?

I already created a prototype: https://github.com/elastic/helm-charts/compare/master...adrobisch:es-client-hpa

PS: we know about the k8s operator, but don't want to switch right now.

I tried to get feedback in https://discuss.elastic.co/t/hpa-for-clients-in-helm-chart/266694 already.

**Comment by jmlrt** [comment]
Hi @adrobisch, thanks for opening this PR, I never investigated into HPA for StatefulSets and don't know if this is something we could/would want to do for Elasticsearch chart.

Leaving this ticket for future exploration.

**Comment by jmlrt** [comment]
still valid

**Comment by adrobisch** [comment]
@jmlrt I can create a real PR from my branch to discuss the details, what do you think?
