### ISSUE TITLE
Dockerize helper scripts for release process

### ISSUE THREAD

**Issue by Crazybus** [elastic/helm-charts#113]
Request came from: https://github.com/elastic/helm-charts/pull/111#discussion_r279439133

- [ ] Dockerize [bumper.py](https://github.com/elastic/helm-charts/blob/master/helpers/bumper.py)
- [x] Dockerize [release.py](https://github.com/elastic/helm-charts/blob/master/helpers/release.py)

**Comment by jmlrt** [comment]
👍

**Comment by jmlrt** [comment]
still valid

**Comment by jmlrt** [comment]
This is still valid
