### ISSUE TITLE
Kibana Chart with "kibana_system" user: readinessProbe never succeeds

### ISSUE THREAD

**Issue by felixfiskare** [elastic/helm-charts#1133]
**Chart version:**
7.12.0
**Kubernetes version:**
1.18.2
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
Kubernetes is set up with Rancher

**Helm Version:**
v3

**`helm get release` output**
The environment is air-gapped but I think the bug  is simple enough to reproduce.

**Describe the bug:**
When I set up kibana to use the `kibana_system` user (as recommended for production) the readinessProbe never succeeds.

This is because kibana settings and the readinessProbe use the same user and password ( `ELASTICSEARCH_USERNAME`and `ELASTICSEARCH_PASSWORD`) to connect to elasticsearch and kibana, but the kibana_system user lacks permission to access kibana.
Therefore the call to `app/kibana` returns a `403` HTTP Status Code, but the readinessProbe expects a `200`, as the code snippet shows:

https://github.com/elastic/helm-charts/blob/b3a4b753a564811713f1a5ff04669baa3a4adfd7/kibana/templates/deployment.yaml#L124-L127

Once I manually edit the readinessProbe to accept a 403 code everything works fine

**Steps to reproduce:**

1. Set kibana_system user as `ELASTICSEARCH_USERNAME` in kibana helm template
2. Deploy kibana helm template
3. Watch kibana readinessProbe failing with `Error: Got HTTP code 403 but expected a 200`

**Expected behavior:**

The readinessProbe should recognise that kibana is fully up and running and succeed if the kibana_system user is used.

One could either accept `403`, too or just access `/` (which then gets redirected to `/login?next=%2F` ) and evaluate the http status code there (which is 200 for an unauthenticated user as well)

**Comment by jmlrt** [comment]
Hi @felixfiskare,
Thanks for opening this issue.
Unfortunately we currently don't have time to investigate every tickets so please be patient.

**Comment by carno** [comment]
I worked around this issue by dropping `ELASTICSEARCH_USERNAME` and `ELASTICSEARCH_PASSWORD` from `extraEnvs` - instead I set up
```yaml
kibana.yml: |
  elasticsearch.username: kibana_system
  elasticsearch.password: <password>
```
in `values.yaml`.

I didn't test it enough to say there are no other issues with this approach, but at least kibana is now passing the probe test and running

**Comment by josecu08** [comment]
My workaround was to use another endpoint for healthcheck. I'm using /api/status instead of /app/kibana.

**Comment by zraider7** [comment]
I am also having this issue. Tested by swapping ELASTICSEARCH_USERNAME to elastic and it worked fine, so it is definitely a permission issue with this user. @josecu08's workaround works great, so not a blocker but as it stands right now, the kibana_system role doesn't seem to be enough for the 'kibana_system' user to function

**Comment by stijnbrouwers** [comment]
Same issue here and resolved it by setting 
```
healthCheckPath: /api/status
```
as proposed by @josecu08

**Comment by ebuildy** [comment]
Related to #1239
