### ISSUE TITLE
ingress networking.k8s.io/v1beta1 is deprecated

### ISSUE THREAD

**Issue by zerkms** [elastic/helm-charts#1136]
**Chart version:** 7.12.0

**Kubernetes version:** 1.19

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine) n/a

**Helm Version:** n/a

**`helm get release` output** n/a

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting.*

*If you find some secrets in plain text in `helm get release` output you should use [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) to managed them is a secure way (see [Security Example](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/security/values.yaml#L23-L38)).*

<details>
<summary>Output of helm get release</summary>

```
```

</details>

**Describe the bug:**
As of kubernetes 1.19 `networking.k8s.io/v1beta1` version of `Ingress` is deprecated and is to be removed in kubernetes 1.22

It should be upgraded to `networking.k8s.io/v1`

Deprecation details: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

**Steps to reproduce:**

1. https://github.com/elastic/helm-charts/blob/b3a4b753a564811713f1a5ff04669baa3a4adfd7/elasticsearch/templates/ingress.yaml#L5-L6
2.
3.

**Expected behavior:**

**Provide logs and/or server output (if relevant):**

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting*

```
```

**Any additional context:**

**Comment by jmlrt** [comment]
Hi @zerkms, thanks for submitting this issue 👍🏻

**Comment by zerkms** [comment]
Right, I may do a PR if nobody from the team decides it fix themselves then :-)

**Comment by maybe-sybr** [comment]
@jmlrt - bumping this to draw your attention to #1233 and the recently submitted #1312 . Could we aim to land one of these PRs soon?

**Comment by ruckc** [comment]
Bumping this again as kibana refuses to deploy on kubernetes 1.22, which was released 10 days ago.

The recommended way to define API versions in helm is something like [this](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/_helpers.tpl#L104-L113) from kube-prometheus-stack.  It detects the current Kubernetes version, and uses the best apiversion for it.

**Comment by pjaak** [comment]
Any update on this? Thanks
