### ISSUE TITLE
[FILEBEAT] deployement - Update strategy

### ISSUE THREAD

**Issue by disaster37** [elastic/helm-charts#1179]
**Describe the feature:**
Add a way to set the update strategy for deployment from values.yaml. Default value is `RollingUpdate`

**Describe a specific use case for the feature:**
We need to set `Recreate` instead RollingUpdate` because of we ingest log file inside container (with NFS share). So the filebeat registry is store on PVC and must be accessed from only one instance.

**Comment by BenB196** [comment]
Running into a similar issue, but using a PVC for persisting Filebeat registry.

**Comment by bhiravabhatla** [comment]
Unfortunately daemonset doesnot support Recreate update strategy. It only supports OnDelete and RollingUpdate. I dont think this is doable as of now.

https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#daemonset-update-strategy

**Comment by disaster37** [comment]
Since 7.12, we have availability to deploy filebeat as deployment instead daemonset. So i speak about deployement (like title say).

**Comment by jmlrt** [comment]
still valid

**Comment by BenB196** [comment]
This is still an issue

**Comment by tudrzal** [comment]
still valid
