### ISSUE TITLE
HELM does not update ELASTICSEARCH_HOSTS values if they change and if you force helm using 'force_update' it will fail with spec.clusterIP: Invalid value: "": field is immutable

### ISSUE THREAD

**Issue by carlcauchi** [elastic/helm-charts#1188]
**Chart version:** helm/kibana/kibana-7.12.0.tgz

**Kubernetes version:** v1.18.9

**Kubernetes provider:** EKS

**Helm Version:** terraform helm provider: hashicorp/helm v2.1.2

**Describe the bug:**

If you do a change to one of the Kibana values, for example, if you change the values for an existing deployment for 'ELASTICSEARCH_HOSTS', it will not replace the values with the new updates but it will create a new entry, in this case another environment variable called the same 'ELASTICSEARCH_HOSTS' and adds the new value to it. The pod will ignore the duplicate entry and will not take the update.

Another way to try and solving this issue is by passing the 'force_update' option to helm, which would try to delete the deployment and redeploying it - which partially works, though it fails on:

```
helm_release.kibana: Modifying... [id=kibana]

Error: failed to replace object: Service "kibana" is invalid: spec.clusterIP: Invalid value: "": field is immutable

  on kibana.tf line 52, in resource "helm_release" "kibana":
  52: resource helm_release "kibana" {
```

It fails to force update the kibana Kubernetes Service, specifically one 'spec.clusterIP'.

From what I can see, the same error exists on the elasticsearch chart which a fix was done on a fork, specifically on the elasticsearch chart as described here: https://github.com/elastic/helm-charts/pull/414/commits/691b082356318dc27d5edd3036092feb151e88c2

**Steps to reproduce:**

Reproducing this error by deploying through helm the latest kibana instance which includes a values file with a specific configuration under extraEnvs, '"ELASTICSEARCH_HOSTS" with a given value. Deploy it, then try changing to a new/different IP address so you're changing the value and redeploy the helm chart. Without the force option, it will not update the value on the existing deployment and if you enable the force_update option it will fail on the error described above.

**Expected behavior:**

Value of "ELASTICSEARCH_HOSTS" (in this case) gets updated/overwritten on the existing Deployment.

**Comment by carlcauchi** [comment]
@krichter722

**Comment by bhiravabhatla** [comment]
@carlcauchi  The deployment environment variables are as below in the template :

https://github.com/elastic/helm-charts/blob/8ddb15bde46c892991cbada64722aa5ce4f5d632/kibana/templates/deployment.yaml#L86-L99


ELASTICSEARCH_HOSTS is set explicitly by .Values.elasticsearchHosts.  If you would like to change ELASTICSEARCH_HOSTS you would need to update  .Values.elasticsearchHosts.

extraEnvs - as the name says could be used to set any extra environment variables other than - ELASTICSEARCH_HOSTS, ELASTICSEARCH_URL, SERVER_HOST
