### ISSUE TITLE
Logstash does not get recreated on a new node on failiure

### ISSUE THREAD

**Issue by Shifter2600** [elastic/helm-charts#1191]
**Chart version:**
8.0.0-SNAPSHOT
**Kubernetes version:**
1.20.4
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
Baremetal
**Helm Version:**
3.5.4

Logstash does not deploy on a new node once the node it is on shutsdown

**Steps to reproduce:**

1.Deploy Logstash on k3s
2.Shutdown node it was deployed to
3.The Logstash workload stays offline untill the node it was originally deployed to starts up again.

**Expected behavior:**
Logstash deployes on a new available node.

My logstash purpose is to use http_poller so I only have 1 workload and the intent is that workload moves to an avaialble node once the node it is on fails.

**Comment by ebuildy** [comment]
not sure this is specific to logstash chart, is it working with another StatefulSet?

**Comment by Shifter2600** [comment]
I'm using the defaults helm and values here with the replicas set to 2 and if I turn off a node the down replica never redeploys to a new node that is available.

**Comment by ebuildy** [comment]
Why this is related to logstash Helm chart?

**Comment by Shifter2600** [comment]
Doesn't the helm chart set the controls of what happens in the event of one of the replica's being non responsive? Right now the replica just sits disconnected instead of redeploying to a new node.

**Comment by ebuildy** [comment]
Can you try with another Deployment? I dont see why this can be specific to logstash Helm chart
