### ISSUE TITLE
Please add your charts to https://hub.helm.sh

### ISSUE THREAD

**Issue by monotek** [elastic/helm-charts#12]
Imho it would be cool if the charts would be a bit promoted. Sp please add your charts to https://hub.helm.sh by creating a pr on: https://github.com/helm/hub/blob/master/config/repo-values.yaml

**Comment by jethr0null** [comment]
This is something we're actively working on :) Thanks!

**Comment by monotek** [comment]
Thanks :-)
https://github.com/helm/hub/commit/4ca606c022dc510ad183097b689493919d4702da
