### ISSUE TITLE
[metricbeat] Missing pod security context

### ISSUE THREAD

**Issue by ebuildy** [elastic/helm-charts#1226]
**Chart version:** 7.12.X

The ``deployment`` template is missing pod securityContext, the value variable ``podSecurityContext`` is currently used by the container:

https://github.com/elastic/helm-charts/blob/v7.12.0/metricbeat/templates/deployment.yaml#L129

Like all other chart, we must be able to configure both pod and container securityContext.

**Comment by lepouletsuisse** [comment]
I just face it. IMO this is a bug because PodSecurityContext should be at Pod level, not at container level (as there is already a `deployment.securityContext` key available).
If I receive the approval of the maintainers, I have no problem doing a PR to fix it.

**Comment by jmlrt** [comment]
still valid
