### ISSUE TITLE
Load balancer issue: helm.elastic.co is missing 7.13.0 charts?

### ISSUE THREAD

**Issue by ebuildy** [elastic/helm-charts#1235]
**Chart version:** 7.13.0

**Helm Version:** v3.6.0

**Describe the bug:**

All 7.13.0 charts are missing from index:  https://helm.elastic.co/index.yaml "sometimes". It looks an issue with HTTP load balancer:

```
curl -sL https://helm.elastic.co/index.yaml -I > /dev/null | grep "content-length"     ## OK !                                                                
x-goog-stored-content-length: 141600
content-length: 141600

curl -sL https://helm.elastic.co/index.yaml -I > /dev/null | grep "content-length"    ## Missing 7.13.0 charts                                                                 
x-goog-stored-content-length: 138044
content-length: 138044
```

**Steps to reproduce:**

Try with curl.

**Expected behavior:**

Helm should get always all elastic charts.

**Comment by xeraa** [comment]
Sorry for the trouble!

I cannot reproduce it right now (or any more) and 2 other colleagues couldn't either. Is it still an issue for you?
Reproducing and disappearing caching or toggling LBs are always a "joy" to debug...

**Comment by ebuildy** [comment]
Yeah!

I can confirm this is working fine now. Took me a few hours to figure out "helm dep build" errors was due to this!

As a workaround, I have edited manualy the index.yaml file and store it on google cloud.
