### ISSUE TITLE
[logstash] Add keystore initContainer like in elasticsearch

### ISSUE THREAD

**Issue by asafhm** [elastic/helm-charts#1243]
**Describe the feature:**
Just like in elasticsearch chart, an init container for the keystore in logstash for initializing the keystore, and populate it with secrets stored as Kubernetes secrets.

**Describe a specific use case for the feature:**
Pipelines often hold secrets such as passwords or tokens, and instead of writing them explicitly within the pipeline (highly frowned upon if these pipelines are also stored in Git) one should reference them in the keystore. When working with the Helm chart, there is currently no solution for the initialization of the keystore.

**Comment by ebuildy** [comment]
I am using ``extraEnvs`` for that but this is better to use logstash keystore as you said (https://www.elastic.co/guide/en/logstash/current/keystore.html) .

Could you make a PR?

**Comment by jmlrt** [comment]
still valid
