### ISSUE TITLE
helm install logstash  failure

### ISSUE THREAD

**Issue by linkingli** [elastic/helm-charts#1244]
**Chart version:**
7.6.2
**Kubernetes version:**
v1.18.13

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)

**Helm Version:**
v3.5.4

**`helm get release` output**

```
```

</details>

**Describe the bug:**

helm install get success, but helm pull and install failure
![image](https://user-images.githubusercontent.com/28832157/120999880-344a5d80-c7bc-11eb-9dd5-15f3abbcc3cd.png)
![image](https://user-images.githubusercontent.com/28832157/120999513-c867f500-c7bb-11eb-8eee-051df0b4693e.png)

**Steps to reproduce:**

1.
2.
3.

**Expected behavior:**
all pass

**Provide logs and/or server output (if relevant):**

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting*

```
```

**Any additional context:**

**Comment by jmlrt** [comment]
Hi @linkingli, we had some issues with Logstash charts and its services previously to 7.9.3.
Can you try a more recent version?

**Comment by jmlrt** [comment]
closing as stale
