### ISSUE TITLE
Unable to use `values.yaml` when trying to install elasticsearch helm chart

### ISSUE THREAD

**Issue by dsikes** [elastic/helm-charts#1256]
**Chart version:**
7.12.1

**Kubernetes version:**
v1.19.6-eks-49a6c0

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
AWS (EKS)

**Helm Version:**
version.BuildInfo{Version:"v3.6.0-rc.1", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}

**`helm get release` output**
n/a (no release available yet, due to bug)

**Describe the bug:**
Unable to use `values.yaml` when trying to install elasticsearch helm chart

**Steps to reproduce:**

1. Run `helm install esprod elastic/elasticsearch --values es/values.yaml`

**Expected behavior:**
I expect the template to install, using the values I am providing.

**Provide logs and/or server output (if relevant):**
```
Error: template: elasticsearch/templates/statefulset.yaml:298:27: executing "elasticsearch/templates/statefulset.yaml" at <.Values.roles.master>: can't evaluate field master in type interface {}
```

**Any additional context:**

I have tried to run this using the `multi` example, and just the `default` example.
Either way, I get the same error message regarding `elasticsearch/templates/statefulset.yaml:298:27` so that would lead me to believe there is an error in the template.

**Comment by knyuwork** [comment]
I think this is duplicated with #1241

**Comment by jmlrt** [comment]
Answered in https://github.com/elastic/helm-charts/issues/1241#issuecomment-866893094
Closing as duplicate
