### ISSUE TITLE
Running elasticsearch on 443 on kubernetes

### ISSUE THREAD

**Issue by AshwiniSwain** [elastic/helm-charts#1259]
I am trying to make the elasticsearch service run on the port 443. The reason for this is that we are currently using ec2 discovery and when trying to use with nginx-ingress, the discovery doesn't work for some reason. To circumvent this issue, we created the elasticsearch service as a Loadbalancer, and a AWS ELB is created for the same and we are able to access the cluster on https://xyz.com:9200, and also the discovery works fine for this.

I was retrying to make it work with ingress, by making the elasticsearch service bind to port 443, but I get this error:

`"stacktrace": ["org.elasticsearch.bootstrap.StartupException: BindHttpException[Failed to bind to 0.0.0.0:443]; nested: BindException[Permission denied];",`

My `elasticsearch.yml` looks like:

    
    discovery.seed_providers: ec2
    discovery.ec2.tag.cluster_name: elasticsearch
    network.host: _ec2:privateIpv4_
    http.port: 443
    discovery.ec2.endpoint: ec2.ap-south-1.amazonaws.com
    cloud.node.auto_attributes: true
    cluster.routing.allocation.awareness.attributes: aws_availability_zone
    logger.org.elasticsearch.discovery.ec2: "TRACE"
    bootstrap.memory_lock: true

Has anyone been able to achieve this? Or has anyone worked on discovery with an ingress?? Any leads will be super helpful.

Thanks

**Comment by ebuildy** [comment]
**Dont use port under 1024, as this require ``root`` priviliges.** 

You can use port ``9200`` with TLS enabled.

**Comment by AshwiniSwain** [comment]
Thanks for the suggestion @ebuildy
