### ISSUE TITLE
Support for Multiple pipelines

### ISSUE THREAD

**Issue by rajudivakaran** [elastic/helm-charts#1282]
**Describe the feature:**

As per https://www.elastic.co/blog/logstash-multiple-pipelines we can use pipelines.yaml to configure multiple pipe lines in one logstash instance. It would be great to know, if this is already supported or can be incorporated in to the helm chart for logstash.

**Describe a specific use case for the feature:**
The use case for me, is to configure multiple inputs and filters. With all the logs been sent to one output (elastic cloud). I am trying to set this up using the helm chart and finding it complex to achieve.

Any help, will be greatly appreciated!

**Comment by johnniee** [comment]
I'm also interested in this feature 👋

**Comment by framsouza** [comment]
I assume you can achieve this by using [logstashPipeline](https://github.com/elastic/helm-charts/blob/master/logstash/values.yaml#L15-L23)

**Comment by sjors101** [comment]
> I assume you can achieve this by using [logstashPipeline](https://github.com/elastic/helm-charts/blob/master/logstash/values.yaml#L15-L23)

This can be used to define different pipelines which will create new files in /usr/share/logstash/pipeline/. However to make sure this becomes effective you still need to update pipelines.yml with the pointers to these new pipeline files, this does happen by default.

**Comment by emmanuelmathot** [comment]
+1

**Comment by vishrantgupta** [comment]
You can configure [multiple pipelines](https://www.elastic.co/guide/en/logstash/current/pipeline-to-pipeline.html#distributor-pattern) as follows:

```
  logstashConfig:
    pipelines.yml: |
      - pipeline.id: beats-server
        path.config: "/usr/share/logstash/pipeline/beat-server.conf"
      - pipeline.id: weblog-processing
        path.config: "/usr/share/logstash/pipeline/weblog-processing.conf"
      - pipeline.id: syslog-processing
        path.config: "/usr/share/logstash/pipeline/syslog-processing.conf"
      - pipeline.id: fallback-processing
        path.config: "/usr/share/logstash/pipeline/fallback-processing.conf"

  # Allows you to add any pipeline files in /usr/share/logstash/pipeline/
  logstashPipeline:
    beat-server.conf: |
      input {
        beats { 
          port => 5044 
        } 
      }
      output {
          if [type] == apache {
            pipeline { send_to => weblogs }
          } else if [type] == system {
            pipeline { send_to => syslog }
          } else {
            pipeline { send_to => fallback }
          }
      }
    weblog-processing.conf: |
      input { pipeline { address => weblogs } }
      filter {
         json {
           source => "message"
         }
      }
      output {
        elasticsearch { hosts => ["http://elasticsearch:9200"] }
      }
    syslog-processing.conf: |
      input { pipeline { address => syslog } }
      filter {
         json {
           source => "message"
         }
      }
      output {
        elasticsearch { hosts => ["http://elasticsearch:9200"] }
      }

    fallback-processing.conf: |
      input { pipeline { address => fallback } }
      output { elasticsearch { hosts => ["http://elasticsearch:9200"] } }

```

**Comment by vishrantgupta** [comment]
This issue seems duplicate of https://github.com/elastic/helm-charts/issues/746

**Comment by johnniee** [comment]
Thanks!
