### ISSUE TITLE
Error: could not find tiller

### ISSUE THREAD

**Issue by a1exus** [elastic/helm-charts#13]
I'm trying to follow [Installing](https://github.com/elastic/helm-charts/tree/master/elasticsearch#installing), yet getting following error:

```
toor@suey:~$ helm repo add elastic https://helm.elastic.co
"elastic" has been added to your repositories
toor@suey:~$ helm repo list
NAME   	URL                                             
stable 	https://kubernetes-charts.storage.googleapis.com
local  	http://127.0.0.1:8879/charts                    
elastic	https://helm.elastic.co                         
toor@suey:~$ helm install --name elasticsearch elastic/elasticsearch --version 6.5.3-alpha1
Error: could not find tiller
toor@suey:~$ 
```

```
toor@suey:~$ tiller -version
v2.12.0
toor@suey:~$ 
```

Please advise.

**Comment by jethr0null** [comment]
Thanks @barkbay! 

Agreed that this looks to be a Helm related issue. Closing this issue for now, but please do continue to open issues if you have any chart related questions or issues once your tiller install is validated and you are able to deploy the charts.

**Comment by a1exus** [comment]
a node to myself (and alikes): start `Tiller` (Helm server) _BEFORE_ (Help client)  :laughing:
