### ISSUE TITLE
Timeout expired waiting for volumes to attach or mount for pod

### ISSUE THREAD

**Issue by JWebDev** [elastic/helm-charts#130]
**Chart version: 7.0.1-alpha1**

**Kubernetes version: v1.13.1**

**Kubernetes provider: Barer metal** 

**Helm Version: v2.11.0**

Run the helm chart.
 
`
helm install elastic/elasticsearch --namespace efk --name efk-elasticsearch --version 7.0.1-alpha1 --set imageTag=7.0.1 --set replicas=1 --set resources.requests.memory=1Gi --set volumeClaimTemplate.storageClassName=nfs --set volumeClaimTemplate.resources.requests.storage=600Gi --set "nodeSelector.kubernetes\.io/hostname"=node3
`  

Persistent Volume is created, and gets the status "bound".

`
elasticsearch-master-elasticsearch-master-0
Bound
pvc-a23fd9a2-7347-11e9-bdfc-0050563dbb49
600Gi
ReadWriteOnce
nfs
`

But the elasticsearch pod does not starts.

`pod has unbound immediate PersistentVolumeClaims
Unable to mount volumes for pod "elasticsearch-master-0_efk(a240e2f2-7347-11e9-bdfc-0050563dbb49)": timeout expired waiting for volumes to attach or mount for pod "efk"/"elasticsearch-master-0". list of unmounted volumes=[elasticsearch-master]. list of unattached volumes=[elasticsearch-master default-token-q8bks]`

Thanks for the help.

**Comment by Crazybus** [comment]
Hi!

This sounds like it might be an issue with your Kubernetes cluster and the persistent storage. Have you been able to deploy other statefulsets or pvcs for other applications?

Could you show me the output of:

```
kubectl get events
kubectl get pv
kubectl get pvc
kubectl get storageclass
```

And could you also include your values.yaml you are using to deploy?

**Comment by JWebDev** [comment]
> Hi!
> 
> This sounds like it might be an issue with your Kubernetes cluster and the persistent storage. Have you been able to deploy other statefulsets or pvcs for other applications?

No, I only have such problems with Elasticsearch. Other applications work and deploy without problems.


> Could you show me the output of:
> 
> ```
> kubectl get events
> kubectl get pv
> kubectl get pvc
> kubectl get storageclass
> ```

```
root@master:~
> kubectl get events --all-namespaces
NAMESPACE     LAST SEEN   TYPE      REASON        KIND   MESSAGE
efk           4m3s        Warning   Unhealthy     Pod    Readiness probe failed:
efk           2m4s        Warning   FailedMount   Pod    Unable to mount volumes for pod "elasticsearch-master-0_efk(a240e2f2-7347-11e9-bdfc-0050563dbb49)": timeout expired waiting for volumes to attach or mount for pod "efk"/"elasticsearch-master-0". list of unmounted volumes=[elasticsearch-master]. list of unattached volumes=[elasticsearch-master default-token-q8bks]
kube-system   28m         Warning   Unhealthy     Pod    Liveness probe failed: Get http://127.0.0.1:9099/liveness: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

root@master:~
> kubectl get pv --all-namespaces
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                             STORAGECLASS    REASON   AGE
data-nfs-server-provisioner-0              700Gi      RWO            Retain           Bound    nfs/data-nfs-server-provisioner-0                 nfs                      83d
jenkins-pv                                 100Gi      RWO            Retain           Bound    tools/jenkins-pvc                                                          83d
jenkins-share-pv                           100Gi      RWO            Retain           Bound    tools/jenkins-share-pvc                                                    83d
mongo-pv                                   50Gi       RWO            Retain           Bound    tools/mongo-pvc                                   mongo-storage            84d
mysql-pv                                   50Gi       RWO            Retain           Bound    tools/mysql-pvc                                   mysql-storage            84d
nexus-pv                                   400Gi      RWO            Retain           Bound    tools/nexus-pvc                                   nexus-storage            84d
pvc-a23fd9a2-7347-11e9-bdfc-0050563dbb49   600Gi      RWO            Delete           Bound    efk/elasticsearch-master-elasticsearch-master-0   nfs                      7d12h

root@master:~
> kubectl get pvc --all-namespaces
NAMESPACE   NAME                                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS    AGE
efk         elasticsearch-master-elasticsearch-master-0   Bound    pvc-a23fd9a2-7347-11e9-bdfc-0050563dbb49   600Gi      RWO            nfs             7d12h
nfs         data-nfs-server-provisioner-0                 Bound    data-nfs-server-provisioner-0              700Gi      RWO                            83d
tools       jenkins-pvc                                   Bound    jenkins-pv                                 100Gi      RWO                            83d
tools       jenkins-share-pvc                             Bound    jenkins-share-pv                           100Gi      RWO                            83d
tools       mongo-pvc                                     Bound    mongo-pv                                   50Gi       RWO            mongo-storage   84d
tools       mysql-pvc                                     Bound    mysql-pv                                   50Gi       RWO            mysql-storage   84d
tools       nexus-pvc                                     Bound    nexus-pv                                   400Gi      RWO            nexus-storage   84d

root@master:~
> kubectl get storageclass --all-namespaces
NAME            PROVISIONER                            AGE
local-storage   kubernetes.io/no-provisioner           84d
mongo-storage   kubernetes.io/no-provisioner           84d
mysql-storage   kubernetes.io/no-provisioner           84d
nexus-storage   kubernetes.io/no-provisioner           84d
nfs (default)   cluster.local/nfs-server-provisioner   83d

root@master:~

```

> And could you also include your values.yaml you are using to deploy?

No, I do not use any values.xml. Only helm command.

**Comment by Crazybus** [comment]
I just tested this by installing the stable helm chart for the nfs provisioner (`helm install stable/nfs-server-provisioner`) and was able to get it working just fine. While we certainly don't recommend using NFS (for performance reasons) it should still be possible to get it working. 

> No, I only have such problems with Elasticsearch. Other applications work and deploy without problems.

The output of your commands show that you don't currently have any other applications provisioned with the NFS storage class. Could you try deploying another application using the NFS provisioner to be certain that it is working correctly? 

Could I also have some more debugging information:

```
kubectl get statefulset elasticsearch-master -o yaml # replace with whatever your statefulset is called
kubectl describe statefulset elasticsearch-master
kubectl describe pod elasticsearch-master-0

# Logs from your NFS provisioner
kubectl logs donating-ocelot-nfs-server-provisioner-0

# To test if your node selector looks ok (nodeSelector.kubernetes\.io/hostname"=node3)
kubectl get nodes -o yaml
```
