### ISSUE TITLE
Kibana Ingress - Invalid cookie header

### ISSUE THREAD

**Issue by kloudblog** [elastic/helm-charts#1310]
**Chart version:**
Latest

**Kubernetes version:** v1.20

**Kubernetes provider:** 
civo kubernetes cluster and linode cluster

Hi Team 
whenever we are creating Ingress with Kibana it is throwing {"statusCode":400,"error":"Bad Request","message":"Invalid cookie header"} error.

This issue can be reproduce with simple Elasticsearch and Kibana installation 

Kibana values.yaml:

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: kibana.kloudblog.com
      paths:
        - path: /

**Comment by ebuildy** [comment]
Why do you think the error is related to ingress? Could you post your Kibana ``values.yaml`` please?

**Comment by kloudblog** [comment]
@ebuildy  Please find the above values file
