### ISSUE TITLE
 All Helm Charts lack the 'Official badge' in ArtifactHub

### ISSUE THREAD

**Issue by saryeHaddadi** [elastic/helm-charts#1323]
**Describe the bug:** In ArtifactHub, all charts lack the 'Official badge'.
The Official Badge indicates that the publisher of the Chart is the Owner of the Software.
An example of an Official Badge can be seen for the [Airflow ](https://artifacthub.io/packages/search?org=apache-airflow&sort=relevance&page=1) Project.

**Steps to reproduce:**
1. Browse ArtifactHub for org=elastic ([direct link](https://artifacthub.io/packages/search?org=elastic&sort=relevance&page=1))

**Expected behavior:**
Having this badge helps in establishing publisher identities, thus bring confidence, especially for new commers to helm.

**Comment by jmlrt** [comment]
Hi @saryeHaddadi, thanks for the tips :+1:

Request in progress: https://github.com/artifacthub/hub/issues/1601

cc @elastic/infra-release
