### ISSUE TITLE
Chart for version 7.14.1 missing

### ISSUE THREAD

**Issue by rgarcia89** [elastic/helm-charts#1335]
Hi from what I see version elastic stack 7.14.1 was released 7 days ago.
However, I cannot see any chart update for that version, nor can I see a tag for it in this github repo.

Will there be an update or can we go with chart version 7.14.0 for elastic search version 7.14.1?

**Comment by chreichert** [comment]
Are there a timeline, when the chart for 7.14.1 will be available?

**Comment by rgarcia89** [comment]
@jmlrt FYI

**Comment by jmlrt** [comment]
Sorry for the late answer.
Yes, we don't plan to release 7.14.1 for Helm charts this time.
You can use 7.14.0 chart with 7.14.1 `imageTag` value.

**Comment by jmlrt** [comment]
closing now that 7.15.0 has been released
