### ISSUE TITLE
Filebeat: failed validation with Helm 2.14 / kubernet 1.14

### ISSUE THREAD

**Issue by dperetti** [elastic/helm-charts#136]
**Chart version:**
7.0.1-alpha1

**Kubernetes version:**
1.14.1

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
DigitalOcean

**Helm Version:**
2.14.0

Helm rejects the install with:
```
Error: validation failed: error validating "": error validating data: 
ValidationError(DaemonSet.spec.template.spec.containers[0].securityContext):
unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext
```

My understanding is that the `podSecurityContext` [should be only set](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) in `spec.securityContext`, not in `spec.containers[].securityContext` like it is here:
https://github.com/elastic/helm-charts/blob/master/filebeat/templates/daemonset.yaml#L108

**Comment by Crazybus** [comment]
Thanks for reporting this! I have removed it in https://github.com/elastic/helm-charts/pull/140. As this container needs to run as root I can't think of any valid reason to make this configurable. 

That extra validation looks really nice! I'm guessing it is a 1.14 feature. Previous versions of Kubernetes will just silently ignore any fields that it doesn't know 👍 .
