### ISSUE TITLE
Allow configuring a NodePort

### ISSUE THREAD

**Issue by dkirrane** [elastic/helm-charts#139]
**Describe the feature:**
Add `values.yaml` option to allow configuring a `NodePort` to use

**Describe a specific use case for the feature:**
This is useful in development. We use Istio Gateway/VirtualService for Ingress and a NodePort would mean not having to apply Istio yaml in development. We can just access Kibana on a NodePort.

**Comment by Crazybus** [comment]
Hi!

It is already possible to change the service type to `NodePort`.

You can override it here:
https://github.com/elastic/helm-charts/blob/2408b21cb5540a28a343095450795c91be40edee/kibana/values.yaml#L75

Alternatively you could also just use a port forward.

```
kubectl port-forward deployment/helm-kibana-default-kibana 5601
```

And then access Kibana from http://localhost:5601

I'm going to close this issue but do please re-open it if this doesn't work for you.

**Comment by al3k** [comment]
@Crazybus I was unable to use NodePort option. At least for app version 7.1.0 and kibana 6.8.0, server.host is set localhost by default. So kibana service will bind to localhost and NodePort option doesn't work.
Only after I have set server.host to 0.0.0.0, it worked.

**Comment by dkirrane** [comment]
To clarify I can set the service type but can't set the actual port I want to use for NodePort

**Comment by Crazybus** [comment]
Could you post the output of `helm get kibana` or whatever your release name is? 

Setting `service.port` should do what you want right?

https://github.com/elastic/helm-charts/blob/856ecf5385dfc4c21a4cdc8649e97e7220f9726e/kibana/templates/service.yaml#L15-L20

**Comment by Crazybus** [comment]
I just tested this out and it seems you can set a static nodePort value in the service spec instead of getting a generated one. PR incoming with a fix.
