### ISSUE TITLE
[elasticsearch] Helm lint fails on chart v7.15.0

### ISSUE THREAD

**Issue by stephenpope** [elastic/helm-charts#1418]
**Chart version:** 7.15.0

**Helm Version:** 3.7.1

**Operating System:** MacOS

**Describe the bug:**

**Steps to reproduce:**

1. Create new chart with elasticsearch as sub-chart

```yaml
dependencies:
  # Official chart from : https://github.com/elastic/helm-charts/tree/master/elasticsearch
  - name: elasticsearch
    version: 7.15.x
    repository: "https://helm.elastic.co"
    condition: elasticsearch.enabled, global.elasticsearch.enabled
```

2. `helm dep up <newchart>`
3. `helm lint --with-subcharts <newchart>` 

```
❯ helm lint --with-subcharts charts/newchart
==> Linting charts/newchart/charts/elasticsearch-7.15.0.tgz
[ERROR] templates/service.yaml: unable to parse YAML: invalid Yaml document separator: kind: Service
[ERROR] templates/test/test-elasticsearch-health.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: v1
```

**Expected behavior:**

Lint will pass.

**Any additional context:**

Changing the chart version to `7.14.0` results in no linting errors.

```
❯ helm lint --with-subcharts charts/newchart
==> Linting charts/newchart/charts/elasticsearch-7.14.0.tgz
```

**Comment by chetanv-oi** [comment]
The chomping till "---" yaml separator is the problem.
Look at https://github.com/elastic/helm-charts/pull/1538
