### ISSUE TITLE
Add namespace to resource metadata

### ISSUE THREAD

**Issue by barrymars** [elastic/helm-charts#1438]
**Describe the feature:**
It would be nice to have the namespace variable in all appropriate resources metadata, so that it is there when rendering out templates  to disk for use by other tools

will submit a pull request for this shortly

**Describe a specific use case for the feature:**

**Comment by krystian-kulgawczuk** [comment]
@Conky5 apologies for pinging :) Would you mind looking at this issue? A lot of people are using helm only for rendering so it would be nice if elastic chart was supporting it.
