### ISSUE TITLE
ECK with elastic helm-charts

### ISSUE THREAD

**Issue by TobiaszG24** [elastic/helm-charts#1441]
### How to deploy ELK using helm charts, but set ECK as cluster manager?

From what I understand, ECK requires to set "Kind" in yaml manifest to "Elasticsearch" (specific custom resource) instead of "StatefulSet".

**Comment by brsolomon-deloitte** [comment]
We share this same frustration - ECK uses Custom Resource Definitions (CRDs) that require you to specify a kind such as `kind: Elasticsearch`. The Helm charts in this repo don't use the CRDs at all but rather use native Kubernetes objects. There is a Helm chart for the operator itself but not for the actual object types from the ECK CRDs. In other words, they are entirely independent and not compatible; you can't monitor an Elastic stack deployed through these Helm charts with the ECK Elastic Operator.

ECK claims to "simplif[y] the task of deploying Elasticsearch and Kibana on Kubernetes", but then leaves the user alone to actually write Kubernetes manifests that specify the desired Elastic stack state.

----

Note: FWIW, StatefulSet is a level above Pod in the Kubernetes abstraction layers, so a StatefulSet is not really comparable to the Elasticsearch CRD at all anyway...

**Comment by framsouza** [comment]
The reason why we have not implemented such a Helm chart is that it would be hard to do in a generic way, what we suggest here is that users should write their own Helm chart to deploy Elastic stack applications where they can expose just he values that are relevant to them.

However, I dedicated some time writing down this helm chart which you can use to deploy Elasticsearch & Kibana. I hope it's help as a starting point. https://github.com/framsouza/eck-resources-with-helm-charts

If you have any question about ECK, please feel free to open up a issue on the https://github.com/elastic/cloud-on-k8s repo.
