### ISSUE TITLE
Kibana v7.15.0 supported on k8s 1.22 ? 

### ISSUE THREAD

**Issue by gorsr01** [elastic/helm-charts#1444]
Can you please confirm whether Kibana chart v 7.15.0 on Kubernetes 1.22 version ? 
We still some few v1beta1 api in .yaml files.

Thanks
Srikanth

**Comment by eddiesimeon** [comment]
@gorsr01 - the main branch has the kibana chart changes required for k8s 1.22.

I have tested the main branch kibana chart with 1.22 and kibana works fine.

the next release v 7.16.0 of the Kibana chart will have the required changes for k8s 1.22.

**Comment by gorsr01** [comment]
@eddiesimeon  Can you please let us know the Release date for 7.16.0 version.
Thanks
Srikanth

**Comment by eddiesimeon** [comment]
@gorsr01 - I don't know the release schedule
The maintainers made the last release in September. I feel there will be a release coming soon.
You can always clone the repo and install the chart from the main branch.
