### ISSUE TITLE
Ingress pr 1409 should be merged into 7.x branch

### ISSUE THREAD

**Issue by leifcr** [elastic/helm-charts#1445]
Feature request to merge PR #1409 into 7.x branch, as it resolves the ingress on newer kubernetes clusters.

**Comment by lapwat** [comment]
#1409 has been closed, this issue can be closes too

**Comment by mcmarkj** [comment]
When is the next release? Currently can't deploy an ingress for Kibana on the most recent helm chart.

**Comment by pramodsharma62** [comment]
@lapwat +1
When is the new release? Same issue can't deploy elastic search.

**Comment by ebuildy** [comment]
I can see it on latest version: 7.16.2

@leifcr you can close the issue!
