### ISSUE TITLE
Please clarify the compatibility of lack thereof with ECK

### ISSUE THREAD

**Issue by brsolomon-deloitte** [elastic/helm-charts#1446]
Quoting from https://github.com/elastic/helm-charts#eck:

> In addition to these Helm charts, Elastic also provides Elastic Cloud on Kubernetes which is based on Operator pattern and is Elastic recommended way to deploy Elasticsearch, Kibana, and APM Server on Kubernetes. There is a dedicated Helm chart for ECK which can be found in ECK repo (documentation).

If ECK is the _recommended way to deploy Elasticsearch, Kibana, and APM Server on Kubernetes_, then why do these Helm charts exist whereas no Helm charts are published that actually use the ECK CRDs? Hence we now have:

- An Operator + CRDs that offers up nothing more than a couple of hello-world YAML examples for actually using the CRDs
- Helm charts that don't use the CRDs and can't be monitored or controlled by the Operator

Others share this confusion: https://github.com/elastic/helm-charts/issues/1441

**Comment by eddiesimeon** [comment]
@brsolomon-deloitte - the eck-operator helms chart is located here:
- https://github.com/elastic/cloud-on-k8s/tree/master/deploy/eck-operator

The quote from https://github.com/elastic/helm-charts#eck has a link that direct references the eck-operator repo (https://github.com/elastic/cloud-on-k8s/tree/master/deploy/eck-operator) and it contains the folder "deploy" which holds the eck-operator helm chart

**Comment by brsolomon-deloitte** [comment]
@eddiesimeon I am aware there is a Helm chart to deploy the ECK Operator itself. What I am asking for clarification on is why there is no Helm chart that actually uses the [ECK CRDs](https://github.com/elastic/cloud-on-k8s/blob/master/deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml).

**Comment by eddiesimeon** [comment]
@brsolomon-deloitte - I get it - I guess we can always make a helm chart that actually uses ECK CRDS and make a PR and then wait for it to be merged into main. How hard can it be. I'll make one and when I'm done I'll make a PR.

**Comment by framsouza** [comment]
The reason why we have not implemented such a Helm chart is that it would be hard to do in a generic way, what we suggest here is that users should write their own Helm chart to deploy Elastic stack applications where they can expose just he values that are relevant **to them.**

However, I dedicated some time writing down this helm chart which you can use to deploy Elasticsearch & Kibana. I hope it's help as a starting point. https://github.com/framsouza/eck-resources-with-helm-charts

If you have any question about ECK, please feel free to open up a issue on the https://github.com/elastic/cloud-on-k8s repo.

**Comment by brsolomon-deloitte** [comment]
Hello @framsouza and thank you times a million for dedicating your time to put together this example. It is useful. (Btw, check out [this helper function](https://github.com/bitnami/charts/blob/81ece48240d42de95b08e33b78c80078126d0139/bitnami/elasticsearch/templates/_helpers.tpl#L481) for some useful helpers on the `sysctl` stuff.)

We have started down a similar path of creating custom charts that use the ECK CRDs, defaulting to a cluster setup with dedicated node types.

Understand your reasoning around there not being a one-size-fits-all solution implementable in a generic way. However, to push back gently on this, there are plenty examples of Helm charts being slightly "opinionated" on dictating a setup that works out of the box but might not be best for all cases. For instance, the [Bitnami Elasticsearch Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch) uses dedicated nodes with specific/arbitrary number of replicas for different node types by default. So, that is something we would welcome being published by Elastic.
