### ISSUE TITLE
ES Helm Chart with Ingress

### ISSUE THREAD

**Issue by WilliamsDL** [elastic/helm-charts#1447]
When I add an ALB Ingress via the Helm chart with the following spec:
spec:
  rules:
    - http:
        paths:
          - path: /es-dan-master/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: es-dan-master
                port:
                  number: 9200

If I navigate to www.mysite.com/es-dan-master/indexName, I expect that the ingress will forward to my service named "es-dan-master", and then perform a get on index "indexName".

However, upon hitting the pod, it is passing the url "/es-dan-master/indexName" instead of "/indexName", so ES is trying to create an index called "es-dan-master"...

How do I correct this?  Can I have the API run on path /es-dan-master inside the pod?

**Comment by framsouza** [comment]
Hey @WilliamsDL I kindly ask you to please format your code when you open an issue.

If you want to check your index using the ingress URL you should run the following: `curl -k https://www.mysite.com/es-dan-master/_cat/indices/indexName`

It doesn't seems to be a bug, it most likely some configuration you should perform to make it works the way you expect, for any kind of question/configuration please go to our [discuss](https://discuss.elastic.co) and raise a question there (feel free to also ping me there)
