### ISSUE TITLE
changed PodDisruptionBudget api to policy/v1 because it's failing in k8s version 1.21.2 

### ISSUE THREAD

**Issue by shubh-cs29** [elastic/helm-charts#1454]
**Chart version**: 7.15.0

**Kubernetes version**: 1.21.2

**Kubernetes provider**: AKS (Azure Kubernetes Service)

**Helm Version**: 3.7.1

**Describe the bug**: If we try the helm upgrade command with  elasticsearch helm chart 7.15.0 then is's failing due to the PodDisruptionBudget api version in AKS kubernetes version 1.21.2.

**Steps to reproduce**:

1. deploy elastcisearch helm chart 7.15.0 into AKS 1.21.2 version
2. try to upgrade the helm chart with some changes

**Expected behavior**: elasticsearch helm chart 7.15.0 should be upgraded with AKS kubernetes version 1.21.2.

**Provide logs and/or server output (if relevant)**: 
![image](https://user-images.githubusercontent.com/28047404/143389714-4e5abbf2-14c8-443a-bb68-4a06a0911a76.png)

**Any additional context**: PR -> https://github.com/elastic/helm-charts/pull/1453

**Comment by zerkms** [comment]
I locally fixed the pdb one with

```
{{ if $.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
```

**Comment by Aaditya-cc** [comment]
I'm getting the same error with elasticsearch helm chart. 

`policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget`

**Comment by jmlrt** [comment]
Hey @shubh-cs29, 7.15.0 version isn't supported with K8S 1.21, you need to use 7.16.1 which is adding this support.
