### ISSUE TITLE
Readiness probe failing in ES chart 7.15.0 for images 7.16.0 & 7.16.1 

### ISSUE THREAD

**Issue by q-leobrack** [elastic/helm-charts#1473]
**Chart version:**
7.15.0
**Kubernetes version:**

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
GKE
**Helm Version:**

</details>

**Describe the bug:**

Readiness probes failing with chart 7.15 and docker images 7.16.0 and 7.16.1

**Steps to reproduce:**

1. Deploy helm chart with latest images
2.
3.

**Expected behavior:**

**Provide logs and/or server output (if relevant):**

```
Warning  Unhealthy               38m (x7 over 39m)  kubelet                  Readiness probe failed: Waiting for elasticsearch cluster to become ready (request params: "wait_for_status=green&timeout=1s" )
Cluster is not yet ready (request params: "wait_for_status=green&timeout=1s" )
  Warning  Unhealthy  4m32s (x202 over 38m)  kubelet  Readiness probe failed: Elasticsearch is already running, lets check the node is healthy
curl --output /dev/null -k -XGET -s -w '%{http_code}' ${BASIC_AUTH} http://127.0.0.1:9200/ failed with HTTP code 200
sh: 30: [[: not found
sh: 35: [[: not found
sh: 37: [[: not found
```
Looks like the `[[` in the readiness probe script is not compatible with whatever `/bin/sh` provides in the docker image

**Comment by WilliamsDL** [comment]
I came here to post the same thing.  I need to upgrade to 7.16.1 and cannot because of this readiness issue...

**Comment by WilliamsDL** [comment]
> 

Actually I see that this fix works:
readinessProbe:
          exec:
            command:
            - bash

**Comment by ebuildy** [comment]
fixed by https://github.com/elastic/helm-charts/pull/1464

**Comment by pellmont** [comment]
Is there a timeline to release a first version of this branch? I think at the moment quite a lot of people are willing to upgrade their elastic instances due to the log4j vulnerability...

**Comment by MoacirCarlos** [comment]
Even after the release of version 7.16.1, here it still gives the same bug reported in this issue.

**Comment by jmlrt** [comment]
FYI, [7.16.1](https://github.com/elastic/helm-charts/releases/tag/v7.16.1) and [6.8.21](https://github.com/elastic/helm-charts/releases/tag/v6.8.21) releases just got released.

These are the versions to use for the log4j fix.
