### ISSUE TITLE
enable xpack to an existing running elasticsearch cluster

### ISSUE THREAD

**Issue by bamb00** [elastic/helm-charts#149]
**Chart version:**
1.0.0 (6.4.3)
**Kubernetes version:**
1.13.0
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
RedHat 7.6, kubespray
**Helm Version:**
2.13
**Values.yaml:**

```
xpack:
   security: 
       enabled: true
   monitoring:
       enabled: true
```

**Describe the bug:**
Steps to enable xpack security to an existing elasticsearch cluster
**Steps to reproduce:**

1. Deploy elasticsearch without xpack security turn on (basic license)
2. Verify the cluster is running correctly
3. Enable xpack security and monitoring to true (gold license)
4. added the certificate to each elasticsearch node (pod) in the config folder
5. Configuring communication between nodes and excrypting HTTP client comm to the elasticsearch.yml

	   xpack.security.transport.ssl.enabled: true
	   xpack.security.transport.ssl.verification_mode: certificate
	   xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
	   xpack.security.transport.ssl.truststore.path: elastic-certificates.p12
	   xpack.security.http.ssl.enabled: true
	   xpack.security.http.ssl.keystore.path: elastic-certificates.p12
	   xpack.security.http.ssl.truststore.path: elastic-certificates.p12

6. Restart each of the elasticsearch nodes
7. Pods failed to start with exceptions

         Caused by: java.lang.reflect.InvocationTargetException
         Caused by: org.elasticsearch.ElasticsearchException: failed to initialize a TrustManagerFactory
         xCaused by: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/config/elastic-certificates.p12

8. No way to add the certificate if the configmap is modified and the pods need to be restart without avoiding the exceptions above.

**Expected behavior:**
I could not find any documentation in Elastic website that can show me or some guidance
**Provide logs and/or server output (if relevant):**
Started at this url and did all the configuration but does not have guidance on the correct way to enable xpack security to an existing running cluster.
     
        https://www.elastic.co/guide/en/elastic-stack-overview/6.4/ssl-tls.html
**Any additional context:**

**Comment by Crazybus** [comment]
> Chart version:
> 1.0.0 (6.4.3)

I think you might using a different helm chart. There was never a version 1.0.0 of this chart. 

>  Values.yaml:

These are also not valid [configuration options](https://github.com/elastic/helm-charts/tree/master/elasticsearch#configuration) for this chart so now I'm 100% sure you must be using a different chart. 

If you want to install a security enabled cluster with *this* chart then you can try to follow https://github.com/elastic/helm-charts/tree/master/elasticsearch#security

**Comment by bamb00** [comment]
@Crazybus It is the same if I deploy elasticsearch from helm stable.  First, es is deployed without security and monitoring enabled.  Second, convert the license from basic to gold then enable security and monitoring.  It seems there is not a way to enable security + monitoring to an existing elasticsearch cluster.  The security and monitoring has to be set in the elasticsearch.yml (configmap) plus the certificate is generate in the container (config dir).  The pods need to be deleted when the elasticsearch.yml is modified then the certificate is lost from the pods.  Is there another way to enabling security + monitoring to an existing elasticsearch cluster.  Thanks.

**Comment by Crazybus** [comment]
> first, es is deployed without security and monitoring enabled. Second, convert the license from basic to gold then enable security and monitoring.

Just in case you missed it, [security is now in basic](https://www.elastic.co/blog/security-for-elasticsearch-is-now-free). So you can deploy a security enabled cluster and it will work properly before installing the gold license. 

>  The pods need to be deleted when the elasticsearch.yml is modified then the certificate is lost from the pods. Is there another way to enabling security + monitoring to an existing elasticsearch cluster

Ahh I think this is your issue here. In the example I linked you above the security is being mounted via a secret. So you want to generate the certificates and upload them as a secret, and not generate them inside the running Elasticsearch container.

**Comment by bamb00** [comment]
@Crazybus, Is the tools (elasticsearch-certutil) to generate ca and certificate available for download?

**Comment by Crazybus** [comment]
It's included with Elasticsearch which you can download from https://www.elastic.co/downloads/elasticsearch. I always run it from within a docker container with my current directory mounted like this:

```
docker run --rm -ti -v $(pwd):/app -w /app --user $(id -u):$(id -g) docker.elastic.co/elasticsearch/elasticsearch:7.1.1 sh
sh-4.2$ elasticsearch-certutil --help
Commands
--------
csr - generate certificate signing requests
cert - generate X.509 certificates and keys
ca - generate a new local certificate authority

Non-option arguments:
command

Option         Description
------         -----------
-h, --help     show help
-s, --silent   show minimal output
-v, --verbose  show verbose output
```

**Comment by bamb00** [comment]
@Crazybus Can you suggest on "How to upload them as a secret?"

**Comment by Crazybus** [comment]
The command to do that is in https://github.com/elastic/helm-charts/tree/master/elasticsearch#security

```
kubectl create secret generic elastic-certificates --from-file=elastic-certificates.p12
```

**Comment by bamb00** [comment]
@Crazybus I've already create the secret...my question is how to push/injects the certificate to elasticsearch?

**Comment by Crazybus** [comment]
> There is the key 'cluster.keystoreSecret' in values.yaml. Is that the key to specify the secret name for elasticsearch TLS?

I already mentioned this in my first comment https://github.com/elastic/helm-charts/issues/149#issuecomment-499503125 however it seems like you are using a different Elasticsearch chart. There is no `cluster.keystoreSecret` key in the values.yaml. 

If you follow the security example I linked to it will ask you to deploy the security example. The part which actually mounts the secrets into the container as files can be found here:

https://github.com/elastic/helm-charts/blob/e6771f4b8b26c163433bd171e490d28dd77de75c/elasticsearch/examples/security/security.yml#L35-L38
