### ISSUE TITLE
[CDN] index.yaml cache is too much

### ISSUE THREAD

**Issue by ebuildy** [elastic/helm-charts#1490]
**Helm Version:**

```version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}```

**Describe the bug:**

``helm dependency build`` is not getting latest Helm chart versions.

**Steps to reproduce:**

```
 curl https://helm.elastic.co/index.yaml -sL | grep "elasticsearch-7.1"
 ==> where is 7.16.1 ?
```

```
 curl https://helm.elastic.co/index.yaml\?toto -sL | grep "elasticsearch-7.1"
    - https://helm.elastic.co/helm/elasticsearch/elasticsearch-7.16.1.tgz
```

(ho , this is working now ! maybe I have just refreshed the cache by doing this ?)

**Comment by jmlrt** [comment]
Hi @ebuildy, thanks for reporting this, we have added a flush CDN cache step in our internal release procedure.
