### ISSUE TITLE
Make "cluster.deprecation_indexing.enabled" optional

### ISSUE THREAD

**Issue by ckotzbauer** [elastic/helm-charts#1492]
**Chart version:** 7.16.1 (with Elasticsearch-Image 7.6.2)

**Kubernetes version:** 1.19.x

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine) Bare-Metal

**Helm Version:** 3.6.3

**`helm get release` output**
not relevant

**Describe the bug:**
The new helm-chart version introduced this new environment variable which is of course not supported by our underlying ES version (ES crashes then). We want to do this chart-update to get the new v1-Ingress in-place to do subsequent infrastructure updates.

**Steps to reproduce:**

1. Install the newest chart version with an older ES image version
2. ES won't start

**Expected behavior:**
The "cluster.deprecation_indexing.enabled" parameter should be made optional.

**Provide logs and/or server output (if relevant):**

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting*

```
```

**Any additional context:**

**Comment by neverov1987** [comment]
This happens to me too on ES 7.9.2 and 7.10.2
```
java.lang.IllegalArgumentException: unknown setting [cluster.deprecation_indexing.enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
```

**Comment by jmlrt** [comment]
Hi @ckotzbauer, as mentioned in the [supported configurations](https://github.com/elastic/helm-charts#supported-configurations), we recommend that the Helm chart version is aligned to the version of the product you want to deploy and so 7.16.1 chart is only supported with 7.16.1 Elasticsearch image.

If you need to use some feature from 7.16.1 chart, we recommend that you update to 7.16.1 Elasticsearch image or add the change on your fork, however, we won't integrate change to support older version.

**Comment by jmlrt** [comment]
Yes, I understand and totally agree that updating Elasticsearch version may not be an option in certain cases, and meanwhile, new K8S versions are bringing changes that may not be compatible with the previous chart version. 

However, we don't have the bandwidth to maintain backward compatibility and support for every use case, so a choice had to be made to support only the current version with chart version == Elasticsearch version.

For the other use case, we recommend forking these charts and integrating the changes in your fork.

**Comment by phoenix-bjoern** [comment]
I don't agree that the Helm chart and application version have to be aligned. There are good examples that BC plays a role and is respected in the existing chart, like [esMajorVersion](https://github.com/elastic/helm-charts/blob/main/elasticsearch/values.yaml#L27). And I would appreciated if toggles/switches specific to an ES version would be introduced wisely in the chart.
