### ISSUE TITLE
[elasticsearch] Configure JVM options file

### ISSUE THREAD

**Issue by ebuildy** [elastic/helm-charts#1495]
**Describe the feature:**

Realted to https://github.com/elastic/helm-charts/issues/1463, https://www.elastic.co/guide/en/elasticsearch/reference/current/advanced-configuration.html#set-jvm-heap-size

We must be able to configure options files under ``/usr/share/elasticsearch/config/jvm.options.d`` folder.

**Describe a specific use case for the feature:**

**Comment by ebuildy** [comment]
PR is on the way

**Comment by jmlrt** [comment]
fixed by #1496
