### ISSUE TITLE
Elasticsearch: Resources created by chart are keyed off of clusterName rather than Release.Name

### ISSUE THREAD

**Issue by davestephens** [elastic/helm-charts#150]
**Chart version:** 7.1.0

**Kubernetes version:** 1.14

**Kubernetes provider:** Azure

**Helm Version:** 2.14

**Describe the bug:**
The resources created by the chart are keyed off of the `clusterName` value, rather than `Release.Name`. 

This doesn't follow normal Helm patterns, meaning that if you run `helm install elastic/elasticsearch` twice (with different release names but not specifying a `clusterName`), the second deployment will fail, as well as break the first one. 

**Steps to reproduce:**

1. `helm install --name dude-elasticsearch elastic/elasticsearch`
2. Wait for cluster to come up.
3. `helm install --name sweet-elasticsearch elastic/elasticsearch`
4. Observe brokenness of dude-elasticsearch, and failure of deployment of `sweet-elasticsearch`.

**Expected behavior:**
It should be possible to run the chart twice without having to specify a `clusterName` and end up with two working Elasticsearch clusters within k8s.

**Comment by Crazybus** [comment]
> The resources created by the chart are keyed off of the clusterName value, rather than Release.Name.
> This doesn't follow normal Helm patterns, meaning that if you run helm install elastic/elasticsearch twice (with different release names but not specifying a clusterName), the second deployment will fail, as well as break the first one.

When I was developing the chart I was originally using the `Release.Name`. I've looked back through the old commit history (before it was first publicly released) and I found the commit message where it was switched which has the reasoning the it was to make it possible to deploy clusters with [multiple node groups](https://github.com/elastic/helm-charts/blob/master/elasticsearch/README.md#multi). Which is where groups of nodes are part of the same Elasticsearch cluster but deployed using separate helm releases. This makes it possible to replace groups of nodes (you can't do resizing of pv for all Kubernetes clusters yet) and to make up whatever architecture you want. 

However, past me didn't go into detail about why this was needed. Looking at the chart now I can't figure out why it couldn't just use `Release.Name` for all the resources instead. So I have the exact same question as you now!

So I wish I had a good answer, but it seems like either past me made a bad decision, or its possible that trying to switch it back to `Release.Name` and setup a multi node cluster might help to explain it. 

Regardless of whether or not past me had a good reason, this is something that isn't something that can be changed until the 8.0.0 release to preserve backwards compatibility. It would be already possible to make it possible to set the `uname` template to `Release.Name` if a certain variable is set.  However we wouldn't be able to make this the default until the next major release. 

> Observe brokenness of dude-elasticsearch, and failure of deployment of sweet-elasticsearch.

Could you explain how it broke? I just tried to reproduce this and my cluster is still green and all pods are still healthy.

**Comment by davestephens** [comment]
Thanks for the explanation!

I'm not at my computer now to try and reproduce it, I *think* from memory my first cluster's pods went into a not-ready state, and the second cluster's pods were nowhere to be seen, because the names clashed. 

My second cluster was specified with a different storage class, not sure if this had anything to do with it or not.

Will do some more testing and report back!

**Comment by desaintmartin** [comment]
In fact, this would prevent deployment of two different ES Helm Releases in the same namespace if the clustername is the same. Could we have a hybrid approach where name is generated from both .Release.Name and cluster name (with maybe some intelligence to prevent duplication)?

**Comment by clook** [comment]
Same here, I'm using ES chart as subchart and I can't deploy multiple distinct releases of my parent chart in the same namespaces since the master service resource itself is conflicting (`elasticsearch-master`).

Workaround for now is to override the `clusterName` but it is not dynamic at all.

`clusterName` should be something like `{{ .Release.Name }}-elasticsearch` rather than `elasticsearch`.
Node grouping should be managed by another mechanism imho (don't know if `.Values.nodeGroup` alone would be sufficient for that or not).

**Comment by desaintmartin** [comment]
Well, it should actually be:
`{{ .Release.Name }}-elasticsearch-{{ .Values.clusterName }}` if clusterName exists, because you need to support both "multiple clusters in a Release" and "Multiple Releases in the namespace" use cases.

I have to admit that I now use helmfile for the purpose of managing ES cluster deployed through Helm, with:
`clusterName: "{{ .Values.releaseName }}"`
in my values.yaml.gotmpl, releaseName being an environment value.

**Comment by desaintmartin** [comment]
Up?

**Comment by desaintmartin** [comment]
So is that a feature or a bug ? Should we consider the current naming as the way to go?

**Comment by jmlrt** [comment]
Hi @desaintmartin,
As mentionned in https://github.com/elastic/helm-charts/issues/150#issuecomment-499513145, despite there is good reasons for changing it, this is not something we will change before next major release (8.0.0), so yes the current naming is the way to go for now.

**Comment by jmlrt** [comment]
still relevant but will be fixed in 8.0.0 later.

**Comment by jmlrt** [comment]
👍🏻

**Comment by jmlrt** [comment]
still valid
