### ISSUE TITLE
[logstash 7.16] Can't set custom ingress port anymore in logstash chart

### ISSUE THREAD

**Issue by nickbabkin** [elastic/helm-charts#1500]
**Chart version:**
7.16.1

**Describe the bug:**

We use different TCP ports for different inputs on logstash. We expose only handful of them via external ingress.

After 7.16 upgrade, possibility to set custom servicePort for ingress has been removed from logstash chart for unknown reason.

Now, it is automatically set equal to httpPort value in configuration, which does not allow us to expose custom port on ingress anymore and instead forces us to use httpPort setting.
https://github.com/elastic/helm-charts/blob/b4d75e5c0902c44350ab9c7c779c0932b84bf66b/logstash/templates/ingress.yaml#L49

The change was introduced with this commit:
https://github.com/elastic/helm-charts/commit/1459b2f28e80d2abf33443568092feb6dac33328
       

In other charts, however, it is still possible to use custom servicePort, for example elasticsearch 7.16 chart:
https://github.com/elastic/helm-charts/blob/b4d75e5c0902c44350ab9c7c779c0932b84bf66b/elasticsearch/templates/ingress.yaml#L60

Is there any reason for restricting it for logstash?

Thank you.

**Comment by mateuszk-gain** [comment]
Any updates with this topic?

**Comment by mateuszk-gain** [comment]
@framsouza ping

**Comment by rlapond** [comment]
bump, please get this fixed.
