### ISSUE TITLE
Cluster unassigned shards

### ISSUE THREAD

**Issue by elransa** [elastic/helm-charts#1536]
Hi,

I am using helm chart for elastic 7.12.0 cluster (2 master , 2 data) deployment on K8s, with a stateful-set  (for persistence i have a volume claim).
getting a lot of unassigned shards, where the shards are corrupted.  

``"unassigned_info": {
        "reason": "ALLOCATION_FAILED"
        "can_allocate": "no_valid_shard_copy"
        "type": "corrupt_index_exception"

 "caused_by": {
                                    "type": "e_o_f_exception",
                                    "reason": "read past EOF: NIOFSIndexInput(path=\"/usr/share/elasticsearch/data/nodes/0/indices/q-23aUrvSI6Sy9UPttY3Yw/0/index/_lpy_1.fnm\") buffer: java.nio.HeapByteBuffer[pos=0 lim=1024 cap=1024] chunkLen: 1024 end: 29477"
                                }``

has anyone come across this type of scenario / any configuration that i should be aware of wen dealing with persistent volumes for th cluster data?

Thanks

**Comment by xeraa** [comment]
That's the output from the shard allocation explain API, right? What's in your Elasticsearch log?

PS: Related to https://stackoverflow.com/questions/70641834/elasticsearch-unassigned-shards-corrupt-index-exception-no-valid-shard-copy.
