### ISSUE TITLE
[logstash] request to be able to test the pipeline configuration before upgrade a release.

### ISSUE THREAD

**Issue by FuyuanChu** [elastic/helm-charts#1551]
**Describe the feature:**

Firstly, logstash is deployed as a statefulset which differs from deployment when upgrading the release.

StatefulSet will terminate one pod and create a new one with the new configuration. And doing the same when the newly created pod is ready. If we have 2 replicas of the statefulset, it will be only one pod before the newly created pod become ready. 

If we are in a bad situation, the invalid pipeline configuration will block the upgrade of statefulset. And it takes time to let us notice the error.

So we think it could be very helpful if we can test the configuration before each upgrade.

**Describe a specific use case for the feature:**

**Comment by jmlrt** [comment]
Hi @FuyuanChu, I think the best way is that you test the upgrade in a dev environment or eventually some local K8s with Minikube or any alternative before applying the upgrade to production.

**Comment by FuyuanChu** [comment]
Thanks for the rely @jmlrt 
The problem we are facing now is developers only use the production environment as they need real user data. I know that is anti-pattern but can't argue with biz requirements.
Hopefully, they adopt the CI/CD pipeline automation, we built a job testing the logstash pipelines.
