### ISSUE TITLE
NotePort option for elasticsearch backend

### ISSUE THREAD

**Issue by ryandawsonuk** [elastic/helm-charts#157]
Like https://github.com/elastic/helm-charts/issues/139 but for the elasticsearch backend. Much like in that issue for kibana, would be convenient for developing against elasticsearch backend when running in minikube

**Comment by Crazybus** [comment]
Once https://github.com/elastic/helm-charts/pull/123 is merged in. I'll add in the same configuration that I just did for Kibana in https://github.com/elastic/helm-charts/pull/160
