### ISSUE TITLE
ReadinessProbe constant failure in IPv6 Cluster Networking

### ISSUE THREAD

**Issue by DandyDeveloper** [elastic/helm-charts#1572]
**Chart version:**
7.16.2

**Kubernetes version:**
1.20.X 

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
Bare Metal

**Helm Version:**
Helm 3 (Latest)

**`helm get release` output**
Not applicable. 

**Describe the bug:**
The readiness probe is current bound to an ipv4 address (127.0.0.1) statically, but this prevents those forced to use IPv6 networking from using this chart as the pods (despite working) never actually mark themselves as ready.

https://github.com/elastic/helm-charts/blob/main/elasticsearch/templates/statefulset.yaml#L277

**Steps to reproduce:**

1. Have an IPv6 only network enabled in Kubernetes
2. Deploy chart with default values (and the `.Values.networkHost` configured with `_eth0_` OR `[::1]`) 
3. View logs. Cluster is configured, but pods will never become ready.

**Expected behavior:**
This is expected because the chart does not fundamentally support this scenario. 

**Provide logs and/or server output (if relevant):**
Not needed. 

**Any additional context:**
The fix for this is to allow a mapping to adjust this IP address (I.E. A solution for us will be to define an ENV with the pod IP and populate the readinessProbe with this.

**Comment by jmlrt** [comment]
Hi @DandyDeveloper the Elastic charts don't support IPv6 for now.

**Comment by DandyDeveloper** [comment]
@jmlrt They do, this is literally the only issue I've encountered in an IPv6 cluster. As in, the cluster I am working with has no IPv4 capabilities.

**Comment by DandyDeveloper** [comment]
Can we reopen this? There's a good fix for this, I'll look into making a PR.
