### ISSUE TITLE
[metricbeat] kube-state-metrics incompatible with k8s v1.22

### ISSUE THREAD

**Issue by mathewmeconry** [elastic/helm-charts#1576]
**Chart version:**
7.16.3

**Kubernetes version:**
1.22

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
K3s on Hetzner Cloud

**Describe the bug:**
The dependency kube-state-metrics isn't compatible with k8s v1.22 because it is using depricated and now removed apis = `rbac.authorization.k8s.io/v1beta1 ClusterRole`

**Steps to reproduce:**

1. Install a k8s cluster with v1.22
2. Try to install this helm chart

**Expected behavior:**
Deploys without any issues

**Any additional context:**
the repository https://charts.helm.sh/stable that you are using for kube-state-metrics is depricated and has been moved for this particular helm chart to https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics
See issue https://github.com/kubernetes/kube-state-metrics/issues/1153 and https://github.com/helm/charts#deprecation-timeline for more information.

**Comment by beatkind** [comment]
There already a PR #1524
