### ISSUE TITLE
Allow extraInitContainers | extraContainers to be passed in as yaml for metricbeat

### ISSUE THREAD

**Issue by hhollenstain-soda** [elastic/helm-charts#1636]
**Describe the feature:**
same issue as noted in https://github.com/elastic/helm-charts/issues/636 but for metricbeat 
The example values does not match actual input. The extraInitContainers and extraContainers are expected as strings vs yaml

**Describe a specific use case for the feature:**
The examples in the values files are not valid and not not conform with other beats charts. I would like to define my additional containers as yaml.   This appears to have been added for kibana and later the filebeat charts but missed metricbeat

**Comment by cgroschupp** [comment]
@framsouza @jmlrt please reopen this issue.
