### ISSUE TITLE
Using Terraform to install Filebeat results in Kubernetes error

### ISSUE THREAD

**Issue by jiyoon-koo** [elastic/helm-charts#1640]
**Chart version:**
7.9.3
**Kubernetes version:**
Client: 1.21.3
Server: 1.20.7

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
AKS

**Helm Version:**
3.4.2

**`helm get release` output**
N/A - installing helm via `helm_release` in tf, not using helm cmd line

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting.*

*If you find some secrets in plain text in `helm get release` output you should use [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) to managed them is a secure way (see [Security Example](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/security/values.yaml#L23-L38)).*

<details>
<summary>Output of helm get release</summary>

```
```

</details>

**Describe the bug:**

I am trying to install filebeat via terraform, so it can read and send logs from my kubernetes cluster on AKS to my elastic cloud deployment.
filebeat.tf
```terraform
resource "helm_release" "filebeat" {
  name       = "filebeat"
  repository = "https://helm.elastic.co/"
  chart      = "filebeat"
  version    = "7.9.3"
  namespace  = "kube-system"

  values = [templatefile("${path.module}/filebeat.yaml", 
  {
    EC_API_KEY = var.EC_API_KEY
  })]

}
```

the `values` field is referencing my `filebeat.yaml`, which looks like this
```yaml
filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        paths:
          - /usr/share/filebeat/logs/filebeat
    output.elasticsearch:
      hosts: '["my-host-url"]'
      api_key: "${EC_API_KEY}"

```
i am getting an error when i run terraform apply
```terraform
helm_release.filebeat: Creating...
│ Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"]
│ 
│   with helm_release.filebeat,
│   on filebeat.tf line 1, in resource "helm_release" "filebeat":
│    1: resource "helm_release" "filebeat" {
│
```
**Steps to reproduce:**

1.
2.
3.

**Expected behavior:**
When I run `terraform apply` with the above yaml-referenced filebeat.tf, I expect to see filebeat installed. 

**Provide logs and/or server output (if relevant):**

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting*

**Any additional context:**
This seems similar to an issue faced by another helm-chart repo [here](https://github.com/grafana/helm-charts/issues/877)

**Comment by jiyoon-koo** [comment]
I updated to the latest version (7.17.1) and this resolved the issue.

**Comment by audunsolemdal** [comment]
Hi @jiyoon-koo , does the config you showed still work for you?

I'm getting stuck at EOF errors. The same happens if I specify the tarball from artifacthub

```
resource "helm_release" "my_release" {
  chart        = "elasticsearch"
  repository   = "https://helm.elastic.co/"
  name         = "elasticsearch"
  version      = "7.17.7"
  namespace    = "my_namespace"
  max_history  = 1
  atomic       = true
  reuse_values = true
  timeout      = 600

  values = [templatefile("${path.module}/templates/values.yaml.tpl", {})]
}
```

`Error: looks like "https://helm.elastic.co/" is not a valid chart repository or cannot be reached: Get "https://helm.elastic.co/index.yaml": EOF`
