### ISSUE TITLE
Support installing a list of logstash plugins

### ISSUE THREAD

**Issue by pedroosorio** [elastic/helm-charts#1642]
It would be very helpful if we could specify a list of logstash plugins to install:

```
plugins:
   - logstash-filter-json_encode
```

Either that, or change the entrypoint to be a docker-entrypoint.d style where we could mount custom scripts to be executed prior to running logstash itself

**Comment by jmlrt** [comment]
Hi @pedroosorio,
We are still recommending the creation of customized Logstash Docker images with the relevant plugin as mentioned in the FAQ: https://github.com/elastic/helm-charts/tree/main/logstash#how-to-install-plugins
