### ISSUE TITLE
Is there a helm chart for Elastic Agent?

### ISSUE THREAD

**Issue by nickbabkin** [elastic/helm-charts#1646]
Hi!

I want to deploy fleet server as part of my Elasticsearch cluster (cluster is deployed in kubernetes with the help of helm charts from this repo).  According to [this](https://www.elastic.co/guide/en/fleet/current/add-a-fleet-server.html) guide, fleet server is just an installation of Elastic agent with a certain configuration parameters enabled.

Question - is there a helm chart for elastic agent? If not, can I use one of the existing charts (such as filebeat) to deploy elastic agent?

Thank you!

**Comment by kaykhancheckpoint** [comment]
@nickbabkin also looking for this, did you ever find out if you could. also do you use eck and if you do what helm charts do you use?

**Comment by borkke** [comment]
Me too. It seems like Helm is not the way you install Agent

**Comment by framsouza** [comment]
Hello, elastic-agent and fleet server are still not available for the current helm charts.
