### ISSUE TITLE
Import Dashboards and Index Patterns along with Install of ELASTIC/KIBANA using HELM

### ISSUE THREAD

**Issue by gnanirahulnutakki** [elastic/helm-charts#1653]
## **FEATURE DESCRIPTION:**
This is a feature request to add a functionality which would let an user given either an input data of ndjson file or a link to the ndjson file which would then import the dashboards and index patterns on install. 

## **FEATURE USE-CASE**

This might be a common use case for most of the EFK using companies out there is that they have a specific set of dashboards and index patterns created and exported for different use cases according their customers.
They could just use of the exported and stored/saved ndjson files during the deployment probably with HELM and get index patterns and dashboards to the customers instead of running a curl command outside of the installation.

This feature will also be more useful in case of packaged infrastructure deployments which deploy a whole set of applications for various use-cases like logging monitoring metrics etc and would immediately be ready to use after deploying.

**Comment by ebuildy** [comment]
Intersting, I thought the same thing for elasticsearch, we should be able to easily specify elasticsearch index templates etc... 

I wrote a small Helm chart here https://github.com/datatok/helm-charts/tree/main/charts/es-proviz , is uses curl to send resources to elasticsearch API, pretty easy.

For kibana,  we could create a job that wait for kibana ready then use the import API https://www.elastic.co/guide/en/kibana/current/saved-objects-api-import.html, could you propose a PR?
