### ISSUE TITLE
[elasticsearch] Add support for extraconfigmap mounts 

### ISSUE THREAD

**Issue by fajulleiro** [elastic/helm-charts#1658]
It would be great to be able to mount a custom configmap on elasticsearch like this way:
https://github.com/prometheus-community/helm-charts/commit/a147caa689862c7b23ecd8296d7b50f2c12870d9

For example, to load a custom synonyms file for synonym_graph token filter
https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-synonym-graph-tokenfilter.html

Thanks.

**Comment by vali-de-man** [comment]
It would indeed be great to have this, as until now I have had to update config files on each node which is really cumbersome and does not feel k8s native

**Comment by MonGMZ** [comment]
I can make a PR with the feature

**Comment by CarlitoxxPro** [comment]
1+ 

@framsouza this could be very helpfull, if you have a chance to take a look and ping someone else of the dev team to take a look to this for get a possible aproval of this PR would be fantastic. 

thanks in advance y kindest regards ;)
