### ISSUE TITLE
Error from deploying elasticsearch + security

### ISSUE THREAD

**Issue by bamb00** [elastic/helm-charts#166]
**Chart version:**
elasticsearch-7.1.1
**Kubernetes version:**
1.13.0
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
kubespray
**Helm Version:**
v2.13.0
**`helm get release` output**

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

```
```

**Describe the bug:**
Run the 'make' from the security directory.

**Steps to reproduce:**

1. cd to the examples/security dir
2. type 'make', hit enter 
3. install failed with "Error: release helm-es-security failed: timed out waiting for the condition" and "make: *** [install] Error 1"

**Expected behavior:**

**Provide logs and/or server output (if relevant):**

		$ make
		kubectl delete secrets elastic-credentials elastic-certificates elastic-certificate-pem || true && \
		vault read -field=value secret/devops-ci/helm-charts/elasticsearch/security/certificates | base64 --decode > elastic-certificates.p12 && \
		vault read -field=value secret/devops-ci/helm-charts/elasticsearch/security/certificate-pem | base64 --decode > elastic-certificate.pem && \
		kubectl create secret generic elastic-credentials  --from-literal=password=changeme --from-literal=username=elastic && \
		kubectl create secret generic elastic-certificates --from-file=elastic-certificates.p12 && \
		kubectl create secret generic elastic-certificate-pem --from-file=elastic-certificate.pem && \
		rm -f elastic-certificates.p12 elastic-certificate.pem
		Error from server (NotFound): secrets "elastic-credentials" not found
		Error from server (NotFound): secrets "elastic-certificates" not found
		Error from server (NotFound): secrets "elastic-certificate-pem" not found
		/bin/sh: line 1: vault: command not found
		/bin/sh: line 2: vault: command not found
		secret/elastic-credentials created
		secret/elastic-certificates created
		secret/elastic-certificate-pem created
		helm upgrade --wait --timeout=600 --install --values ./security.yml helm-es-security ../../ ; \

		Release "helm-es-security" does not exist. Installing it now.
		Error: release helm-es-security failed: timed out waiting for the condition
		make: *** [install] Error 1

**Any additional context:**

**Comment by Crazybus** [comment]
Sorry it looks like these docs got a bit out of sync with the setup. I'm working on a PR now to update the docs. The two issues are:

1. You need to run `make install` as `make` by default tries to get the pre-generated secrets from our own secret service which you don't have access to (this is used for our automated tests)
2. The command to test at the end assume `http` even though the security example got updated to `https`.

**Comment by Crazybus** [comment]
I just opened #170. So if you could test that out and confirm it works that would be perfect!

**Comment by bamb00** [comment]
Will tested on Wednesday...I'll be at the elastic conference in Austin on Tuesday.

**Comment by bamb00** [comment]
@Crazybus The helm upgrade failed due to an existing nodePort already exist.

        $ helm upgrade --wait --timeout=600 --install --values ./security.yml elasticsearch ../../
           Error: UPGRADE FAILED: failed to create resource: Service "security-master" is invalid:        spec.ports[0].nodePort: Invalid value: 30998: provided port is already allocated

**Comment by Crazybus** [comment]
```
spec.ports[0].nodePort: Invalid value: 30998
```

This is not set in the default values or in the example. Could you post the output of `helm get elasticsearch` so that I can see what configuration you are using? If you are using a nodePort and it is already assigned you will need to chose a different one. However the default values will not use a nodePort service.

**Comment by bamb00** [comment]
@Crazybus I forgot to list the steps,

1. Set the service.type to nodeport
2. Run 'helm install . --name elasticsearch'
3. Create the ca and certificate
4. cd examples/security
5. Run 'helm upgrade --wait --timeout=600 --install --values ./security.yml elasticsearch ../../'

**Comment by Crazybus** [comment]
> Set the service.type to nodeport

Did you also set `server.nodePort` to `30998`? The error message you were showing before makes it sound like you might have two applications both trying to use the same node port.

**Comment by dcvtruong** [comment]
@Crazybus Yes.  I have correct the issue.

**Comment by dcvtruong** [comment]
@Crazybus I ran into the same issue when trying to install Kibana + security.

		$ make
		kubectl delete secret kibana-certificates || true
		Error from server (NotFound): secrets "kibana-certificates" not found
		vault read -field=kibana.crt secret/devops-ci/helm-charts/kibana/security/certificates | base64 --decode > kibana.crt
		/bin/sh: vault: command not found
		vault read -field=kibana.key secret/devops-ci/helm-charts/kibana/security/certificates | base64 --decode > kibana.key
		/bin/sh: vault: command not found
		kubectl create secret generic kibana-certificates --from-file=kibana.crt --from-file=kibana.key && \
		rm -f kibana.crt kibana.key
		secret/kibana-certificates created
		helm upgrade --wait --timeout=600 --install --values ./security.yml helm-kibana-security ../../ ; \

		Release "helm-kibana-security" does not exist. Installing it now.
		Error: release helm-kibana-security failed: timed out waiting for the condition
		make: *** [install] Error 1

**Comment by bamb00** [comment]
@Crazybus Yes.  I have correct the mistake.

**Comment by bamb00** [comment]
@crazybus Looks like using azure disk resolved the discovery exception.  Something is not clear to me why is pv affecting the master discovery and why only one master node is the primary and not all three nodes is primary (replicating).  So if I have replicas of 5 only one node is the primary and the other nodes is on standby?

     [root@elasticsearch-master-0 elasticsearch]# dd if=/dev/zero of=/usr/share/elasticsearch/data/test1.img bs=500M count=1 oflag=dsync 
      1+0 records in 
      1+0 records out 
      524288000 bytes (524 MB) copied, 21.2829 s, 24.6 MB/s

     [root@elasticsearch-master-0 elasticsearch]# dd if=/dev/zero of=/usr/share/elasticsearch/data/test2.img bs=512 count=5000 oflag=dsync 
      5000+0 records in 
      5000+0 records out 
      2560000 bytes (2.6 MB) copied, 125.87 s, 20.3 kB/s
