### ISSUE TITLE
Recommended resource setting for a Logstash Pod 

### ISSUE THREAD

**Issue by rjonala** [elastic/helm-charts#1663]
Is there any recommended resource setting for a Logstash Pod handling small amount(100GB) of data everyday and no filtering in place? Logstash just reads data from SQLServer and pushes it to Elasticsearch without any filtering. Thank you.

**Comment by framsouza** [comment]
It doesn't seems to be an issue/bug with the charts itself, please raise your [question](http://discuss.elastic.co) in our discuss (feel free to ping me there)
