### ISSUE TITLE
can't evaluate field enabled in type interface {}

### ISSUE THREAD

**Issue by ceastman-ibm** [elastic/helm-charts#167]
**Chart version:**
7.1.1
**Kubernetes version:**
v1.12.8+IKS
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
IBM Cloud
**Helm Version:**
2.9.1
**`helm get release` output**

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

```
```

**Describe the bug:**
I get the following trying to use the helm chart:

14:59:25  Error: render error in "elasticsearch/templates/statefulset.yaml": template: elasticsearch/templates/statefulset.yaml:20:16: executing "elasticsearch/templates/statefulset.yaml" at <.Values.persistence....>: can't evaluate field enabled in type interface {}

**Steps to reproduce:**

1.
2.
3.

**Expected behavior:**

**Provide logs and/or server output (if relevant):**

14:59:25  + helm template -f ./helm/elasticsearch/values.yaml -f ./deploy-config/global.yaml -f ./deploy-config/secrets/global.yaml -f ./deploy-config/secrets/cloud-influxdb-devtest-dal10.yaml --set cluster=cloud-influxdb-devtest-dal10 --namespace observability ./helm/elasticsearch --output-dir ./plans/elasticsearch_devtest-influxdb/cloud-influxdb-devtest-dal10_observability

**Any additional context:**
[values.yaml.gz](https://github.com/elastic/helm-charts/files/3297824/values.yaml.gz)

**Comment by Crazybus** [comment]
Hey!

The values.yaml that you attached only seems to contain the default values from the helm chart repo itself. My suspicion is that the problem exists in one of the other values files that you are including. Could you try attaching it again or pasting it inside of codeblocks like:

```
insert values.yaml here
```

**Comment by ceastman-ibm** [comment]
@Crazybus so i removed the indent from line 20 and 30 in statefulset.yaml and now that part works

**Comment by Crazybus** [comment]
Thank you for opening the PR and fixing it! Could you still please attach your values.yaml? We actually have a test to make sure this works:

https://github.com/elastic/helm-charts/blob/26fe7570fb668b909d11cddb6c5fa2f8cfaed288/elasticsearch/tests/elasticsearch_test.py#L551-L558

Seeing your values.yaml will allow me to update the test to make sure that this issue doesn't come back again.

**Comment by ceastman-ibm** [comment]
@Crazybus here you go:
[values.yaml.gz](https://github.com/elastic/helm-charts/files/3303010/values.yaml.gz)

**Comment by Crazybus** [comment]
Are you sure you attached all of the files? In your example you show that you are specifying multiple values.yaml. This one only contains the default values with a couple of unrelated modifications. 

```
image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 7.1.1
  PullPolicy: IfNotPresent
```

This isn't the right way to specify the image values. Instead it should look the same as the default values:

```
image: "docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "7.1.1"
imagePullPolicy: "IfNotPresent"
```

This section doesn't do anything:

```
data:
  path: /usr/share/elasticsearch
```

Luckily this is pointing to the default path anyway, so shouldn't be causing you any issues.

**Comment by jmlrt** [comment]
Hi @ceastman-ibm, 
I'm closing this issue as we don't have enough information to reproduce your problem.
Don't hesitate to reopen it if you can provide us all the values files that you are using (it seems that you are using the following files: `./helm/elasticsearch/values.yaml`, `./deploy-config/global.yaml` `./deploy-config/secrets/global.yaml`and `./deploy-config/secrets/cloud-influxdb-devtest-dal10.yaml`).
