### ISSUE TITLE
Missing 7.17.x charts (chart version not aligned with image tag)?

### ISSUE THREAD

**Issue by brsolomon-deloitte** [elastic/helm-charts#1710]
Is the Elastic team still supporting Elastic stack 7.17.x releases for these Helm charts? It looks like most of the charts were last updated about six months ago to use the `7.17.3` images by default whereas 7.17.6 is the latest patch release.

If there are no plans to update the `7.17` branch here, could that be pinned as a GitHub Issue?

**Comment by jmlrt** [comment]
Hey @brsolomon-deloitte,
Indeed, we didn't release versions after 7.17.3, and decided to not release new version of charts for every patch version.

Not sure if we'll release newer 7.17.x versions but you can use the 7.17.3 chart version with new stack images by setting `imageTag` value.

**Comment by technotaff-nbs** [comment]
Helm best practice is to *not* override the image version in a helm chart (to ensure compatibility between the deployment and the container image).

Could elastic please reconsider their position on this?

**Comment by jmlrt** [comment]
> Helm best practice is to _not_ override the image version in a helm chart

Can you add more details and sources?
90% of the Helm charts do have a value to override the image tag. This is also part of the official Helm chart template when using the `helm create` command and has been mentioned as a best practice by Helm maintainers in the PR that added it: https://github.com/helm/helm/pull/7878#issuecomment-609628459

While we ourself recommend using the same version for the Helm chart and the Docker image in [the doc](https://github.com/elastic/helm-charts/blob/v7.17.3/README.md#supported-configurations), we don't release any more new charts version for all patch releases, so you can override the Docker image tag for a more recent patch version (for example 7.17.3 chart with 7.17.5 images).

**Comment by jmlrt** [comment]
Opened https://github.com/elastic/helm-charts/pull/1723 to make it clear in the doc.

**Comment by brsolomon-deloitte** [comment]
> Can you add more details and sources? 90% of the Helm charts do have a value to override the image tag. 

Yes, but 90% of Helm charts also follow the best practices of:

1. Keeping the _default_ image tag at an up-to-date (latest patch release) version
2. Properly bumping the chart version whenever the default image tag is bumped

[Bitnami charts](https://github.com/bitnami/charts) are one good example.
