### ISSUE TITLE
Move to Elastic Cloud on Kubernetes

### ISSUE THREAD

**Issue by ebuildy** [elastic/helm-charts#1716]
**Describe the feature:**

Since deploying elastic applications (elasticsearch, kibana ...) with "classic" Helm chart is being deprecated, I suggest we could **use ECK to deploy application**, we could migrate all template to use ECK operator, keep all ressources not managed by ECK, such as ingress / network-policy etc...  but replace statefulset by ECK.

As a progressive migration, we could create new charts: "elasticsearch" -> "elasticsearch-eck" and copy as much as possible features from legacy charts.

Also the Helm chart to deploy the operator it-self, should be moved here, so this nice github repository could continue to live!

**Comment by jmlrt** [comment]
👋🏻 @ebuildy, thanks for all your contributions to this repository, as mentioned in https://github.com/elastic/helm-charts/issues/1731, the ECK charts are in the ECK repository: https://github.com/elastic/cloud-on-k8s/tree/main/deploy

We don't expect to migrate them to this repository as it makes more sense for it to be closer to the ECK Operator code as it is maintained by the same team.
