### ISSUE TITLE
skipped value for image: Not a table.

### ISSUE THREAD

**Issue by ceastman-ibm** [elastic/helm-charts#177]
**Chart version:**
7.1.1
Kubernetes version:
v1.12.8+IKS
Kubernetes provider: E.g. GKE (Google Kubernetes Engine)
IBM Cloud
Helm Version:
2.9.1
**`helm get release` output**

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

```
```

**Describe the bug:**
Elasticsearch image is not deployed. When I describe the elasticsearch pod I noticed the image has this value:

    Image:      map[pullPolicy:IfNotPresent pullSecret:docker]:7.1.1

when I do a helm debug i see this warning:

2019/06/17 14:53:53 warning: skipped value for image: Not a table.

here is the image line from my values.yaml:

image: "docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "7.1.1"
imagePullPolicy: "IfNotPresent"
**Steps to reproduce:**

1.
2.
3.

**Expected behavior:**

**Provide logs and/or server output (if relevant):**

**Any additional context:**

**Comment by Crazybus** [comment]
> helm get elasticsearch (replace elasticsearch with the name of your helm release)

Could you give me the output of this please. The section you have given me from your `values.yaml` looks correct and is the same as the default values. So there must be something else interfering with the values.

**Comment by ceastman-ibm** [comment]
@Crazybus this issue can be closed, i found this was a self inflicted issue, i have other yaml files that are getting included.
