### ISSUE TITLE
How to enable x-pack on elasticseach in kubernetes ?

### ISSUE THREAD

**Issue by mounaBoo** [elastic/helm-charts#180]
Hello, 

I have instaled elasticsearch and kibana using the helm chart I wanted to enable the xpack in elasticsearch so that I could have user management on kibana.

How to do it ?

**Comment by Crazybus** [comment]
To be able to configure user management you first need to enable security in Kibana by following https://www.elastic.co/guide/en/kibana/current/using-kibana-with-security.html. The charts include examples for how to do this https://github.com/elastic/helm-charts/blob/master/kibana/README.md#security

I'm closing this issue out. If you have further questions please open up a thread on our discuss forums.  To quote the issue template: 

> We use GitHub to track feature requests and bug reports. Please do not submit issues for questions about how to use features of these helm charts, best practices, or development related help.

> However, we do want to help! Head on over to our official forums and ask your questions there. In additional to awesome, knowledgeable community contributors, core helm chart developers are on the forums every single day to help you out.

> The forums are here: https://discuss.elastic.co/

> We can't stop you from opening an issue here, but it will likely linger without a response for days or weeks before it is closed and we ask you to join us on the forums instead. Save yourself the time, and ask on the forums today.
