### ISSUE TITLE
[elasticsearch] Persistence annotations not working

### ISSUE THREAD

**Issue by eddycharly** [elastic/helm-charts#183]
**Chart version:**

7.1.1

**Kubernetes version:**

NA

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)

AWS

**Helm Version:**

N1

**Describe the bug:**

pvc annotations in statefulset template is wrong.

see https://github.com/elastic/helm-charts/blob/7.1.1/elasticsearch/templates/statefulset.yaml#L26

the generated annotations will have incorrect indentation.

**Comment by Crazybus** [comment]
Thanks for reporting this! I have opened up https://github.com/elastic/helm-charts/pull/186 with the fix.

**Comment by eddycharly** [comment]
👍
