### ISSUE TITLE
pod are runing but unhealthy

### ISSUE THREAD

**Issue by linqingping** [elastic/helm-charts#199]
![深度截图_选择区域_20190703152034](https://user-images.githubusercontent.com/20528139/60571664-9f0be680-9da6-11e9-9795-b537e54518b4.png)
![深度截图_选择区域_20190703152054](https://user-images.githubusercontent.com/20528139/60571672-a16e4080-9da6-11e9-99f2-abb0a512341d.png)

**Comment by tetianakravchenko** [comment]
Looks like it is a stale message, that appeared during the cluster initialization, isn't it?

**Comment by linqingping** [comment]
Cluster initialization will occur？ @tetianakravchenko

**Comment by Crazybus** [comment]
> Looks like it is a stale message, that appeared during the cluster initialization, isn't it?

This is correct! @linqingping it looks like your cluster is healthy and running. Please re open this issue if you are having problems though.
