### ISSUE TITLE
Security enabling:  Error: no objects visited

### ISSUE THREAD

**Issue by mounaBoo** [elastic/helm-charts#201]
Hello , 

I have installed helm chart for elasticsearch and kibana and I want to add security for elasticsearch so 

I copied the security.yml and Chart.yaml into my kubernetes.
when I execute this 

`helm upgrade --wait --timeout=600 --install --values security.yml elasticsearch ./`

I am getting this error 

> Release "elasticsearch" has been upgraded.
> Error: no objects visited

**Comment by Crazybus** [comment]
I haven't seen that error before which seems to be coming from helm. Could you show me the output of `helm get elasticsearch`?

Couple of other questions:

1. Is it actually working or not? The first message makes it sound like helm did actually apply the changes
2. Can you confirm that you did all of the steps in https://github.com/elastic/helm-charts/tree/master/elasticsearch#security

**Comment by mounaBoo** [comment]
I fixed this error finally it was a problem with directory, 

security is finally enabled on elasticsearch but I have probelem enabling it on kibana this is the error I am getting 
`Error: UPGRADE FAILED: timed out waiting for the condition`


once I run make ( from /kibana/examples/security )

**Comment by Crazybus** [comment]
This one is another duplicate. Closing it in favor of the testing being done with the new docs in https://github.com/elastic/helm-charts/pull/205
