### ISSUE TITLE
How to create security certificate pem for elasticsearch an kibana

### ISSUE THREAD

**Issue by mounaBoo** [elastic/helm-charts#211]
I am trying to intall the helm chart of elasticsearch and kibana but in the security configuration I need to have :
```
certificateAuthorities: /usr/share/kibana/config/certs/elastic-certificate.pem

  key: /usr/share/kibana/config/certs/kibana/kibana.key
  certificate: /usr/share/kibana/config/certs/kibana/kibana.crt
```

can any one tell me how to create those file using the elasticsearch certutil.

**Comment by Crazybus** [comment]
I'm going to close this since its a duplicate of the discussions we are having in https://github.com/elastic/helm-charts/pull/205. This PR adds automation for automatically generating the certificates.
