### ISSUE TITLE
ability to add additional labels

### ISSUE THREAD

**Issue by dugouchet** [elastic/helm-charts#212]
**Describe the feature:**
We need to add additional labels for monitoring into the daemonset as it's the case for podAnnotation.
**Describe a specific use case for the feature:**
Monitoring for prometheus, Service mesh ( istio), are based on the label.

PR should come from me !!

**Comment by Crazybus** [comment]
> PR should come from me !!

Awesome! I just merged in the first version of the metricbeat chart in https://github.com/elastic/helm-charts/pull/127. Could you also add the additonal labels into it as well? The charts are very very similar so it should just be a matter of copy paste.

**Comment by dugouchet** [comment]
cf la PR : https://github.com/elastic/helm-charts/pull/214

**Comment by Crazybus** [comment]
Did you also plan on porting the same change to the metricbeat chart? If not I can pick that up.
