### ISSUE TITLE
Independent release for minor changes

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/helm-charts#223]
**Describe the feature:**

Release charts independently one from another for minor changes, that are not related to the stack version.

**Comment by Crazybus** [comment]
> Release charts independently one from another for minor changes, that are not related to the stack version.

Could you explain why you would like this? Having to keep track of which versions are compatible with which is the exact reason why we moved to a unified version for all products in the stack. 

Or is this more to do with the release schedule? I just looked at your recent PR and found this comment https://github.com/elastic/helm-charts/pull/197#issuecomment-509537208. I'm more than happy to do extra releases between the stack releases (and will do one now).

**Comment by Crazybus** [comment]
Note: I have also updated my filters to look for comments in closed pull requests (which were filtered out before) so that I don't miss this next time.

**Comment by tetianakravchenko** [comment]
> Or is this more to do with the release schedule?

Yes, it is more about the release schedule, I thought charts release sticks to the stack version, just misunderstood that. And I really didn't take into account this point:

> Having to keep track of which versions are compatible with which is the exact reason why we moved to a unified version for all products in the stack.

thank you for the clarification and release!

**Comment by Crazybus** [comment]
Release has just been pushed!
