### ISSUE TITLE
Standardize on Elasticsearch connection value names

### ISSUE THREAD

**Issue by Crazybus** [elastic/helm-charts#23]
As discovered in https://github.com/elastic/helm-charts/pull/22#pullrequestreview-188478296 the values used to connect to Elasticsearch differ between Kibana and Elasticsearch. In the future when charts are added for Logstash/Beats/others this could become even more fragmented and annoying to configure. 

Because the Elasticsearch chart needs to be able to access parts of the Elasticsearch URL separately I think it makes most sense to split the URL up into separate variables.   

Proposal:

```
esHost: elasticsearch-master
esProtocol: http
esPort: 9200
```

**Comment by jordansissel** [comment]
> In the future when charts are added for Logstash/Beats/others

Indeed, I have a beats chart which has these values:

```
beats-setup:
  elasticsearchAddress: draal-data:9200
  kibanaAddress: draal-kibana:5601
```

It'd be nice to reuse where possible.
