### ISSUE TITLE
[elasticsearch] PSP and ServiceAccount creation / support

### ISSUE THREAD

**Issue by maximelenair** [elastic/helm-charts#232]
Hello,

This issue is related to an [existing PR](https://github.com/elastic/helm-charts/pull/207) - please tell if this is not in the right spot.

The current iteration of the Helm chart will not run on a k8s cluster with the PSP admission controller enabled.
This feature would allow user to either:
- Reference by name the PSP and SA created by other means
- Create the required PSP and SA with few parameters

Add the possibility to create or reference the following resources with the Elasticsearch Helm Chart:
1) `Pod Security Policy`:
- Referencing an external PSP by name
- Creating a PSP with minimal permissions for the Helm Chart to run
2) `Service Account`, `Role` and `RoleBinding`:
- Referencing an external SA by name
- Creating a SA (and the associated role and role binding) linked to the PSP

Ideally the current behaviour of the chart would not be changed by this.

I've got a working implementation of the above (with unit test) that I'm currently using on a fork, if there's interest in this I can create a PR and work from there as a starting point.

**Comment by Crazybus** [comment]
> I've got a working implementation of the above (with unit test) that I'm currently using on a fork, if there's interest in this I can create a PR and work from there as a starting point.

Please do! I believe that current PR has gone stale. That particular PR is also implementing some other things so there is still value in keeping it open.
