### ISSUE TITLE
nodeSelector has desapeared in fielbeat values

### ISSUE THREAD

**Issue by remiville** [elastic/helm-charts#242]
Please reinsert the nodeSelector in fielbeat values or give another solution

**Comment by Crazybus** [comment]
> reinsert the nodeSelector

This was never part of the filebeat chart so it was never removed. 

> give another solution

I'm not sure what problem it is you are trying to solve. If you could explain that first then I might be able to help you with a solution. With the limited information you have given my best bet is that you want to run the filebeat daemonset on only some nodes as described in https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#running-pods-on-only-some-nodes

**Comment by remiville** [comment]
Hi,

Thank you for yor quick answer.

Yes I want to run the filebeat daemonset on only some nodes.
With the stable/filebeat chart I could use the nodeSelector entry, but it seems to not exist any more in elastic/filebeat chart (despite that for example the tolerations entry still exist)

There's maybe a way to do the same with a different syntax in elastic/filebeat but I don't know how.

**Comment by Crazybus** [comment]
I have opened a PR making the nodeSelector and affinity rules configurable for filebeat and metricbeat https://github.com/elastic/helm-charts/pull/243.

I'm guessing the use case is that you have a shared kubernetes cluster where you have dedicated nodes for different teams or environments? Then it would make sense to want to run different configurations for filebeat depending on the node. Not a use case that I had thought of.

**Comment by remiville** [comment]
Thank you !

In fact I'm new to cloud, kubernets and helm etc. and it appeared it is not a big issue for the project I work on.
However I think it a good thing to have the nodeSelector, if you don't want to log everything, it can be used as a first filter before using autodiscover conditions...
