### ISSUE TITLE
[Kibana] Support plugin installation

### ISSUE THREAD

**Issue by diversario** [elastic/helm-charts#246]
**Describe the feature:**
The [pre-deprecated Kibana chart](https://github.com/helm/charts/tree/master/stable/kibana) supports plugin installation via chart values. It would be helpful if the new Kibana chart supported that as well.

**Describe a specific use case for the feature:**
Using Kibana plugins without custom Docker image and/or a custom Helm chart (which add complexity for users).

**Comment by geede** [comment]
We are using this kibana chart, but want to use elastalert plugin.  Any ideas on when this issue will be fixed?

**Comment by NorDroN** [comment]
I've created PR https://github.com/elastic/helm-charts/pull/285

**Comment by japzio** [comment]
#51 Old discussion whether or not to expose init containers

**Comment by dminca** [comment]
@Crazybus acording to https://github.com/elastic/helm-charts/issues/51#issuecomment-461012196 , should we do the same for Kibana also?

**Comment by Crazybus** [comment]
> @Crazybus acording to #51 (comment) , should we do the same for Kibana also?

Yup! This is still the recommended way to install plugins.
