### ISSUE TITLE
kibana readiness probe failing on both http and https

### ISSUE THREAD

**Issue by nishantsh77** [elastic/helm-charts#247]
**Chart version:** kibana-7.2.0

**Kubernetes version:** 1.15.1

**Kubernetes provider:** centos7 based local cluster

**Helm Version:** v2.14.2

**`helm get release` output**
[root@node03 kibana-helm-chart]# helm get kibana
REVISION: 1
RELEASED: Tue Aug  6 09:56:37 2019
CHART: kibana-7.2.0
USER-SUPPLIED VALUES:
imageTag: 7.1.1

COMPUTED VALUES:
affinity: {}
antiAffinity: hard
antiAffinityTopologyKey: kubernetes.io/hostname
elasticsearchHosts: http://elasticsearch-master:9200
elasticsearchURL: ""
extraEnvs: []
fullnameOverride: ""
healthCheckPath: /app/kibana
httpPort: 5601
image: docker.elastic.co/kibana/kibana
imagePullPolicy: IfNotPresent
imagePullSecrets: []
imageTag: 7.1.1
ingress:
  annotations: {}
  enabled: false
  hosts:
  - chart-example.local
  path: /
  tls: []
kibanaConfig: {}
maxUnavailable: 1
nameOverride: ""
nodeSelector: {}
podSecurityContext:
  fsGroup: 1000
priorityClassName: ""
protocol: http
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5
replicas: 1
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 500m
secretMounts: []
securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
serverHost: 0.0.0.0
service:
  annotations: {}
  nodePort: null
  port: 5601
  type: ClusterIP
serviceAccount: ""
tolerations: []
updateStrategy:
  type: Recreate

HOOKS:
MANIFEST:

---
# Source: kibana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kibana-kibana
  labels:
    app: kibana
    release: "kibana"
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 5601
      protocol: TCP
      name: http
      targetPort: 5601
  selector:
    app: kibana
    release: "kibana"
---
# Source: kibana/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-kibana
  labels:
    app: kibana
    release: "kibana"
spec:
  replicas: 1
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: kibana
      release: "kibana"
  template:
    metadata:
      labels:
        app: kibana
        release: "kibana"
      annotations:

    spec:
      securityContext:
        fsGroup: 1000

      volumes:
      containers:
      - name: kibana
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000

        image: "docker.elastic.co/kibana/kibana:7.1.1"
        env:
          - name: ELASTICSEARCH_HOSTS
            value: "http://elasticsearch-master:9200"
          - name: SERVER_HOST
            value: "0.0.0.0"
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 3
          timeoutSeconds: 5

          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                http () {
                    local path="${1}"
                    set -- -XGET -s --fail

                    if [ -n "${ELASTIC_USERNAME}" ] && [ -n "${ELASTIC_PASSWORD}" ]; then
                      set -- "$@" -u "${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}"
                    fi

                    curl -k "$@" "http://localhost:5601${path}"
                }

                http "/app/kibana"
        ports:
        - containerPort: 5601
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 500m

        volumeMounts:

**Describe the bug:** 
"Readiness probe failed:" is coming. I am not sure why readiness probe is failing other I can access Kibana UI and perform required functions. In logs also, I can't see any error.

I tried both http and https ways and getting same error.

**Steps to reproduce:**

1. I just followed steps mentioned on "https://github.com/elastic/helm-charts/tree/master/kibana". As we are using ES with version 7.1.1, so I deployed Kibana with same version.
2. helm install --name kibana elastic/kibana --set imageTag=7.1.1
3. using kubectl command, I exec inside pod and ran readiness command and got output.
"exec [sh -c #!/usr/bin/env bash -e
http () {
    local path="${1}"
    set -- -XGET -s --fail

    if [ -n "${ELASTIC_USERNAME}" ] && [ -n "${ELASTIC_PASSWORD}" ]; then
      set -- "$@" -u "${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}"
    fi

    curl -k "$@" "http://localhost:5601${path}"
}

http "/app/kibana"
]"

**Expected behavior:**
Readiness probe should not fail.

**Provide logs and/or server output (if relevant):**

**Any additional context:**

**Comment by nishantsh77** [comment]
I modified the readiness probe settings and now readiness probe is working.

**Comment by shahinkl** [comment]
@nishantsh77 
Can you please share with us the settings which worked for you?

**Comment by dpkirchner** [comment]
Setting `healthCheckPath: /api/status` in `values.yaml` did the job for me. The probe in the latest chart is looking for HTTP responses with status 200 but `/app/kibana` (default) returns 302.
