### ISSUE TITLE
[elasticsearch] how to deploy different settings for master and data pods

### ISSUE THREAD

**Issue by rewt** [elastic/helm-charts#252]
In the helm version of this chart, each ES role was broken out into its own respective configuration section for ingress, data, and master roles.  This was helpful in deploying different specs for different pod needs.

Moving into this chart, it appears the suggested way is to have release for each role type?  So would I create a values-master.yaml and values-data.yaml (I don't use ingress role)?  Or is it best to branch into each role to make sure the values file receives updates up over time?

**Comment by Crazybus** [comment]
> Moving into this chart, it appears the suggested way is to have release for each role type?

This chart is designed to be flexible, so the suggested way is to decide yourself which roles and which groups of nodes you want. If you want to have multiple data only nodes with different sizing and configuration then that is possible. If you want to have a group of dedicated nodes for [machine learning](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#ml-node) then you can do that too. The nice thing is you are not locked into a specific architecture and can change it at any time. If you start with the default "all roles" setup you can easily add dedicated data nodes down the line. 

In the [Usage and getting started](https://github.com/elastic/helm-charts/tree/master/elasticsearch#usage-notes-and-getting-started) section there is a link to an example using [multiple releases](https://github.com/elastic/helm-charts/tree/master/elasticsearch/examples/multi) for how to do this. 

The [migration example](https://github.com/elastic/helm-charts/tree/master/elasticsearch/examples/migration) contains configuration which matches the default settings that came with https://github.com/helm/charts/tree/master/stable/elasticsearch.

If you want to manage and re-use some of the settings you can create a [child chart](https://github.com/elastic/helm-charts/pull/22/files) that merges the values.
