### ISSUE TITLE
Not able to exec to pods security-master-0 is forbidden

### ISSUE THREAD

**Issue by dcvtruong** [elastic/helm-charts#256]
**Chart version:**
7.3.0
**Kubernetes version:**
1.13.0
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
kubespray
**Helm Version:**
2.12.1
**`helm get release` output**

      $ helm get helm-es-security
      REVISION: 1
      RELEASED: Fri Aug 16 15:27:08 2019
      CHART: elasticsearch-7.3.0
      USER-SUPPLIED VALUES:
      clusterName: security
      esConfig:
        elasticsearch.yml: |
          xpack.security.enabled: true
          xpack.security.transport.ssl.enabled: true
          xpack.security.transport.ssl.verification_mode: certificate
          xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
          xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
          xpack.security.http.ssl.enabled: true
          xpack.security.http.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
          xpack.security.http.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
      extraEnvs:
      - name: ELASTIC_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: elastic-credentials
      - name: ELASTIC_USERNAME
        valueFrom:
          secretKeyRef:
            key: username
            name: elastic-credentials
      nodeGroup: master
      protocol: https
      roles:
        data: "true"
        ingest: "true"
        master: "true"
      secretMounts:
      - name: elastic-certificates
        path: /usr/share/elasticsearch/config/certs
        secretName: elastic-certificates

      COMPUTED VALUES:
      antiAffinity: hard
      antiAffinityTopologyKey: kubernetes.io/hostname
      clusterHealthCheckParams: wait_for_status=green&timeout=1s
      clusterName: security
      esConfig:
        elasticsearch.yml: |
          xpack.security.enabled: true
          xpack.security.transport.ssl.enabled: true
          xpack.security.transport.ssl.verification_mode: certificate
          xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
          xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
          xpack.security.http.ssl.enabled: true
          xpack.security.http.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
          xpack.security.http.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
      esJavaOpts: -Xmx1g -Xms1g
      esMajorVersion: ""
      extraEnvs:
      - name: ELASTIC_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: elastic-credentials
      - name: ELASTIC_USERNAME
        valueFrom:
          secretKeyRef:
            key: username
            name: elastic-credentials
      extraInitContainers: ""
      extraVolumeMounts: ""
      extraVolumes: ""
      fsGroup: ""
      fullnameOverride: ""
      httpPort: 9200
      image: docker.elastic.co/elasticsearch/elasticsearch
      imagePullPolicy: IfNotPresent
      imagePullSecrets: []
      imageTag: 7.3.0
      ingress:
        annotations: {}
        enabled: false
        hosts:
        - chart-example.local
        path: /
        tls: []
      initResources: {}
      labels: {}
      lifecycle: {}
      masterService: ""
      masterTerminationFix: false
      maxUnavailable: 1
      minimumMasterNodes: 2
      nameOverride: ""
      networkHost: 0.0.0.0
      nodeAffinity: {}
      nodeGroup: master
      nodeSelector: {}
      persistence:
        annotations: {}
        enabled: true
      podAnnotations: {}
      podManagementPolicy: Parallel
      podSecurityContext:
        fsGroup: 1000
      priorityClassName: ""
      protocol: https
      readinessProbe:
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 3
        timeoutSeconds: 5
      replicas: 3
      resources:
        limits:
          cpu: 1000m
          memory: 5Gi
        requests:
          cpu: 100m
          memory: 2Gi
      roles:
        data: "true"
        ingest: "true"
        master: "true"
      schedulerName: ""
      secretMounts:
      - name: elastic-certificates
        path: /usr/share/elasticsearch/config/certs
        secretName: elastic-certificates
      securityContext:
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
        runAsUser: 1000
      service:
        annotations: {}
        nodePort: null
        type: ClusterIP
      sidecarResources: {}
      sysctlInitContainer:
        enabled: true
      sysctlVmMaxMapCount: 262144
      terminationGracePeriod: 120
      tolerations: []
      transportPort: 9300
      updateStrategy: RollingUpdate
      volumeClaimTemplate:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: elkdevtestsc

      HOOKS:
      ---
      # helm-es-security-ilszd-test
      apiVersion: v1
      kind: Pod
      metadata:
        name: "helm-es-security-ilszd-test"
        annotations:
          "helm.sh/hook": test-success
      spec:
        containers:
        - name: "helm-es-security-lswwy-test"
          image: "docker.elastic.co/elasticsearch/elasticsearch:7.3.0"
          command:
            - "sh"
            - "-c"
            - |
              #!/usr/bin/env bash -e
              curl -XGET --fail 'security-master:9200/_cluster/health?wait_for_status=green&timeout=1s'
        restartPolicy: Never
      MANIFEST:

      ---
      # Source: elasticsearch/templates/poddisruptionbudget.yaml
      apiVersion: policy/v1beta1
      kind: PodDisruptionBudget
      metadata:
        name: "security-master-pdb"
      spec:
        maxUnavailable: 1
        selector:
          matchLabels:
            app: "security-master"
      ---
      # Source: elasticsearch/templates/configmap.yaml
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: security-master-config
        labels:
          heritage: "Tiller"
          release: "helm-es-security"
          chart: "elasticsearch-7.3.0"
          app: "security-master"
      data:
        elasticsearch.yml: |
          xpack.security.enabled: true
          xpack.security.transport.ssl.enabled: true
          xpack.security.transport.ssl.verification_mode: certificate
          xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
          xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
          xpack.security.http.ssl.enabled: true
          xpack.security.http.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
          xpack.security.http.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
      ---
      # Source: elasticsearch/templates/service.yaml
      kind: Service
      apiVersion: v1
      metadata:
        name: security-master-headless
        labels:
          heritage: "Tiller"
          release: "helm-es-security"
          chart: "elasticsearch-7.3.0"
          app: "security-master"
        annotations:
          service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
      spec:
        clusterIP: None # This is needed for statefulset hostnames like elasticsearch-0 to resolve
        # Create endpoints also if the related pod isn't ready
        publishNotReadyAddresses: true
        selector:
          app: "security-master"
        ports:
        - name: http
          port: 9200
        - name: transport
          port: 9300
      ---
      # Source: elasticsearch/templates/service.yaml
      kind: Service
      apiVersion: v1
      metadata:
        name: security-master
        labels:
          heritage: "Tiller"
          release: "helm-es-security"
          chart: "elasticsearch-7.3.0"
          app: "security-master"
        annotations:
          {}
          
      spec:
        type: ClusterIP
        selector:
          heritage: "Tiller"
          release: "helm-es-security"
          chart: "elasticsearch-7.3.0"
          app: "security-master"
        ports:
        - name: http
          protocol: TCP
          port: 9200
        - name: transport
          protocol: TCP
          port: 9300
      ---
      # Source: elasticsearch/templates/statefulset.yaml
      apiVersion: apps/v1beta1
      kind: StatefulSet
      metadata:
        name: security-master
        labels:
          heritage: "Tiller"
          release: "helm-es-security"
          chart: "elasticsearch-7.3.0"
          app: "security-master"
        annotations:
          esMajorVersion: "7"
      spec:
        serviceName: security-master-headless
        selector:
          matchLabels:
            app: "security-master"
        replicas: 3
        podManagementPolicy: Parallel
        updateStrategy:
          type: RollingUpdate
        volumeClaimTemplates:
        - metadata:
            name: security-master
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: elkdevtestsc
            
        template:
          metadata:
            name: "security-master"
            labels:
              heritage: "Tiller"
              release: "helm-es-security"
              chart: "elasticsearch-7.3.0"
              app: "security-master"
            annotations:
              
              configchecksum: 35a54914853cbef94ccfcc3ae99ac46d5af722ebb70249a835d33b059e04730
          spec:
            securityContext:
              fsGroup: 1000
              
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - "security-master"
                  topologyKey: kubernetes.io/hostname
            terminationGracePeriodSeconds: 120
            volumes:
              - name: elastic-certificates
                secret:
                  secretName: elastic-certificates
              - name: esconfig
                configMap:
                  name: security-master-config
            initContainers:
            - name: configure-sysctl
              securityContext:
                runAsUser: 0
                privileged: true
              image: "docker.elastic.co/elasticsearch/elasticsearch:7.3.0"
              command: ["sysctl", "-w", "vm.max_map_count=262144"]
              resources:
                {}
                
            containers:
            - name: "elasticsearch"
              securityContext:
                capabilities:
                  drop:
                  - ALL
                runAsNonRoot: true
                runAsUser: 1000
                
              image: "docker.elastic.co/elasticsearch/elasticsearch:7.3.0"
              imagePullPolicy: "IfNotPresent"
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 3
                timeoutSeconds: 5
                
                exec:
                  command:
                    - sh
                    - -c
                    - |
                      #!/usr/bin/env bash -e
                      # If the node is starting up wait for the cluster to be ready (request params: 'wait_for_status=green&timeout=1s' )
                      # Once it has started only check that the node itself is responding
                      START_FILE=/tmp/.es_start_file

                      http () {
                          local path="${1}"
                          if [ -n "${ELASTIC_USERNAME}" ] && [ -n "${ELASTIC_PASSWORD}" ]; then
                            BASIC_AUTH="-u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}"
                          else
                            BASIC_AUTH=''
                          fi
                          curl -XGET -s -k --fail ${BASIC_AUTH} https://127.0.0.1:9200${path}
                      }

                      if [ -f "${START_FILE}" ]; then
                          echo 'Elasticsearch is already running, lets check the node is healthy'
                          http "/"
                      else
                          echo 'Waiting for elasticsearch cluster to become cluster to be ready (request params: "wait_for_status=green&timeout=1s" )'
                          if http "/_cluster/health?wait_for_status=green&timeout=1s" ; then
                              touch ${START_FILE}
                              exit 0
                          else
                              echo 'Cluster is not yet ready (request params: "wait_for_status=green&timeout=1s" )'
                              exit 1
                          fi
                      fi
              ports:
              - name: http
                containerPort: 9200
              - name: transport
                containerPort: 9300
              resources:
                limits:
                  cpu: 1000m
                  memory: 5Gi
                requests:
                  cpu: 100m
                  memory: 2Gi
                
              env:
                - name: node.name
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: cluster.initial_master_nodes
                  value: "security-master-0,security-master-1,security-master-2,"
                - name: discovery.seed_hosts
                  value: "security-master-headless"
                - name: cluster.name
                  value: "security"
                - name: network.host
                  value: "0.0.0.0"
                - name: ES_JAVA_OPTS
                  value: "-Xmx1g -Xms1g"
                - name: node.data
                  value: "true"
                - name: node.ingest
                  value: "true"
                - name: node.master
                  value: "true"
                - name: ELASTIC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: elastic-credentials
                - name: ELASTIC_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: elastic-credentials
                
              volumeMounts:
                - name: "security-master"
                  mountPath: /usr/share/elasticsearch/data
                - name: elastic-certificates
                  mountPath: /usr/share/elasticsearch/config/certs
                - name: esconfig
                  mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
                  subPath: elasticsearch.yml
e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

```
```

**Describe the bug:**

**Steps to reproduce:**

1. Run 'make' from helm-charts/elasticsearch/examples/security
2. The install failed during 'helm test...' or run 'kubectl exec -it security-master-0 bash' 
3. Error: 

       Testing with pod: security-master-0
       Error from server (Forbidden): pods "security-master-0" is forbidden: cannot exec into or attach to a privileged container make: *** [goss] Error 1

**Expected behavior:**
Should be able to access the pods
**Provide logs and/or server output (if relevant):**

       $ kubectl exec -it security-master-0 bash
          Error from server (Forbidden): pods "security-master-0" is forbidden: cannot exec into or attach to a privileged container
**Any additional context:**

**Comment by Crazybus** [comment]
> Error from server (Forbidden): pods "security-master-0" is forbidden: cannot exec into or attach to a privileged container make: *** [goss] Error 1

This seems like something specific with your Kubernetes deployment itself. Can you exec into other containers in this cluster? Could you also give me more details about your kubespray deployment? 

One thing you could try is doing:

```
podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
```

I saw this in #15 and I'm wondering if not having `runAsUser` set could be forcing some Kubernetes providers/versions to default to running as root.
