### ISSUE TITLE
loadBalancerIP in service

### ISSUE THREAD

**Issue by comradesharf** [elastic/helm-charts#257]
**Describe the feature:**
Add loadBalancerIP in service

**Describe a specific use case for the feature:**
I use loadBalancerIP to specify static load balancer IP address using [GCP internal load balancing](https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing). This internal IP address will be added as a record in CloudDNS to allow connection in private VPC

**Comment by travisghansen** [comment]
Still valid :)

**Comment by andyliddle** [comment]
I could do with this added too,

**Comment by jmlrt** [comment]
closed by #539
