### ISSUE TITLE
persistence.enabled is not respected

### ISSUE THREAD

**Issue by jwsomis** [elastic/helm-charts#264]
**Chart version:**
7.3.0
**Kubernetes version:**
1.12.10
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
KOps (AWS)
**Helm Version:**
2.14.3
**`helm get release` output**

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

```
```

**Describe the bug:**
I have persistence.enabled set to false, but the default data volumeClaimTemplate and mount are still created. I'm using aws i3 instances and want to use the ephemeral local disk, but I can't override the default data mount because the `persistence.enabled: false` is not respected. 
I have also tried specifying a different data path in the esConfig, but there is an ownershiip issue on any other directory that I have not been able to get around. 

**Steps to reproduce:**

1.
2.
3.

**Expected behavior:**

**Provide logs and/or server output (if relevant):**

**Any additional context:**

**Comment by Crazybus** [comment]
From a templating point of view we have a test making sure that it will not be created. https://github.com/elastic/helm-charts/blob/132bd326aef2025d9c5d8c14c69758cb59368f89/elasticsearch/tests/elasticsearch_test.py#L608-L615

Could you post this output? 

> e.g. helm get elasticsearch (replace elasticsearch with the name of your helm release)

That way I can check if anything else might be causing the variable to not be set properly that should be disabling it.
