### ISSUE TITLE
Support fullnameOverride (Kibana chart)

### ISSUE THREAD

**Issue by ppawel** [elastic/helm-charts#267]
**Describe the feature:**

Currently "fullname" helper macro provides name to service, ingress etc. and it uses release name, chart name (and optionally you can input "nameOverride") and this results in a "x-y" construct.

Allowing the user to specify `fullnameOverride` in values file will give additional flexibility with naming resources.

Examples:

https://github.com/helm/charts/blob/master/stable/grafana/templates/_helpers.tpl
https://github.com/helm/charts/blob/master/stable/prometheus/templates/_helpers.tpl

**Describe a specific use case for the feature:**

I want my service, ingress and other resources to be named just "kibana", without any prefix, like "monitoring-kibana" (because they are anyway in the "monitoring" namespace in my case so it's redundant).

**Comment by davispw** [comment]
This is inconsistent with elasticsearch's helm chart (which does not use the Release name at all--the service is always just named "elasticsearch-master").

**Comment by morganchristiansson** [comment]
I agree. My pod names are:

- kibana-kibana-xxx
- filebeat-filebeat-xxx
- metricbeat-metricbeat-xxx

Please fix-fix

**Comment by jmlrt** [comment]
I'm closing this issue as it was implemented in #330

**Comment by ppawel** [comment]
Thanks @tusciucalecs, you are a hero-hero!
