### ISSUE TITLE
kubernetes helm install with xpack security enabled won't start - security index is unavailable

### ISSUE THREAD

**Issue by ceastman-ibm** [elastic/helm-charts#273]
**Chart version:**
7.3.0
**Kubernetes version:**
1.14
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
IBM Cloud

**Helm Version:**

**`helm get release` output**

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

```
```

**Describe the bug:**
Master nodes won't start: seeing this error in the logs:
{"type": "server", "timestamp": "2019-09-06T18:50:44,128+0000", "level": "ERROR", "component": "o.e.x.s.a.e.NativeUsersStore", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-0", "cluster.uuid": "SAahFVjPToKipK4KvR6zLQ", "node.id": "7-93zAjkSOKaGkNktJSbRw",  "message": "security index is unavailable. short circuiting retrieval of user [redacted]"  }
**Steps to reproduce:**

1.  added the following to values:
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true
2.
roles:
  master: "true"
  ingest: "false"
  data: "false"
3.
extraEnvs:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username

**Expected behavior:**
3 master nodes created with basic auth enabled.

**Provide logs and/or server output (if relevant):**

**Any additional context:**

**Comment by ceastman-ibm** [comment]
looks like internal https needs to be setup for xpack security to be enabled. i installed docker locally and ran make in the examples/security folder. im able to install master, data and client clusters in the same kubernetes cluster.

**Comment by mattfung** [comment]
@ceastman-ibm are you able to run elasticsearch with basic auth in a remote cluster?
facing the same problem currently

**Comment by SCLogo** [comment]
same issue here. Any idea ?

**Comment by jgato** [comment]
the same here :(

**Comment by BlackDark** [comment]
Run into similar problems. ELASTIC_USERNAME env was without effect for me. Was always `elastic` so i kept it for solving the readiness check in k8s. After that the node started up and i was able to connect kibana and log in with `elastic` user.

**Comment by dunefro** [comment]
@BlackDark 
Yes, that worked for me too, I made the user with a different name and i got the same issue. I switched back to the name `elastic` and it worked for me.

**Comment by Daviswenpy** [comment]
worked for me too! But i wonder why it's so wired, i use k8s to deploy es-cluster, there's no such problem, i can use any username
