### ISSUE TITLE
create indexes after es cluster is up & running

### ISSUE THREAD

**Issue by vishnugs** [elastic/helm-charts#278]
Hey, 

I have initiated elastic search this helm chart running with es 7.2.0 image. I want to create indexes after the cluster is running.  

I tried to put a custom image but imagePullSecret is failing and not pulling image from our docker registry.

Could you please let me know how can i run this command to create indexes, using bootstrapcommand ?

i have all json files.

**Comment by Crazybus** [comment]
Could you please provide the output from `helm get elasticsearch`? Replace `elasticsearch` with whatever your helm release name is. That will make it easier for us to help you. 

Image pull secrets should be set like this: https://github.com/elastic/helm-charts/blob/8502b6f5224e51b228c13e21681770c03e337fb8/elasticsearch/tests/elasticsearch_test.py#L419-L420

**Comment by vishnugs** [comment]
sure no problem now.
