### ISSUE TITLE
Elasticsearch keystore missing values

### ISSUE THREAD

**Issue by CarlosEsco** [elastic/helm-charts#281]
**Chart version:**
7.3
**Kubernetes version:**
1.11
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
self hosted

Followed steps outlined in readme.

1.  add secret to kubernetes, and verify it kubectl get secret
2.  run helm chart to install elasticsearch with 
  keystore:
   - secretName: id
3.  exec into elasticsearch pod and run bin/elasticsearch-keystore list
    no entry for the s3.client,default.access_key

**Comment by martinkubrak** [comment]
Same problem here.

This is what I have in Helm values:

keystore:
  - secretName: es-snapshot-oss-credentials
    items:
    - key: s3.client.default.access_key
      path: s3.client.default.access_key
    - key: s3.client.default.secret_key
      path: s3.client.default.secret_key

'bin/elasticsearch-keystore list ' shows nothing.

**Comment by Crazybus** [comment]
> Chart version: 7.3

This feature is not yet released and is only in master. If you are running from master could you provide the output of `helm get elasticsearch` (replace elasticsearch with your release name). I just got back from vacation and will be doing the next release tomorrow which will include this feature.

**Comment by Crazybus** [comment]
> This feature is not yet released and is only in master

This has now been released and is available in chart version 7.3.2

**Comment by CarlosEsco** [comment]
Will look into and see if it working.  i was building from master and pushing to my own chart museum.

**Comment by CarlosEsco** [comment]
My issue is now related to #280
