### ISSUE TITLE
filebeat index not available to kibana for 1.14.3 

### ISSUE THREAD

**Issue by dwaiba** [elastic/helm-charts#282]
**Chart version:**

**Kubernetes version: 1.14.3**

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)

**Helm Version:**

**`helm get release` output**

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

```
```

**Describe the bug:**
filebeat index not available to Kibana for 1.14.3 k8s 

**Steps to reproduce:**

1. Deploy Elasticsearch, filebeafilebeat,metricbeat and kibana
2.
3.

**Expected behavior:**

**Provide logs and/or server output (if relevant):**

**Any additional context:**

**Comment by Crazybus** [comment]
> e.g. helm get elasticsearch (replace elasticsearch with the name of your helm release)

Could you please provide these details and which Kubernetes provider you are using? We have automated testing to make sure that the default configurations all work together which also tests that the filebeat indexes are created and being filled correctly.

**Comment by dwaiba** [comment]
This was working until v1.13.3 but on using metricbeat along with filebeat from v1.13.7 onwards [also tested on v1.14.3], metricbeat-* index is created in kibana automatically but not filebeat-*. Tested on gke 1.14.3 and result is the same.

**Comment by Crazybus** [comment]
> e.g. helm get elasticsearch (replace elasticsearch with the name of your helm release)

Could you please add these details so I can try to reproduce your issue? Also giving the log output from the filebeat pods will help me to figure out what might be happening.
