### ISSUE TITLE
[ElasticSearch] Service becomes unavailable on chart upgrade

### ISSUE THREAD

**Issue by haizz** [elastic/helm-charts#284]
**Chart version:**
7.3.0

**Describe the bug:**
Chart has Service selector spec bound to specific chart version:
https://github.com/elastic/helm-charts/blob/a49995539e4347e8729437cfbb54299023c81306/elasticsearch/templates/service.yaml#L18

Which means that upgrading the chart removes older pods from the service and makes the service totally unavailable.

**Comment by Crazybus** [comment]
That is a really great find! Especially since this comes from the default `helm create` template. Any idea if it is still present in the default template? If so I would expect that this would be affecting just about every helm chart created with it.

**Comment by Crazybus** [comment]
This has been fixed in #290. Thank you again for finding it!

**Comment by JoaquinScript** [comment]
This is still happening to me. I'm not sure if it is the same issue but it's the same symptom: after upgrade the pod (only one replica) never turns green and the last log its from it turning yellow from red. But if I delete the chart (and the pvc) and install again, everything works as expected.

Is there a chance I'm not using an updated chart? how can I make sure of that?

**Comment by fatmcgav** [comment]
@JoaquinScript Are you able to open a new issue and provide the details requested?

We're specifically interested in the output from `kubectl get events` and the logs from the elasticsearch pods during the upgrade process.

Cheers
