### ISSUE TITLE
[ElasticSearch][7.3.0] search_phase_execution_exception

### ISSUE THREAD

**Issue by Yitaek** [elastic/helm-charts#292]
**Chart version:** 7.3.0

**Kubernetes version:** 1.13.7-gke.24

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)

**Helm Version:** v2.14.1

**`helm get release` output** Using default settings

**Describe the bug:**

We started seeing the following errors once we transitioned from 7.2 to 7.3. It may be the underlying Docker image has changed some behavior:

```
{
   message:  "search_phase_execution_exception"    
   name:  "ResponseError"    
   stack:  "ResponseError: search_phase_execution_exception
    at IncomingMessage.response.on (/usr/src/app/node_modules/@elastic/elasticsearch/lib/Transport.js:287:25)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)"    
  }
```

We have a use case where you want to search for a bunch of items by ids. Under a certain number of ids (e.g. 24 items), the search returns fine. But for a large number of ids (e.g. 25+ items), we get that exception above. In the previous version (7.2.0), it was returning fine for a large number of items 25+ (up to around 150 items) at once. We are using the node client library.

**Comment by Crazybus** [comment]
Hi @Yitaek! This repo is for issues related to the helm chart itself while this issue looks Elasticsearch specific. Could you please open it at https://discuss.elastic.co/c/elasticsearch or in the Elasticsearch repo itself?
