### ISSUE TITLE
Need Heartbeat chart to deploy to a kubernetes cluster in ES 7.4.0

### ISSUE THREAD

**Issue by dcvtruong** [elastic/helm-charts#317]
**Chart version:**
7.4.0
**Kubernetes version:**
1.13.10
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
Kubespray
**Helm Version:**
2.14.3
**`helm get release` output**

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

```
N/A
```

**Describe the bug:**
In Kibana 7.4 dashboard the Uptime page required the user to download Heartbeat 7.4 using curl for kubernetes cluster and no available Heartbeat helm chart to deploy into Kubernetes.
**Steps to reproduce:**

1. Deploy Elasticsearch 7.4
2. Deploy Kibana 7.4.0
3. Access the Kibana Dashboard
4. Goto 'Uptime'
5. Info to run the curl command to download Heartbeat package for Linux

**Expected behavior:**
Helm Chart for Heartbeat
**Provide logs and/or server output (if relevant):**
N/A
**Any additional context:**
The heartbeat chart from stable has an older image 6.7.0

**Comment by jmlrt** [comment]
Hi @dcvtruong, 
Thank you for openning this issue.

We don't know yet when Heartbeat chart will be released. Our priority for new Chart development is currently Logstash.

I let this issue opened and will keep you informed when we'll have more details about Heartbeat chart development.

**Comment by skob** [comment]
active

**Comment by nfsouzaj** [comment]
Hello Guys, 
I am also i need of a heartbeat helm chart in order to be able to monitor my clusters within AKS.

**Comment by fabioqcorreia** [comment]
Up

**Comment by fabioqcorreia** [comment]
So I've managed to work through this extracting the old [stable/heartbeat](https://hub.helm.sh/charts/stable/heartbeat) repo using `helm pull stable/heartbeat .` then changing image version to 7.8.0. Of course this ain't the best option, but still worked for me. Some issues found while using this: secretMounts does not work and many other functions, needs to update Chart.yaml of course.

**Comment by jmlrt** [comment]
still valid

**Comment by fabioqcorreia** [comment]
Birthday cake for this issue! 🎂

**Comment by nfsouzaj** [comment]
I gave up on the idea of using elastic.

**Comment by kwsorensen** [comment]
Is Elastic open to the idea of a heartbeat Helm chart? Is it on the roadmap? As a paying elastic.co service would be valuable feature to have.

**Comment by jmlrt** [comment]
Hi, I would really like having a chart for Heartbeat, but unfortunately this is not on the roadmap for now.

**Comment by jappi00** [comment]
A Heartbeat Chart would be great :D

**Comment by kwsorensen** [comment]
Is the removal of stale mean that this is going to happen?

**Comment by ChipWolf** [comment]
> 
> 
> Is the removal of stale mean that this is going to happen?

Not necessarily, it's just a valid request with enough interest _(in my opinion)_ to remain open

**Comment by chrisjaimon2012** [comment]
is this going to happen anytime soon?
much needed

**Comment by BenB196** [comment]
Its not mentioned here, but https://github.com/elastic/synthetics being docker/container only would also be a good plus here as its part of heartbeat.

**Comment by drenze-athene** [comment]
I'm in need of this as well.

**Comment by drenze-athene** [comment]
Pinging to keep alive.

**Comment by ChipWolf** [comment]
Freshen

**Comment by duclm2609** [comment]
3 years for waiting a chart :D. I'm thinking of creating my own chart.

**Comment by jmlrt** [comment]
Hi, unfortunately, creating and maintaining an additional chart for Heartbeat is still not on the roadmap in the mid or long term. We don't have the bandwidth for that and try to focus on keep maintaining the existing ones.

Our recommendation would be to use ECK to deploy Heartbeat on K8S. You can find a short config example here: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-beat-configuration.html

Otherwise, you can create your own chart or use one other from the community if needed.
