### ISSUE TITLE
Kibana chart setting "podAntiAffinity" is useless.

### ISSUE THREAD

**Issue by nerddelphi** [elastic/helm-charts#318]
That line is useless, once deployment template doesn't read that config, causing pods be scheduled in the same nodes:

[https://github.com/elastic/helm-charts/blob/f4040f5a9df00f0de2377b592647a70aa75dd6f0/kibana/values.yaml#L76](https://github.com/elastic/helm-charts/blob/f4040f5a9df00f0de2377b592647a70aa75dd6f0/kibana/values.yaml#L76)

That setting could be copied from elasticsearch chart:

[https://github.com/elastic/helm-charts/blob/f4040f5a9df00f0de2377b592647a70aa75dd6f0/elasticsearch/templates/statefulset.yaml#L80](https://github.com/elastic/helm-charts/blob/f4040f5a9df00f0de2377b592647a70aa75dd6f0/elasticsearch/templates/statefulset.yaml#L80)

**Comment by jmlrt** [comment]
Hi @nerddelphi, thank you for reporting this issue.

`antiAffinity` and `antiAffinityTopologyKey` are a heritage from Elasticsearch chart but aren't used for Kibana chart as Kibana clustering is currently not supported.

I created #326 to remove these keys.
