### ISSUE TITLE
Kibana chart setting "maxUnavailable" is useless.

### ISSUE THREAD

**Issue by nerddelphi** [elastic/helm-charts#331]
That line is useless, once templates doesn't read that config.

[https://github.com/elastic/helm-charts/blob/master/kibana/values.yaml#L79](https://github.com/elastic/helm-charts/blob/master/kibana/values.yaml#L79)

**Comment by jmlrt** [comment]
Hi @nerddelphi,
Thank you for reporting this. This value is used in Elasticsearch chart but not in Kibana chart.
We'll fix it soon.

**Comment by jmlrt** [comment]
fixed by #422
