### ISSUE TITLE
pod has unbound immediate PersistentVolumeClaims 

### ISSUE THREAD

**Issue by CodeShareDude** [elastic/helm-charts#332]
**Chart version:** elastic/elasticsearch 7.4.0

**Kubernetes version:** 13.3

**Kubernetes provider:** None

**Helm Version:** v2.12.2

I'm trying to run the basic commands to deploy elasticsearch pods on my Kubernetes cluster:
1. helm repo add elastic https://helm.elastic.co
2. helm install --name elasticsearch elastic/elasticsearch

**Describe the bug:** When I run the above, the pods remain in a pending state. When I inspect, I see a FailedScheduling error, with a message stating that "pod has unbound immediate PersistentVolumeClaims (repeated 5 times)"

**Steps to reproduce:**

1. helm repo add elastic https://helm.elastic.co
2. helm install --name elasticsearch elastic/elasticsearch

**Expected behavior:** Expecting the pods to be in a ready state

**Any additional context:** As a way to address the issue, I created a 2Gi PersistentVolume, I curled the values.yaml at the root of the git repo, changed line 87's storage request from 30Gi to 1Gi, and re-deployed using my customized values.yaml. But this did not fix the issue.

**Comment by holms** [comment]
@CodeShareDude I've got exactly the same problem just now. I don't know what is going on but after setting it as `2G`, it started to work! While using `2Gi` it doesn't! Meanwhile got further problems with permission on PVC after that :(

**Comment by fatmcgav** [comment]
@CodeShareDude Is this still an issue for you?

Are you able to confirm if your cluster has a `default` storage class?
As this error is indicative of there not being a configured storage class for the requested persistent volumes. 

Could you post the output of the following commands:
- `kubectl describe storageclasses`
- `kubectl describe pvc`

**Comment by CodeShareDude** [comment]
Hi folks,

I was able to resolve this issue by creating Persistent Volumes and Persistent Volume Claims with the appropriate name(s) that the Elastic pods were looking for. This was after considerable trial and error.

The format of the PVC names was data-<release name>-elasticsearch-<master/data>-<0/1/2/3/...>. Example: data-my-release-elasticsearch-data-0

**Comment by fatmcgav** [comment]
@CodeShareDude cheers for the update.

Would you be able to post the output of the above commands so that we can see if there is anything we can do to improve the experience of using these helm charts?

**Comment by CodeShareDude** [comment]
[root@jimbo ~]# kubectl get storageclasses --all-namespaces
No resources found

[root@jimbo ~]# kubectl describe pvc
Name:          data-elk-release-elasticsearch-data-0
Namespace:     default
StorageClass:  local
Status:        Bound
Volume:        elk-data-pv
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"data-elk-release-elasticsearch-data-0","namespace":...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      3Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    elk-release-elasticsearch-data-0
Events:        <none>


Name:          data-elk-release-elasticsearch-data-1
Namespace:     default
StorageClass:  local
Status:        Bound
Volume:        elk-data-pv-1
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"data-elk-release-elasticsearch-data-1","namespace":...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      3Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    elk-release-elasticsearch-data-1
Events:        <none>


Name:          data-elk-release-elasticsearch-master-0
Namespace:     default
StorageClass:  local
Status:        Bound
Volume:        elk-master-pv
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"data-elk-release-elasticsearch-master-0","namespace...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    elk-release-elasticsearch-master-0
Events:        <none>


Name:          data-elk-release-elasticsearch-master-1
Namespace:     default
StorageClass:  local
Status:        Bound
Volume:        elk-master-pv-1
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"data-elk-release-elasticsearch-master-1","namespace...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    elk-release-elasticsearch-master-1
Events:        <none>


Name:          data-elk-release-elasticsearch-master-2
Namespace:     default
StorageClass:  local
Status:        Bound
Volume:        elk-master-pv-2
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"data-elk-release-elasticsearch-master-2","namespace...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    elk-release-elasticsearch-master-2
Events:        <none>
