### ISSUE TITLE
Add support for additional labels for service

### ISSUE THREAD

**Issue by usamaahmadkhan** [elastic/helm-charts#342]
**Describe the feature:**
Ability to add additional labels on services .

**Describe a specific use case for the feature:**
I'm using a kubernetes operator which reads labels from the service and creates ingresses on the basis of those labels. So I need to have the ability to add additional labels on the services.

**Comment by usamaahmadkhan** [comment]
@jmlrt any idea when this will be released?

**Comment by jmlrt** [comment]
This should be released for 7.4.2 or 7.5.0 in november.

Le mer. 30 oct. 2019 à 07:36, Usama Ahmad <notifications@github.com> a
écrit :
