### ISSUE TITLE
Make filebeat and metricbeat use hostnetwork for proper hostname

### ISSUE THREAD

**Issue by evannorstrand** [elastic/helm-charts#355]
As the subject states, hostnetwork is required by filebeat and metricbeat to capture the correct hostname of the files/metrics being captured.

**Comment by jmlrt** [comment]
related to #315 and #321

**Comment by mitchellmaler** [comment]
@jmlrt I can see that the filebeat chart has this option now but not metricbeat. I like to enable this on the daemonset metriicbeat but not the deployment metricbeat in the chart.

**Comment by jmlrt** [comment]
@mitchellmaler we have a pr in progress for metricbeat: #315
Don't hesitate to comment also in this PR for being able to enable `hostNetwork` only on metricbeat daemonset.

**Comment by gkcgi** [comment]
I would also like to see dnsPolicy and hostNetwork enabled for metricbeat (like filebeat).

**Comment by jmlrt** [comment]
still valid
