### ISSUE TITLE
[elasticsearch] kubernetes-kind example: missing -p in mkdir in init-container

### ISSUE THREAD

**Issue by holms** [elastic/helm-charts#362]
Sorry I'll just go without template in here. This affects everything and everywhere:

In this particular command `-p` should be added, or else once you'll redeploy your pod, init-container will fail complaning that folder already exists in your attached volume, and pod will exit immediately. 

https://github.com/elastic/helm-charts/blob/e463e7a1f4f719687e8b4294bc3223bfbd021915/elasticsearch/examples/kubernetes-kind/values.yaml#L26

**Comment by jmlrt** [comment]
Hi @holms,

Thank you for submitting this issue. Well this should only affect people using this provided example to test elasticsearch chart deploy locally using https://kind.sigs.k8s.io/.

Could you create a PR to fix it?

**Comment by holms** [comment]
Sure, will do:)

-- 
Roman Gorodeckij

**Comment by holms** [comment]
@jmlrt which is example is used for k8s specifically? If there's any other init-containers with missing -p I'd add them.

**Comment by jmlrt** [comment]
Every example are for kubernetes, however some are targetting specific k8s distrib (docker-for-mac, kubernetes-kind, minikube, openshift) while others are targetting specific scenarios (6.x, config, default, multi, oss, security, upgrade) for vanilla k8s.
