### ISSUE TITLE
Status of the logstash chart?

### ISSUE THREAD

**Issue by mcanevet** [elastic/helm-charts#370]
I was wondering which logstash chart should I use. It looks like the one in this git repo is not published on the helm.elastic.co chart repository. Does it mean that I should use the stable/logstash chart instead?

**Comment by jmlrt** [comment]
Hi @mcanevet,

Logstash Helm Chart has been merged on master a few weeks ago but has still not been released officially. It will be officially released with 7.5.0 before the end of the month and will be published on helm.elastic.co at this occasion.

Meanwhile, you can still use this chart from master branch by following [Using master branch](https://github.com/elastic/helm-charts/blob/master/logstash/README.md#using-master-branch) instructions.

As for choosing this one or stable/logstash, we currently still lack feedback for Elastic Logstash chart which is pretty new and don't recommand it for production yet so you better choose stable/logstash currently if you have production or requirements or equivalent. However if you are running it in development I encourage you to give a try to Elastic Logstash Helm Chart which will be better integrated with other Elastic Charts, actively maintained and ensure backward compatibility.

**Comment by jmlrt** [comment]
Related to https://github.com/elastic/helm-charts/pull/333#issuecomment-549334869, https://github.com/elastic/helm-charts/issues/353 and https://github.com/elastic/helm-charts/issues/365.

I'll keep this one open until official release to avoid having new duplicate issues

**Comment by jmlrt** [comment]
Logstash chart has been released on [Elastic Helm repository](https://helm.elastic.co/) with #391.
