### ISSUE TITLE
Readiness probe health check parameters are incorrect

### ISSUE THREAD

**Issue by lachlanbb** [elastic/helm-charts#374]
**Chart version:** 7.4.1

**Kubernetes version:** 1.14, GitVersion:"v1.14.6-eks-5047ed"

**Kubernetes provider:** EKS

**Helm Version:** v2.14.2

**Describe the bug:** Default clusterHealthCheckParams is not suitable for any production helm deployment.

**Steps to reproduce:**

1. Use this elasticsearch chart in the default configuration. 
```yaml
clusterHealthCheckParams: "wait_for_status=green&timeout=1s"
```
2. Perform an upgrade, indice restore or anything that causes the cluster to stop returning green status
3. Any helm operations after this will take the cluster offline, when using helm --recreate-pods this is even more immediate and it will never recover. Any failureover scenarios (e.g kube node replacements) will also immediately break the release. 

I will comment on this issue with a suitable set of replacements but a combination of liveliness & readiness with `_cluster/health?local=true&wait_for_status=[yellow,green]&timeout=1s` should do it.

I think the timeout is too low to always return but I might be wrong.

I'll look stable/elasticsearch chart as I think they mostly resolved these issues, it took a while though.

**Comment by holms** [comment]
I've increased readinessProbe timeout to 200s :D Then it worked. In managed kubernetes this is somehow an issue too.

**Comment by fatmcgav** [comment]
@lachlanbb Thank you for opening an issue, and apologies if this is causing you pain.

The params used by the `readinessProbe` Curl request is override-able by setting the `clusterHealthCheckParams` value: https://github.com/elastic/helm-charts/blob/0411010e8f03c25c06d864ce62f5b482b5439bdb/elasticsearch/values.yaml#L198

So you should be able to set this param to `wait_for_status=yellow&timeout=1s` - Note that `wait_for_status` is a singular value:
> **wait_for_status**
>(Optional, string) One of green, yellow or red. Will wait (until the timeout provided) until the status of the cluster changes to the one provided or better, i.e. green > yellow > red. By default, will not wait for any status.

Are you able to give this a try and report back?

**Comment by lachlanbb** [comment]
Thanks for the quick response, I'd tried a few different steps to get the cluster out of a red state but the only thing that reliably works is settings the probe to 'wait_for_nodes=>5&timeout=1'

N: -1 meaning up to one pod can be offline at a time (But obviously this will impact availability outside of rolling helm updates).

Could you add an option to define a liveness check and disable the readiness probe?

**Comment by lachlanbb** [comment]
wait_for_nodes will fail when the first 'local=true' check on the node happens.

> failureThreshold: When a Pod starts and the probe fails, Kubernetes will try failureThreshold times before giving up. Giving up in case of liveness probe means restarting the container. In case of readiness probe the Pod will be marked Unready. Defaults to 3. Minimum value is 1.

failureThreshold: 3 
This should be set higher on the readiness probe, I don't know why the pod is not replaced when it does not reach ready state but it might be because of PDB.

Having an option to disable the readiness probe is definitely necessary, I'm doing DR testing so will advise if I needed to customise the helm chart (I would prefer not)

**Comment by fatmcgav** [comment]
@lachlanbb I don't think disabling the readiness probe is the correct solution for this scenario. 

The fact is that we _want_ to run a readiness probe to ensure that the pod is ready to serve traffic before we add it to the service load-balancer. 

It's also worth noting that a failing readiness probe _will not_ result in the pod being restarted. It will only result in the pod being marked as `Unready` which prevents any traffic being routed to it. Kubernetes will continue running the configured readiness probe until such point that the probe succeeds or the pod is killed via another means. 
> https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes

Would it be possible for you to capture the following logs during a rolling upgrade or indices restore?
* `kubectl get events`
* `kubectl logs elasticsearch-master-0`
* `kubectl describe pod/elasticsearch-master-0`

Also, could you attach the output from `helm get <deployment name>`.

**Comment by fatmcgav** [comment]
@lachlanbb Also, I just wanted to clarify the behaviour of the `readinessProbe` in relation to:
> Perform an upgrade, indice restore or anything that causes the cluster to stop returning green status

The configured `readinessProbe` command only checks the cluster health on initial startup of the pod, to ensure that the new pod has joined the cluster successfully and the cluster has re-balanced, relocated shards etc. This is to ensure that actions like rolling restarts or upgrades don't move onto the next pod until the cluster is completely green and healthy. 

Whether this is an initial startup or later in the pod life is determined by looking for the presence of a `START_FILE` within the pod filesystem. 
Once the pod is running and the cluster health is `green`, then the readiness probe simply checks that `/` http endpoint is responding for the local node - Lines 213-215 below. 

This means that any actions to the cluster, such as restoring indices, that result in a non-green health _would not_ result in readiness probes failing for existing nodes within the cluster.

The full readiness probe is defined here: 
https://github.com/elastic/helm-charts/blob/0411010e8f03c25c06d864ce62f5b482b5439bdb/elasticsearch/templates/statefulset.yaml#L194-L225

**Comment by pradeeepst** [comment]
> @lachlanbb Thank you for opening an issue, and apologies if this is causing you pain.
> 
> The params used by the `readinessProbe` Curl request is override-able by setting the `clusterHealthCheckParams` value:
> 
> https://github.com/elastic/helm-charts/blob/0411010e8f03c25c06d864ce62f5b482b5439bdb/elasticsearch/values.yaml#L198
> 
> So you should be able to set this param to `wait_for_status=yellow&timeout=1s` - Note that `wait_for_status` is a singular value:
> 
> > **wait_for_status**
> > (Optional, string) One of green, yellow or red. Will wait (until the timeout provided) until the status of the cluster changes to the one provided or better, i.e. green > yellow > red. By default, will not wait for any status.
> 
> Are you able to give this a try and report back?
@fatmcgav tried as per suggestion  `wait_for_status=yellow&timeout=1s`, no luck. 
Tried with other combinations as mentioned in the https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html#request-params
No luck ! 
Will you able to re-open this issue and investigate further ? 
thanks

**Comment by Nimesh36** [comment]
I was having the same issue. Earlier I have set a password with a length of fewer than 20 characters. but after setting a password with 20 character length in 100s pod status is turn in ready.

**Comment by ebuildy** [comment]
Yes in general, this is really a bad practice to make the node status depending of the cluster status!

**Comment by billabongrob** [comment]
This also becomes a strange issue when trying to enable xpack tls after the fact i believe.

**Comment by n1vgabay** [comment]
Someone have a solution for this issue?
