### ISSUE TITLE
initContainer vm.max_map_count does not persist

### ISSUE THREAD

**Issue by VariableDeclared** [elastic/helm-charts#378]
**Chart version:**
Latest
**Kubernetes version:**
1.16
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
Charmed Kubernetes
**Helm Version:**
v2.15.1

**Describe the bug:**

Deployment uses elasticsearch container when deploying to Kubernetes.

**Steps to reproduce:**

1. Deploy Elasticsearch with image and imageTag values
2. Observe pod crash

**Expected behavior:**
Elasticsearch should spin without and intervention.

**Provide logs and/or server output (if relevant):**

**Any additional context:**
Opened a pull request for this: https://github.com/elastic/helm-charts/pull/377

**Comment by jmlrt** [comment]
Hi @VariableDeclared,
Can you provide more details about your issue and why the pod is craching?
Also we don't need the full elasticsearch Docker image to run `sysctl` command in init container, this is working and our automated tests are successfull with this configuration.

Posting the result of `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release) and the container logs would help us to understand your issue.

**Comment by VariableDeclared** [comment]
Hi @jmlrt, what we realised was that the base image for the elasticsearch container does not persist the vm.max_map_count value over to the next container. We tried this out with an initContainer of Ubuntu and running container of Ubuntu on another deployment it it seemed to persist.

**Comment by jmlrt** [comment]
@VariableDeclared,
I couldn't reproduce it locally. `vm.max_map_count` value, is persisted in all my tests using elasticsearch docker image as init container.

Can you provide more logs and configuration?

- `helm get <release_name>`
- `kubectl get events`
- `kubectl logs`

**Comment by VariableDeclared** [comment]
Hi @jmlrt I will try to replicate this sometime this week. Apologies for the delay on this.
