### ISSUE TITLE
[elasticsearch] version and appVersion

### ISSUE THREAD

**Issue by naseemkullah** [elastic/helm-charts#389]
It was my understanding that this repo wanted to keep chart and app versions the same, I see that is no longer the case, can you please confirm?

**Comment by jmlrt** [comment]
Hi @naseemkullah,
This is still the case we are still keeping same chart and app version in each release.
Why do you think this is not anymore the case?

**Comment by naseemkullah** [comment]
Ok good to know, I tried pinning chart version 7.4.2 and got an error, then I went and looked here:

https://github.com/elastic/helm-charts/blob/38925a0084bb5254828bb342bfb6f1142558014e/elasticsearch/Chart.yaml#L8-L9

**Comment by jmlrt** [comment]
Yeah while [releases](https://github.com/elastic/helm-charts/releases) do still have the same versions for chart and app, master branch currently deviate.

Long story short, we missed releasing 7.4.2 a few weeks ago for schedule issues, and we will release [7.5.0](https://github.com/elastic/helm-charts/pull/391) during the week. 

We updated [last week](https://github.com/elastic/helm-charts/pull/386) app version to 7.4.2 on master branch to ensure it was working well before updating to 7.5.0.

However, this is happening only on master branch, releases won't be impacted, and this should last only a few days before 7.5.0 release.

**Comment by naseemkullah** [comment]
Ok, thanks @jmlrt !
