### ISSUE TITLE
Support helm 3.x

### ISSUE THREAD

**Issue by krichter722** [elastic/helm-charts#401]
**Describe the feature:**
I'd be nice if helm 3.x would be supported. It's released and unfortunately a lot of issues with helm 2.x are only solved in 3.x.

**Describe a specific use case for the feature:**
Installation with helm 3.x because I use it/have to use it for other chart installations.

Currently the following charts are experiencing issues with helm 3.x:

* ~logstash (#398)~

**Comment by gadelkareem** [comment]
I managed to install the chart with Helm 3 by extracting the template `helm template` then adding the template to a new empty Helm 3 compatible chart. All working fine so far, only Kibana is misbehaving.

**Comment by drenze** [comment]
With the exception of needing to define a service in logstash, everything has installed fine for me as-is under Helm 3. However, it should be noted that I am installing the charts as subcharts of a Helm 3 chart, which may or may not make a difference.

**Comment by gadelkareem** [comment]
Kibana worked after reinstalling the kibana helm chart the same way with helm 3. So it is just a matter of adding the Chart.yaml file

**Comment by pbecotte** [comment]
I've been using helm 3 since the first beta (including these), and haven't yet had to modify a chart to get it to work (fingers crossed)

**Comment by desaintmartin** [comment]
FYI: https://github.com/elastic/helm-charts/pull/437 for helm 3 migration.

**Comment by krichter722** [comment]
Work is also happening in #516.

**Comment by lucaskjaero** [comment]
For people looking at this issue to evaluate whether to use this chart or the one in stable, I want to share my experience. The Elasticsearch and Kibana charts seem to work for a new installation on Helm 3 without modification. I would recommend this chart above the stable one.

**Comment by krichter722** [comment]
Still an issue

**Comment by jmlrt** [comment]
FYI, Helm 3 support has been added in beta with [7.9.0](https://github.com/elastic/helm-charts/releases/tag/7.9.0) and [6.8.12](https://github.com/elastic/helm-charts/releases/tag/6.8.12) releases => #759

**Comment by jmlrt** [comment]
Updating `rbac.authorization.k8s.io` API is required to make `helm lint --strict` work with Helm 3 => #890

**Comment by jamshid** [comment]
Hopefully coming, helm 2 is EOL. https://helm.sh/blog/helm-2-becomes-unsupported/

**Comment by jmlrt** [comment]
Current status of Helm 3 support work:

- ✅ `helm install` of all charts with default values with Helm 3 (Logstash fixed in #695 + #776 + #839)
- ✅ `helm lint --strict` for all charts (deprecated K8S API replaced in #890)
- ✅ `heritage` labels removed from K8S immutable field in #437 and #516
- ✅ K8S deprecated `Capabilities.KubeVersion.GitVersion` replaced in #516
- ✅ Doc updated with Helm 3 commands in #759 
- ✅ CI tests updates in #516 

The remaining tasks are:
- merge #516 
- upgrade tests and document breaking changes if needed

**Comment by dominik-bln** [comment]
Helm 3 made changes to how tests are cleaned up. Before it was possible to run `helm test --cleanup ..`, now the manifests seem to need an annotation `"helm.sh/hook-delete-policy": hook-succeeded` to be properly deleted (as briefly mentioned [at the bottom of the new docs](https://helm.sh/docs/topics/chart_tests/#notes)).

When running the chart with Helm 3 we are seeing the tests pile up:

<img width="261" alt="Screenshot 2020-11-18 at 10 28 04" src="https://user-images.githubusercontent.com/855119/99511811-0705a180-2989-11eb-9192-b34df2788263.png">

Would it be possible to add that annotation? Should I open a new issue or PR for this change?

**Comment by jmlrt** [comment]
@dominik-bln, Thanks for the tips, I thought that test pods where cleaned automatically with Helm 3 but it seems not. I created #911 to fix it.

**Comment by jmlrt** [comment]
Helm 3 work is done and will be part of 7.10.0 release soon.
