### ISSUE TITLE
Explain the relation to cloud-on-k8s in README

### ISSUE THREAD

**Issue by krichter722** [elastic/helm-charts#402]
**Chart version:** ./.

**Kubernetes version:** ./.

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine) ./.

**Helm Version:** ./.

**`helm get release` output**
./.

**Describe the bug:**
Both the helm-charts and the [cloud-on-k8s](https://github.com/elastic/cloud-on-k8s) project seem to provide ways to deploy an elastic-stack on Kubernetes. It'd be nice if the relationship between the two project would be added to README in the form of one sentence. Usage recommendation for novice and advanced users would be appreciated.

Since there's a lot of redundancy between the two approaches to use helm and copy-paste snippets from the quickstart guide of cloud-on-k8s it'd be nice to explain why these two approaches are maintained in a very short statement.

**Steps to reproduce:**
Read the REAMDE.

**Expected behavior:**
Being certain that I use the right project/approach to get an elastic stack running on k8s.

**Provide logs and/or server output (if relevant):**
./.

**Any additional context:**
./.

**Comment by jmlrt** [comment]
still valid

**Comment by krichter722** [comment]
still valid
