### ISSUE TITLE
[Beats] Remove hardcoded or make configurable the docker mounts

### ISSUE THREAD

**Issue by mitchellmaler** [elastic/helm-charts#404]
Not all Kubernetes clusters deploy using docker since the CRI has multiple implementations. Our situation is we deploy with containerd and not docker and the docker directories or socet do not exist. The beat helm charts have the docker directories mounted by default. 
It would be better to make a configuration to disable mounting the docker directories for clusters that are not using docker at all.

**Comment by jmlrt** [comment]
Hi @mitchellmaler,
Thanks for submitting this feature request.
I'll let the issue open but don't think we'll have time to work on it.

**Comment by jmlrt** [comment]
still valid even if we have no plan to work on it currently :(

**Comment by jmlrt** [comment]
still valid

**Comment by jmlrt** [comment]
still valid

**Comment by jmlrt** [comment]
still valid

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
This is more relevant now since Azure's Kubernetes (AKS) [switched to using ContainerD](https://github.com/Azure/AKS/releases/tag/2020-11-16) by default as of Kubernetes 1.19.

**Comment by jmlrt** [comment]
still valid

**Comment by towolf** [comment]
still valid
