### ISSUE TITLE
[Logstash] - Allow StatefulSet Container Ports to be defined in the helm chart

### ISSUE THREAD

**Issue by andyliddle** [elastic/helm-charts#416]
Currently, the stateful set only defines an HTTP port on the container.   

It would be useful to allow these port to be specified in the helm chart values.

This would allow input from beats when using the following:

logstashPipeline: 
  beats.conf: |
    input { 
      beats {
        type => beats
        port => 5044
      }
    }

**Comment by jmlrt** [comment]
Hi @andyliddle,
You should be able to use beats input by setting a service for port 5044 using https://github.com/elastic/helm-charts/blob/master/logstash/values.yaml#L188-L195.

**Comment by andyliddle** [comment]
Yeah, I saw that,  but doesn't the container also need to expose the same port for the service?

**Comment by jmlrt** [comment]
I think I had a successfull test with this configuration. Can you try like that and confirm me if it's working or not? If an additional configuration is required I'll try to submit a PR next week.

**Comment by andyliddle** [comment]
Just tested it, and your correct :-)

I just added service to the values file and workes.   Looks like i've i had the wrong idea about how services worked lol.   Will close issue.

`
service:
  annotations: {}
  type: ClusterIP
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: 5044
    - name: sthn-beats
      port: 5045
      protocal: TCP
      targetPort: 5045
`

**Comment by jmlrt** [comment]
Thanks @andyliddle, I'll try to find some time to write an example or better documentation for that
