### ISSUE TITLE
Enable security by setting [xpack.security.enabled] to [true] in the elasticsearch.yml file and restart the node.

### ISSUE THREAD

**Issue by tirelibirefe** [elastic/helm-charts#423]
**Chart version:**
7.5.1
**Kubernetes version:**
1.16
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
Bare-Metal on vSphere
**Helm Version:**
3.1

**Describe the bug:**

[exception] Security must be explicitly enabled when using a [basic] license. Enable security by setting [xpack.security.enabled] to [true] in the elasticsearch.yml file and restart the node.: Check the Elasticsearch Monitoring cluster network connection or the load level of the nodes.

**Steps to reproduce:**

1.Kibana>> Heartbeat>>Set up monitoring with Metricbeat

**Expected behavior:**
Setting up monitoring

--------------

Is there a way editing elasticsearch.yml file runing ElasticSearch in Kubernetes. Wish not have to re-install ElasticSearch because of this error.

**Comment by jmlrt** [comment]
Hi @tirelibirefe,
You can configure `elasticsearch.yml` by overriding [esConfig](https://github.com/elastic/helm-charts/blob/master/elasticsearch/values.yaml#L23) value.
