### ISSUE TITLE
/usr/share does not exist using Docker for Windows with Kubernetes

### ISSUE THREAD

**Issue by kivi** [elastic/helm-charts#427]
**Chart version:** 7.5.1

**Kubernetes version:** 1.15.5

**Kubernetes provider:** Docker Desktop on Windows 10

**Helm Version:** 3.0.2

~~**`helm get release` output**~~ (did not work for me)

**Describe the bug:** I am getting **AccessDeniedException** on `/usr/share/elasticsearch/data/nodes`. I have digged down by adding a few extraInitContainers doing `ls`. I found out that `/usr/share` does not exists, subsequently `/usr/share/elasticsearch/data/nodes` can not be created.

**Steps to reproduce:**

1. Git pull https://github.com/elastic/helm-charts.git
2. cd elasticsearch/examples/docker-for-mac
3. helm install elasticsearch elastic/elasticsearch -f ./values.yaml

**Expected behavior:** elasticsearch should run.

**Provide logs and/or server output (if relevant):**

```Java
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
{"type": "server", "timestamp": "2020-01-03T13:53:15,092Z", "level": "WARN", "component": "o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-0", "message": "uncaught exception in thread [main]",
"stacktrace": ["org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];",
```

**For debugging added extraInitContainer**
```
  - name: ls1
    image: busybox
    command: ['ls', '/usr/share']
```

Output of `kubectl logs elasticsearch-master-0 -c ls1` is:
```
ls: /usr/share: No such file or directory
```

**Comment by pbecotte** [comment]
Your debug method isn't going to work- busybox doesn't have a /usr/share folder, and you're not mounting any volumes (the containers dont share a file system). As an alternative, put that command at the beginning of the `command` in the statefulset.

As to the actual issue, I am betting the issue isn't a missing location, its a permission issue. Docker on Windows has some weirdness- it will enforce filesystem permissions... but won't let you change them. It can be very hard to run containers as a non-root user there.

If this is for dev use, I would suggest simply disabling persistence. If you really want it, the next thing I would try is removing the `storageClass` line from the VolumeClaimTemplate and see if there is a default that does a better job. Finally, I would try creating a volume out of band and setting the PVC to use it.

**Comment by kivi** [comment]
My debug method actually works, it tells me something ist not working here. If I am getting it right, you have examples with busybox and there are even going deeper than /usr/share - Or I am somehow not using the examples right? 
What I do is, clone the charts, go to that chart I would like to deploy. Cd into examples and pick one and there I helm `install -f ./values.yaml` and hoping that things work

And that's why you might be right about the problem with win-docker  (yep it is dev use, I would not use that in production, and I would certainly have found more about it on the net)

**Comment by kivi** [comment]
So I get it. persistence is not needed and if I can renounce it for my development env, I could simply install with 

`helm install elasticsearch elastic/elasticsearch --set persistence.enabled=false`

Thanks @pbecotte

**Comment by pbecotte** [comment]
You can use that as a debug method, but you have to mount a shared volume in both containers so they see the same filesystem. Glad to hear you got it working though! I've never used the docker on Windows k8s.

**Comment by kivi** [comment]
I have installed kibana and I am not so sure, if this is an win-docker (only) issue. If I describe the kibana pod I will get the following output below. And if I am understanding right, it is mounting  `/usr/share/kibana/...`

```
Name:           kibana-6fdf8f6d85-f9wxf
Namespace:      default
Priority:       0
Node:           docker-desktop/192.168.65.3
Start Time:     Wed, 08 Jan 2020 11:43:20 +0100
Labels:         app=kibana
                pod-template-hash=6fdf8f6d85
                release=kibana
Annotations:    checksum/config: 3744466a7114793210263f1e5a4268c154c6d1d50868a3bea6c091f4a3328673
Status:         Running
IP:             10.1.0.242
Controlled By:  ReplicaSet/kibana-6fdf8f6d85
Containers:
  kibana:
    Container ID:   docker://2224f766cb61611e8e0912fc91e2419382460ab7cb9751d01ed600e2100246b2
    Image:          docker.elastic.co/kibana/kibana-oss:6.7.0
    Image ID:       docker-pullable://docker.elastic.co/kibana/kibana-oss@sha256:9af7fbceb7c9a746df1f7dc79d2b3bb320f0fddf9b06a3cc12fd8f903902e731
    Port:           5601/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 08 Jan 2020 11:46:21 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /usr/share/kibana/config/kibana.yml from kibana (rw,path="kibana.yml")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-sk284 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kibana:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kibana
    Optional:  false
  default-token-sk284:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-sk284
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age    From                     Message
  ----    ------     ----   ----                     -------
  Normal  Scheduled  9m56s  default-scheduler        Successfully assigned default/kibana-6fdf8f6d85-f9wxf to docker-desktop
  Normal  Pulling    9m55s  kubelet, docker-desktop  Pulling image "docker.elastic.co/kibana/kibana-oss:6.7.0"
  Normal  Pulled     6m56s  kubelet, docker-desktop  Successfully pulled image "docker.elastic.co/kibana/kibana-oss:6.7.0"
  Normal  Created    6m55s  kubelet, docker-desktop  Created container kibana
  Normal  Started    6m55s  kubelet, docker-desktop  Started container kibana
```

**Comment by pbecotte** [comment]
The way these charts are setup, they use volume mounts for configuration. They set up a ConfigMap and then mount that at /usr/share/<APP>/config/, and then configure the app to read the yaml files from that location. All of these helm charts work that way.

In addition, the Elasticsearch chart uses a StatefulSet to persist the elasticsearch data. That involves requisitioning a persistent volume, and mounting it at /usr/share/elasticsearch/data/. The error message you described is elasticsarch not being able to create new folders inside that persistent volume. My best guess as to the actual cause is windows filesystem permissions. This is because the default persistent volume on windows is a hostpath volume. The Elasticsearch container is set up to run as user 1000 (not root), however, kubernetes can not change the ownership of that volume to allow user 1000 read/write permissions. No longer having a windows based docker setup, I can't experiment, but I am betting that changing the security posture to run as root would also fix this issue.

Your busybox container was running in parallel to the elasticsearch container- not on the same filesystem. So that container was looking at a DIFFERENT /usr than your elasticsearch container was. In order to use that container to check the filesystem, you would have to mount the same volume into the busybox container as you did into the elasticsearch container. This would do it-

```
  - name: ls1
    image: busybox
    command: ['ls', '/usr/share']
    volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-master
```
