### ISSUE TITLE
Allow configuration of Java options for metricbeat and filebeat

### ISSUE THREAD

**Issue by krichter722** [elastic/helm-charts#431]
**Describe the feature:**
Allow configuration of Java options of metricbeat and filebeat chart analogous to logstash and elasticsearch

**Describe a specific use case for the feature:**
Reduce memory usage of pods. Resource limits don't work alone for JVM.

**Comment by jmlrt** [comment]
Hi @krichter722,
[Beats](https://github.com/elastic/beats) applications are developped in [Go](https://golang.org/) and don't use Java or JVM. That's why this option doen't exist for these charts.
