### ISSUE TITLE
Ingress support in Logstash

### ISSUE THREAD

**Issue by jnbelo** [elastic/helm-charts#453]
The current Logstash helm chart lacks ingress support. I did find, in [a commit](https://github.com/elastic/helm-charts/commit/1768d4b24c4130566ff47017013bbb7ff8d1fde2) that it was initially added but removed soon after.

It states:

> Logstash HTTP API shouldn't be exposed externally as Logstash doesn't manage any authentication on this API.
> Also as Logstash doesn't support clustering, being able to access this API via a service doesn't make sense.

As far as I saw, the HTTP plugin does support some level of authentication and I really can't see how the lack of clustering support influences this decision. Do these conditions still hold?

**Comment by KristapsT** [comment]
Found lacking this same support in the Logstash helm chart.

HTTP Plugin supports HTTP basic authentication, so it shouldn't be an issue to secure it.
Moreover, whoever would wish to have more than HTTP basic auth can ensure that in ingress itself - depending on choice of ingress provider and its integrations, such as client SSL verification, OAuth, etc. - I don't see a reason why helm chart wouldn't give an option to enable HTTP input + add ingress.

**Comment by jmlrt** [comment]
Hi @jnbelo @KristapsT, thanks for reporting this issue. The mentionned commit was about not exposing Logstash API externally. We didn't add the feature to attach an ingress for HTTP plugin yet but may do it later.

**Comment by drenze** [comment]
Is there a workaround for this? I absolutely need to expose Logstash internally within my company. We use certificate authentication and TLS encryption, so I'm not currently concerned about the authentication piece of this.

Looking at the Logstash configuration and the Kubernetes configuration generated by Helm, I can't even determine where this could possibly be modified.

**Comment by camerondavison** [comment]
Is this a good place holder issue for the support coming later? I have been watching it to see when it comes

**Comment by jmlrt** [comment]
> Is this a good place holder issue for the support coming later? I have been watching it to see when it comes

Yes it is, despite we don't plan to work on it in short/mid-term unless someone submit a PR.

**Comment by baniga** [comment]
Is there any workaround for this? I do need to expose our Logstash API via an internal load balancer.

**Comment by jnbelo** [comment]
Since this seems to be something some people require, I decided to submit a PR. (Sorry for taking months to actually do it, but at the time, I ended up not requiring this feature in my project)
