### ISSUE TITLE
Not Seeing Statefulset for data pods and deployment for client pods under template

### ISSUE THREAD

**Issue by sachinmsft** [elastic/helm-charts#465]
As i understood in full ES cluster there are 3 master, 2 data and 2 client pods. Though In the elasticsearch helm chart I am seeing that it has only 3 pods with all the three roles. What is the procedure to install the full ES cluster using elasticsearch helm chart. ? I don't see data statefulset and client deployment under the template.

**Comment by jmlrt** [comment]
Hi @sachinmsft,

Our recommended way is to deploy the chart several times with different values for the different roles you need. You can find an example [here](https://github.com/elastic/helm-charts/tree/master/elasticsearch/examples/multi).

**Comment by sachinmsft** [comment]
So we will have multiple helm release in the end one for each role right ?
and I don't see values for client role in the example. Its only for master and data roles.

**Comment by jmlrt** [comment]
>So we will have multiple helm release in the end one for each role right ?

Yes, that's it

>and I don't see values for client role in the example. Its only for master and data roles.

While the example provide config for master and data roles, if you want an additionnal role, you just need to create a new release in the same way while providing specific values for the new role matching the configuration documented for this role.

**Comment by sachinmsft** [comment]
thanks.

**Comment by junneyang** [comment]
@sachinmsft 
would you please give some client/coordinate role examples, thanks ~~

**Comment by sachinmsft** [comment]
I have not tried that yet. May be @jmlrt can provide the same.

**Comment by jmlrt** [comment]
Well what we call a client node is usually which is neither master node, neither data node, neither ingest node.

If want to add client nodes in the [multi role example](https://github.com/elastic/helm-charts/tree/master/elasticsearch/examples/multi), we would need to add a `client.yml` value file with the following values and deploy it as a new chart release in the same namespace as chart releases for other nodes:

```
# client.yml
clusterName: "multi"
nodeGroup: "client"

roles:
  master: "false"
  ingest: "false"
  data: "false"
```
