### ISSUE TITLE
Seperate resrouces for metricbeat daemonset and deployment

### ISSUE THREAD

**Issue by mitchellmaler** [elastic/helm-charts#467]
**Describe the feature:**
Add separate resources variables for the daemonset and the deployment instead of using the same one.

**Describe a specific use case for the feature:**
Each type of deployment of metricbeat might need different resources where they both do different things in terms of metric collection. Seperating the values could allow someone to add more resources for the deployment but less in the deamonset pods.

**Comment by jmlrt** [comment]
Hi @mitchellmaler, we have #448 open for that

**Comment by jmlrt** [comment]
There is also #446 issue so I'll close this one as duplicate and the progress will be tracked on #446 and #448.
