### ISSUE TITLE
[logstash] Ability to change the livenessProbe and readinessProbe

### ISSUE THREAD

**Issue by moosecanswim** [elastic/helm-charts#468]
**Describe the feature:**

The httpGet fails for both the liveness and readinessProbes in our openshift v3.11 k8 v1.11 cluster
`Readiness probe failed: Get http://10.129.8.156:9600/: dial tcp 10.129.8.156:9600: connect: connection refused`

Solution:

Change the logstash stateful set to allow the user to add their own probes other than httpGet.

Statefulset change:
```
        {{- if .Values.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        {{- end }}
```

values.yaml change:
```
# By default there will not be a livelenessProbe. You may uncomment this or use another probe.
livenessProbe: {}
  # httpGet:
  #   path: /
  #   port: http
  # initialDelaySeconds: 300
  # periodSeconds: 10
  # timeoutSeconds: 5
  # failureThreshold: 3
  # successThreshold: 1

# By default there will not be a readinessProbe. You may uncomment this or use another probe.
readinessProbe: {}
  # httpGet:
  #   path: /
  #   port: http
  # initialDelaySeconds: 60
  # periodSeconds: 10
  # timeoutSeconds: 5
  # failureThreshold: 3
  # successThreshold: 3
```

**Describe a specific use case for the feature:**

As the chart/value file are currently written you can specify only `httpGet`s.  If an exec is probe is added in a custom values file and applied to the install helm combines them instead of replacing them resulting in a failed deployment. 

the way they are written you cannot replace them with
```
readinessProbe:
  exec:
    command:
      - curl
      - localhost:9600
```
because when helm appends out custom-values.yaml on top of the built in values.yaml results in:
```
readinessProbe:
  exec:
    command:
      - curl
      - localhost:9600
  httpGet:
    path: /
    port: http
```

**Comment by moosecanswim** [comment]
https://github.com/elastic/helm-charts/pull/469

**Comment by GreenKnight15** [comment]
Bump +1

**Comment by sebastien-prudhomme** [comment]
Same problem here.

I can't even see how the  chart can run with the current probes as by default Logstash is listening on 127.0.0.1 for the API.

My fix for now is to listen on 0.0.0.0 (be aware of security risks that it might imply):

```
logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
```

**Comment by jmlrt** [comment]
Hi,
Indeed having `http.host: 0.0.0.0` is mandatory for livenessProbe and readinessProbe.

This is the default config in Logstash Docker images (see [`logstash.yml`](https://github.com/elastic/logstash/blob/master/docker/data/logstash/config/logstash-full.yml)) which is used with chart default values ([`logstashConfig: {}`](https://github.com/elastic/helm-charts/blob/master/logstash/values.yaml#L6)).

However when you override `logstashConfig`, this replace Docker image default config so you need to re-include `http.host: 0.0.0.0`).

We will see how we can improve that so you don't need to add explicitely `http.host: 0.0.0.0` when overriding config or at least document it.

In the mean time we will investigate why probes can't be overrided if you want to change them but the default values should still include these probes.

**Comment by jmlrt** [comment]
As mentionned in my previous comment `http.host: 0.0.0.0` is the default values in Logstash Docker images and is mandatory for default probes, if you add some custom `logstashConfig` you should always include `http.host: 0.0.0.0` to use default probes.

If you need to use `http.host: 127.0.0.1` which is not compatible with default probes, you can disable or override probes using one of the following yaml syntaxes:

```yaml
# disable livenessProbe
livenessProbe: null

# replace httpGet default readinessProbe by some exec probe
readinessProbe:
  httpGet: null
  exec:
    command:
      - curl
      - localhost:9600
```

We will update Logstash `README.md` to document it soon.

**Comment by jmlrt** [comment]
Can we close this issue or do you have any questions?
