### ISSUE TITLE
please point or document how to get the free version / open source x-pack license

### ISSUE THREAD

**Issue by innovia** [elastic/helm-charts#47]
Hi

I'm unable to find a way to get the free / open source  x-pack license

can you please guide how to?

**Comment by Crazybus** [comment]
Hi Ami!

The default installation will give you a [basic license](https://www.elastic.co/subscriptions) already enabled. So to use the basic features there is no need to install a license. 

You can test by running `curl localhost:9200/_xpack/license` inside one of the containers. 

```
$ curl localhost:9200/_xpack/license
{
  "license" : {
    "status" : "active",
    "uid" : "cb4accde-900e-491d-9d1d-9d9e084fcac0",
    "type" : "basic",
    "issue_date" : "2019-01-29T15:25:11.191Z",
    "issue_date_in_millis" : 1548775511191,
    "max_nodes" : 1000,
    "issued_to" : "elasticsearch",
    "issuer" : "elasticsearch",
    "start_date_in_millis" : -1
  }
}
```

**Comment by innovia** [comment]
Thanks - it wasn't clear from the docs right after generating the certs 
https://github.com/elastic/helm-charts/tree/master/elasticsearch#security

I suggest adding that note there will be helpful

**Comment by innovia** [comment]
Actually, I'm re-opening this issue as I still get crashes when i attempt to install the security option as  documented on kubernetes

**Comment by Crazybus** [comment]
> Thanks - it wasn't clear from the docs right after generating the certs
https://github.com/elastic/helm-charts/tree/master/elasticsearch#security

Ahh it wasn't clear from your original comment that you were trying to follow the security example. The security feature is not available with the basic license and requires [gold or platinum](https://www.elastic.co/subscriptions). 

If you want to start a trial of these features you can enable them for 30 days by using the [start trial API](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/start-trial.html).

> do i need to helm install without xpack - get the license, remove the helm installtion and recreate with the given license?

If you do have the right license level it is possible to just install it in one go. This is actually done as one of [automated tests](https://github.com/elastic/helm-charts/tree/master/elasticsearch/examples/security).

**Comment by hoffoo** [comment]
hi @Crazybus 

I am also confused about the security example. This page https://www.elastic.co/subscriptions#request-info suggests that File and native authentication is available under the Basic free license. 

Can you please elaborate? The Readme isn't very clear and seems to imply basic auth just works

**Comment by Crazybus** [comment]
Hi @hoffoo,

When I wrote the above comment that was not yet the case. Those security features were only moved to the basic license recently: https://www.elastic.co/blog/security-for-elasticsearch-is-now-free
