### ISSUE TITLE
Helm chart not in elastic helm repo for apm-server

### ISSUE THREAD

**Issue by pjaak** [elastic/helm-charts#470]
Hi,

I am trying to deploy apm-server from elastic/apm-server, however i keep getting the error:

Error: failed to download "elastic/apm-server" (hint: running `helm repo update` may help)

I check the https://helm.elastic.co/ and i can't find the chart here either?

Thanks

**Comment by jmlrt** [comment]
Hi @pjaak, APM Server chart isn't available on repo yet. It wil be released to this repo with next release. Meanwhile you can deploy it using [master branch procedure](https://github.com/elastic/helm-charts/blob/master/apm-server/README.md#using-master-branch).

**Comment by jmlrt** [comment]
@pjaak APM chart has been released with 7.6.0 yesterday. you can now find it in Elastic chart repo and [Helm Hub](https://hub.helm.sh/charts/elastic/apm-server).
