### ISSUE TITLE
hot-reload of pipeline configs without restarting logstash pods

### ISSUE THREAD

**Issue by morganchristiansson** [elastic/helm-charts#474]
**Describe the feature:**

https://www.elastic.co/guide/en/logstash/current/reloading-config.html

**Describe a specific use case for the feature:**

Starting logstash can be slow. Hot-reloading config files should help when updating logstash pipelines via helm values.

Seems to me it's just a matter of adding `--config.reload.automatic` and removing/disabling this code in logstash/templates/statefulset.yaml

```
{{/* This forces a restart if the configmap has changed */}}
{{- if .Values.logstashConfig }}
configchecksum: {{ include (print .Template.BasePath "/configmap-config.yaml") . | sha256sum | trunc 63 }}
{{- end }}
{{/* This forces a restart if the configmap has changed */}}
{{- if .Values.logstashPipeline }}
pipelinechecksum: {{ include (print .Template.BasePath "/configmap-pipeline.yaml") . | sha256sum | trunc 63 }}
{{- end }}
```

Or is restart preferred for any reason?

**Comment by drenze** [comment]
Kubernetes won't reload changed configmaps. The only way to force the reload is by including the config checksum, which forces the pod to reload.

**Comment by morganchristiansson** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically

**Comment by morganchristiansson** [comment]
Also need --config.reload.automatic per https://www.elastic.co/guide/en/logstash/current/reloading-config.html

**Comment by jmlrt** [comment]
This is still relevant

**Comment by jmlrt** [comment]
still valid

**Comment by jmlrt** [comment]
still valid

**Comment by liabio** [comment]
still valid

**Comment by liladler** [comment]
Since secrets are automatically reloaded without restarting the pods, what worked for me is to configure Logstash with a `stringData` Secret while setting `config.reload.automatic: true` in `logstash.yml`

**Comment by chas0amx** [comment]
@liladler 
In chart we have `ConfigMap`, not `Secret`. Is it possible to configure with `Secret`?
![Selection_233](https://user-images.githubusercontent.com/53621461/110431494-8cd36700-80b6-11eb-8609-d87a8e6332f3.png)

**Comment by jmlrt** [comment]
still valid

**Comment by jmlrt** [comment]
still valid

**Comment by cchriso** [comment]
still valid
