### ISSUE TITLE
open to including `namespace` in the charts?

### ISSUE THREAD

**Issue by natebrennand** [elastic/helm-charts#480]
**Describe the feature:**

For many workflows with helm, it can be convenient to embed `namespace` in the materialized k8s manifest files. The helm community / maintainers seem to be relatively split (https://github.com/helm/helm/issues/5465) on this topic.

Would the maintainers be open to making embedding the namespace optional?

Added blocks would look something like this to ensure backwards compatibility:
```yaml
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
```
(could also make the `Release.namespace` value an option)

**Describe a specific use case for the feature:**

We materialize our k8s manifests in source control and would like to embed the `namespace` value in them.

-----

If y'all are open to this, I would be happy to craft a PR adding them.

**Comment by jmlrt** [comment]
Hi @natebrennand,
Thanks for opening this issue.

There are mixed opinions about that topic. I'm more in favor of not including `namespace` options in charts and let the namespace control to the command which will run the chart install.

We may eventually revisit it later if some related best practice is adopted by Helm community.

**Comment by jmlrt** [comment]
Closing it as we got no feedback about not adding namespace to charts.
