### ISSUE TITLE
[apm-server] Unused "fullnameOverride" parameter

### ISSUE THREAD

**Issue by kawat55** [elastic/helm-charts#481]
**Chart version:** 7.6.0

**Kubernetes version:** 1.14.9

**Kubernetes provider:** EKS

**Helm Version:** 2.14.3

**Describe the bug:**

In apm-server helm chart, "fullnameOverride" doesn't work.
This parameter doesn't seem to be used.
In other helm chart, "fullnameOverride" works.

Got the following deployment name: "apm-server-apm-server"

**Steps to reproduce:**

helm install elastic/apm-server --name apm-server --set fullnameOverride="apm-server"

**Expected behavior:**

Deployment name should be "apm-server"

**Comment by ralavay** [comment]
This is because there is no definition of `fullnameOverride` in `_helpers.tpl`. Only have to update that block.

```{{- define "apm.fullname" }}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-"}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
```

**Comment by jmlrt** [comment]
Hi @kawat55 @ralavay ,
Thanks for reporting this issue.
Do you think you could provide a PR to fix it?

**Comment by kawat55** [comment]
Added a PR #508.
