### ISSUE TITLE
Filebeat DaemonSet renders extraInitContainers with toYaml not tpl

### ISSUE THREAD

**Issue by jarpy** [elastic/helm-charts#490]
**Chart version:**
7.6.0

**Kubernetes version:**
```
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.33", GitCommit:"2c6d0ee462cee7609113bf9e175c107599d5213f", GitTreeState:"clean", BuildDate:"2020-01-15T17:47:46Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Kubernetes provider:**
GKE

**Helm Version:**
```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

**Describe the bug:**
All other resources that accept `extraInitContainers` take a string and use the `tpl` function to render it. The Filebeat DaemonSet, however, renders the input with `toYaml`, which results in behaviour that is inconsistent.

https://github.com/elastic/helm-charts/search?q=.values.extrainitcontainers&unscoped_q=.values.extrainitcontainers

**Comment by GreenKnight15** [comment]
Bump +1
