### ISSUE TITLE
Enabling HPA in apm-server chart fails

### ISSUE THREAD

**Issue by kmattiasek1** [elastic/helm-charts#491]
**Chart version:**
7.6.0

**Kubernetes version:**
1.14

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
AWS

**Helm Version:**
3.0.3

**Describe the bug:**
hpa.yaml template seems to have a typo.. using ingress apiversion

**Steps to reproduce:**
helm install --set autoscaling.enabled=true  apm-server elastic/apm-server

**Expected behavior:**
```
NAME: apm-server
LAST DEPLOYED: Wed Feb 19 15:14:46 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Watch all containers come up.
  $ kubectl get pods --namespace=default -l app=as-apm-server -w
```

**Provide logs and/or server output (if relevant):**

```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "HorizontalPodAutoscaler" in version "networking.k8s.io/v1beta1"
```
**Any additional context:**

**Comment by jmlrt** [comment]
Hi @kmattiasek1 ,
Thank you for reporting this issue.
We don't support Helm 3 currently. Can you reproduce it with Helm 2?

**Comment by kmattiasek1** [comment]
Hi @jmlrt!
I just reproduced this with helm version 2.14.3, running
`helm install --set autoscaling.enabled=true --name apm-server elastic/apm-server`
Still the outcome is the same.
