### ISSUE TITLE
[filebeat] Optional service and containerPorts

### ISSUE THREAD

**Issue by iridian-ks** [elastic/helm-charts#511]
**Describe the feature:**

By default, the current chart would remain as-is.

Optionally, if a user wants to expose arbitrary ports then the user could do this through a `extraPorts` features that defaults to an empty array.

**Describe a specific use case for the feature:**

Filebeat supports TCP/UDP/Syslog. https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html#filebeat-input-types

These are not usable by the chart because the ports can't be exposed.

**Comment by jmlrt** [comment]
Hi @iridian-ks, Thanks for submitting this feature request.
Do you think you could add a PR for it?

**Comment by iridian-ks** [comment]
Sure, been busy but can circle back in a couple weeks.

**Comment by jmlrt** [comment]
still make sense to do it

**Comment by jmlrt** [comment]
👍

**Comment by pheever** [comment]
This feature also makes sense when deploying metricbeat to collect filebeat stats. The http port is not enabled and metricbeat fails to connect to it. The alternative to collecting filebeat stats is to have metricbeat as a sidecar, which is cumbersome.

**Comment by jmlrt** [comment]
still valid

**Comment by jmlrt** [comment]
still valid

**Comment by poochwashere** [comment]
Is there a way to to expose a port to allow syslog traffic from external devices?

**Comment by v8v5v** [comment]
could this issue be re-opened?
It seems to be still valid...

**Comment by cchriso** [comment]
still valid, I want to expose a service port for external use
