### ISSUE TITLE
Helm chart version and docker image tag mismatch for 6.6.0

### ISSUE THREAD

**Issue by sektoid0** [elastic/helm-charts#55]
Seems the Docker imageTag is set to "6.6.0" in the '6.6.0-alpha1' helm chart.

Is the '6.6.0-alpha1' chart a stable '6.6.0' application release?

**Comment by Crazybus** [comment]
Hey @sektoid0,

Correct. The chart itself is in alpha so the chart version is 6.6.0-alpha1 which uses by default the stable 6.6.0 Elasticsearch docker image. Once the charts have left alpha status we will be removing the alpha tag.

Sorry for the confusion, versioning is really hard and for this setup this appears to be the least confusing option. I went into more detail about why we use this versioning setup in a recent PR comment: https://github.com/elastic/helm-charts/pull/40#discussion_r249422024

**Comment by Crazybus** [comment]
I'm going to close this one. Feel free to reopen this issue if you have any more questions.
