### ISSUE TITLE
elasticsearch should support hostNetwork mode

### ISSUE THREAD

**Issue by junneyang** [elastic/helm-charts#552]
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet

**Comment by jmlrt** [comment]
Hi @junneyang,
Can you provide more details about your use case and why do you need hostNetwork for Elasticsearch?

**Comment by junneyang** [comment]
@jmlrt 
Compared with the virtual network, the mode of hostnetwork has much better performance 



> Hi @junneyang,
> Can you provide more details about your use case and why do you need hostNetwork for Elasticsearch?
