### ISSUE TITLE
[ES] - service & ingress are created for data node instalation

### ISSUE THREAD

**Issue by smahalingam** [elastic/helm-charts#554]
I tried to create dedicated node ES cluster as mentioned in https://github.com/elastic/helm-charts/tree/master/elasticsearch#multi It creates ingress and service for data node installing. But they are not used anywhere. Can i raise PR to create those services & ingress only for master nodes.

**Comment by jmlrt** [comment]
Hi @smahalingam,
Services are mandatory for Elasticsearch cluster to work. 
As for the ingress, they are only created if you set `ingress.enabled` to true so they shouldn't be created with default config from [multi example](https://github.com/elastic/helm-charts/tree/master/elasticsearch#multi).

**Comment by smahalingam** [comment]
Got it Thanks @jmlrt

**Comment by jmlrt** [comment]
I'm closing the issue, don't hesitate to reopen it if you have any question.
