### ISSUE TITLE
Make Kibana chart able to acept extraVolumes and extraVolumeMounts

### ISSUE THREAD

**Issue by nerddelphi** [elastic/helm-charts#557]
Hi there.
It'd be great if **Kibana** chart provide [extraVolume](https://github.com/elastic/helm-charts/blob/master/elasticsearch/templates/statefulset.yaml#L130) and [extraVolumeMounts](https://github.com/elastic/helm-charts/blob/master/elasticsearch/templates/statefulset.yaml#L292), like [elasticsearch](https://github.com/elastic/helm-charts/tree/master/elasticsearch) does.

It's very simple and easy and works like a charm with **extraInitContainer** setting.
Thanks.

**Comment by nerddelphi** [comment]
any update?

**Comment by ados1991** [comment]
i agree with @nerddelphi, also any update ?

**Comment by jmlrt** [comment]
Hi @nerddelphi & @ados1991,
Sorry for the late answer.
I don't see a good use case needed mounting additional volumes for Kibana.
Could you give more details why this is needed?

**Comment by predogma** [comment]
We have another customer requesting this.  They basically wanted "...to mount the volume where ES generated certificates for secured ES to Kibana communication."

**Comment by Angelin01** [comment]
> Hi @nerddelphi & @ados1991,
> Sorry for the late answer.
> I don't see a good use case needed mounting additional volumes for Kibana.
> Could you give more details why this is needed?

I am not one of the original posters, however I believe I have a very simple use case: I want to add a sidecar to Kibana, which is already possible through `extraContainers`. Said sidecar might need a volume for whatever reason.

**Comment by Angelin01** [comment]
@jmlrt 
>Hi @nerddelphi & @ados1991,
Sorry for the late answer.
I don't see a good use case needed mounting additional volumes for Kibana.
Could you give more details why this is needed?

I am not one of the original posters, however I believe I have a very simple use case: I want to add a sidecar to Kibana, which is already possible through `extraContainers`. Said sidecar might need a volume for whatever reason.

**Comment by jmlrt** [comment]
Fixed by #557
