### ISSUE TITLE
Metricbeat improvements

### ISSUE THREAD

**Issue by mdelapenya** [elastic/helm-charts#559]
After testing the Helm chart for metricbeat in cooperation with the Integrations team (thank you @ChrsMark), we detected the following list of items to be updated in the chart:

- [ ] Remove `in_cluster` from add_kubernetes_metadata (partially removed [here](https://github.com/elastic/helm-charts/pull/403)): 
  - Value: https://github.com/elastic/helm-charts/blob/a03b78e40d5f4c4b71a1e4e9ca08ffd9191bb700/metricbeat/values.yaml#L25
  - Examples: https://github.com/elastic/helm-charts/blob/a03b78e40d5f4c4b71a1e4e9ca08ffd9191bb700/metricbeat/examples/security/values.yaml#L22
- [x] `livenessProbe`: https://github.com/elastic/helm-charts/blob/a03b78e40d5f4c4b71a1e4e9ca08ffd9191bb700/metricbeat/values.yaml#L118 Check that the internal metrics endpoint (`127.0.0.1:5066`) is available. The [official docs](https://www.elastic.co/guide/en/beats/metricbeat/current/http-endpoint.html) says it's disabled by default for security reasons.
- [ ] `clusterRoleRules`: Rules are not in sync (i.e. statefulsets are missing, nodes/stats only accepts get as verb)
  - Helm chart: https://github.com/elastic/helm-charts/blob/a03b78e40d5f4c4b71a1e4e9ca08ffd9191bb700/metricbeat/values.yaml#L143-L159 
- Metricbeat reference: https://github.com/elastic/beats/blob/7.6/deploy/kubernetes/metricbeat-kubernetes.yaml#L320-L348

It's important to notice that also the Kubernetes operator has examples with different configurations

cc/ @jmlrt

**Comment by jmlrt** [comment]
>- [ ] `livenessProbe`: https://github.com/elastic/helm-charts/blob/a03b78e40d5f4c4b71a1e4e9ca08ffd9191bb700/metricbeat/values.yaml#L118 Check that the internal metrics endpoint (`127.0.0.1:5066`) is available. The [official docs](https://www.elastic.co/guide/en/beats/metricbeat/current/http-endpoint.html) says it's disabled by default for security reasons.

@mdelapenya HTTP endpoint is configured here: https://github.com/elastic/helm-charts/blob/master/metricbeat/templates/daemonset.yaml#L101

Can you confirm that's OK?

**Comment by mdelapenya** [comment]
Yeah, I'd say that that configuration enables the endpoint in that specific port.

Thanks!
