### ISSUE TITLE
[Kibana] Plugins take 15-30 minutes to optimize plugins

### ISSUE THREAD

**Issue by maynardflies** [elastic/helm-charts#563]
**Chart version:**
7.6.2

**Kubernetes version:**
1.18

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
On-Prem

**Helm Version:**
3

**`helm get release` output**
NAME: kibana-helm
LAST DEPLOYED: Sun Apr  5 17:37:28 2020
NAMESPACE: default
STATUS: failed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
elasticsearchHosts: http://xxxxx-client:9200
extraEnvs:
- name: SERVER_NAME
  value: kibana.xxxxxx.ca
- name: XPACK_SECURITY_ENABLED
  value: "false"
- name: NODE_OPTIONS
  value: --max-old-space-size=3097
kibanaConfig:
  kibana.yml: |
    server.name: kibana.xxxxxx.ca
    xpack.monitoring.ui.container.elasticsearch.enabled: false
    xpack.security.enabled: false
replicas: 3
resources:
  limits:
    cpu: 1000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 4Gi

COMPUTED VALUES:
affinity: {}
elasticsearchHosts: http://xxxxx-client:9200
elasticsearchURL: ""
extraContainers: ""
extraEnvs:
- name: SERVER_NAME
  value: kibana.xxxxxx.ca
- name: XPACK_SECURITY_ENABLED
  value: "false"
- name: NODE_OPTIONS
  value: --max-old-space-size=3097
extraInitContainers: ""
fullnameOverride: ""
healthCheckPath: /app/kibana
httpPort: 5601
image: docker.elastic.co/kibana/kibana
imagePullPolicy: IfNotPresent
imagePullSecrets: []
imageTag: 7.6.2
ingress:
  annotations: {}
  enabled: false
  hosts:
  - chart-example.local
  path: /
  tls: []
kibanaConfig:
  kibana.yml: |
    server.name: kibana.sparkits.ca
    xpack.monitoring.ui.container.elasticsearch.enabled: false
    xpack.security.enabled: false
labels: {}
lifecycle: {}
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext:
  fsGroup: 1000
priorityClassName: ""
protocol: http
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5
replicas: 3
resources:
  limits:
    cpu: 1000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 4Gi
secretMounts: []
securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
serverHost: 0.0.0.0
service:
  annotations: {}
  labels: {}
  loadBalancerSourceRanges: []
  nodePort: ""
  port: 5601
  type: ClusterIP
serviceAccount: ""
tolerations: []
updateStrategy:
  type: Recreate

HOOKS:
MANIFEST:
---
# Source: kibana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-helm-kibana-config
  labels:
    app: kibana
    release: "kibana-helm"
data:
  kibana.yml: |
    server.name: kibana.xxxxxx.ca
    xpack.monitoring.ui.container.elasticsearch.enabled: false
    xpack.security.enabled: false
---
# Source: kibana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kibana-helm-kibana
  labels:
    app: kibana
    release: "kibana-helm"
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 5601
      protocol: TCP
      name: http
      targetPort: 5601
  selector:
    app: kibana
    release: "kibana-helm"
---
# Source: kibana/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-helm-kibana
  labels:
    app: kibana
    release: "kibana-helm"
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kibana
      release: "kibana-helm"
  template:
    metadata:
      labels:
        app: kibana
        release: "kibana-helm"
      annotations:

        configchecksum: c29c7fccc983913213709916dcddabbdde30ff654acffd0e075cff0e3ee83cc
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: kibanaconfig
          configMap:
            name: kibana-helm-kibana-config
      containers:
      - name: kibana
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        image: "docker.elastic.co/kibana/kibana:7.6.2"
        imagePullPolicy: "IfNotPresent"
        env:
          - name: ELASTICSEARCH_HOSTS
            value: "http://xxxx-client:9200"
          - name: SERVER_HOST
            value: "0.0.0.0"
          - name: SERVER_NAME
            value: kibana.xxxxxx.ca
          - name: XPACK_SECURITY_ENABLED
            value: "false"
          - name: NODE_OPTIONS
            value: --max-old-space-size=3097
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 3
          timeoutSeconds: 5
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                http () {
                    local path="${1}"
                    set -- -XGET -s --fail

                    if [ -n "${ELASTICSEARCH_USERNAME}" ] && [ -n "${ELASTICSEARCH_PASSWORD}" ]; then
                      set -- "$@" -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}"
                    fi

                    STATUS=$(curl --output /dev/null --write-out "%{http_code}" -k "$@" "http://localhost:5601${path}")
                    if [[ "${STATUS}" -eq 200 ]]; then
                      exit 0
                    fi

                    echo "Error: Got HTTP code ${STATUS} but expected a 200"
                    exit 1
                }

                http "/app/kibana"
        ports:
        - containerPort: 5601
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 4Gi
        volumeMounts:
          - name: kibanaconfig
            mountPath: /usr/share/kibana/config/kibana.yml
            subPath: kibana.yml
e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting.*

*If you find some secrets in plain text in `helm get release` output you should use [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) to managed them is a secure way (see [Security Example](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/security/security.yml#L23-L38)).*

<details>
<summary>Output of helm get release</summary>

```
```

</details>

**Describe the bug:**
Kibana takes an inordinately long time to optimize plugins, even on pretty decent hardware.  This makes it tricky to use with things like terraform where if something messes up, you have to wait a really long time 

**Steps to reproduce:**

1. Deploy helm chart to cluster

**Expected behavior:**
Pods come up after a couple of minutes

**Provide logs and/or server output (if relevant):**
{"type":"log","@timestamp":"2020-04-05T21:38:07Z","tags":["info","optimize"],"pid":6,"message":"Optimizing and caching bundles for core, graph, monitoring, space_selector, ml, dashboardViewer, apm, maps, canvas, infra, siem, uptime, lens, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes"}
{"type":"log","@timestamp":"2020-04-05T21:59:58Z","tags":["info","optimize"],"pid":6,"message":"Optimization of bundles for core, graph, monitoring, space_selector, ml, dashboardViewer, apm, maps, canvas, infra, siem, uptime, lens, kibana, stateSessionStorageRedirect, status_page and timelion complete in 1310.90 seconds"}

**Any additional context:**
If it does require this long to optimize, how about providing the ability to persist it to storage so it at least doesn't have to do this every time the pod is recreated?

**Comment by jmlrt** [comment]
Hi @maynardflies,

We have #285 to persist Kibana plugins but would need to dedicate some time to really think about if this is the best solution and test every use cases. So I'm not sure when/if we'll be able to merge it.

Meanwhile, we are still recommanding building your own Kibana Docker images with plugins included as mentionned in https://github.com/elastic/helm-charts/tree/master/kibana#how-to-install-plugins.

**Comment by jmlrt** [comment]
related to https://github.com/elastic/helm-charts/issues/246
