### ISSUE TITLE
Kibana chart should allow custom annotations

### ISSUE THREAD

**Issue by predakanga** [elastic/helm-charts#57]
The Kibana chart should provide the `podAnnotations` value to add annotations to the created pod.

This feature is essential to using the new "autodiscovery hints" feature in Filebeat and Metricbeat.

**Comment by ryandawsonuk** [comment]
It would be good if the kibana chart supported this (the [elasticsearch chart does](https://github.com/elastic/helm-charts/blob/master/elasticsearch/templates/statefulset.yaml#L40) but not kibana at present)

**Comment by jmlrt** [comment]
Hi @ryandawsonuk,
I'm closing this as this was implemented in https://github.com/elastic/helm-charts/pull/210.
