### ISSUE TITLE
Is x-pack in elastic search open source 

### ISSUE THREAD

**Issue by sachinmsft** [elastic/helm-charts#573]
Hi,
I see in below yaml that we are configuring the certs/key to make inter-node node communication secure.
https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/security/security.yml

I have 2 questions
1) Is x-pack open source, can we use it in production without any license issue?
2) I see in above yaml that we are just configuring single cert/key for all the nodes in cluster. Is it okay ?
      a) there is no need to configure CA cert?
      b) what short of certificates are these? are these server cert or client cert or both ?

**Comment by jmlrt** [comment]
Hi @sachinmsft, 

> * Is x-pack open source, can we use it in production without any license issue?

Security isn't part of the OSS distribution which can be installed using [`elasticsearch-oss` image](https://github.com/elastic/helm-charts/blob/4fae1bd508445a755f44eb7052e3488c5eacb15d/elasticsearch/examples/oss/values.yaml#L4) but it is part of Elastic license with Basic subscription which is free to use in most case.

> * I see in above yaml that we are just configuring single cert/key for all the nodes in cluster. Is it okay ?
>   a) there is no need to configure CA cert?
>   b) what short of certificates are these? are these server cert or client cert or both ?

https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/security/security.yml is only an example of configuration using TLS and security. This example doesn't necessarily follow best practices for security in production.

For all questions not directly related to the Helm charts like question on Elasticsearch best practices or licensing, I would recommand posting to [Elastic forum](https://discuss.elastic.co/) where you'll be able to have better answers.
