### ISSUE TITLE
metricbeat without kube-state-metrics

### ISSUE THREAD

**Issue by nerumo** [elastic/helm-charts#574]
The kube-state-metrics dependency in the metricbeat chart should be optional. I have a conflict with the prometheus operator helm chart which has the same dependency with the same name.

I'd like the option to make the dependency conditional with a simple boolean value like `kubeStateMetrics.enabled` which is true by default.

**Comment by jmlrt** [comment]
Related to #387 and #561

**Comment by jmlrt** [comment]
closed by #387
