### ISSUE TITLE
How to pass file to lifecycle hook?

### ISSUE THREAD

**Issue by hatharom** [elastic/helm-charts#592]
I want to init elasticsearch data with template from a file. The example in values.yml shows handcoded json in the put request. Is there a way to define here a file which resides in the chart's directory?

**Comment by hatharom** [comment]
So basically what I did right now: Put the file into the chart and created a configmap and binded through Values.yaml's extravolumes.

Now the question: Is there a way to accomplish this without touching the chart itself (when the elasticsearch chart is a subchart ) ? Values can be overriden from the wrapper chart, but what about the file and the configmap?

**Comment by jmlrt** [comment]
Hi @hatharom, I don't think adding a file to the chart directory is something we should recommand.
I would recommand defining the config map for your file outside of this chart, then using `extraVolumeMounts` value inside the chart to mount it.
