### ISSUE TITLE
how can i create new serviceaccount and role for kibana?

### ISSUE THREAD

**Issue by ThePolarNight** [elastic/helm-charts#595]
**Chart version:**
master branch
**Kubernetes version:**
1.16.8
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)

**Helm Version:**
3.1.1

**`helm get release` output**

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting.*

*If you find some secrets in plain text in `helm get release` output you should use [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) to managed them is a secure way (see [Security Example](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/security/security.yml#L23-L38)).*

<details>
<summary>Output of helm get release</summary>

```
```

</details>

**Describe the bug:**

**Steps to reproduce:**

1.
2.
3.

**Expected behavior:**

**Provide logs and/or server output (if relevant):**

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting*

```
```

**Any additional context:**

**Comment by jmlrt** [comment]
Hi @ThePolarNight, currentlky Kibana chart doesn't allow yet to manage service account and roles like the other charts. Are you interested to contribute with a PR?
