### ISSUE TITLE
loadBalancerIP in service - Kibana

### ISSUE THREAD

**Issue by alexgordonpandera** [elastic/helm-charts#611]
**Describe the feature:**
Add loadBalancerIP in service for Kibana. This feature was added for Elasticsearch but not Kibana.

**Describe a specific use case for the feature:**
I use loadBalancerIP to specify static load balancer IP address using GCP internal load balancing. This internal IP address will be added as a record in CloudDNS to allow connection in private VPC.

**Comment by jmlrt** [comment]
Hi @alexgordonpandera,
Thanks for submitting this request.
LoadBalancerIP was implemented in #539 for Elasticsearch.
Would you be interested to create a PR based on #539 for Kibana?

**Comment by debojitkakoti** [comment]
/assign
Can I work on this issue? If it is not merged.

**Comment by jmlrt** [comment]
Closed by #726
