### ISSUE TITLE
Metricbeat daemonset not reloading on configmap changes

### ISSUE THREAD

**Issue by MaxRink** [elastic/helm-charts#632]
**Chart version:**
7.7.0
**Kubernetes version:**
1.18.2
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
CAPI
**Helm Version:**
3.1.2

**Describe the bug:**
If i change the metricbeat config and do an helm upgrade, the metricbeat configmap gets changed, but the metricbeat daemonset and deployment never restart to grab the new config.
**Steps to reproduce:**

1. install metricbeat via helm
2. change for example the output server
3. the daemonset stays the same

**Expected behavior:**
The daeomset and deployment get restarted to use the new configmap

**Comment by MaxRink** [comment]
This is due to https://github.com/elastic/helm-charts/blob/fe52a62639031d8988e2ce4cc12479c3e85e2b69/metricbeat/templates/daemonset.yaml#L140
As stated here ( https://kubernetes.io/docs/concepts/storage/volumes/#configmap ): Note: A Container using a ConfigMap as a subPath volume mount will not receive ConfigMap updates.

**Comment by jmlrt** [comment]
Fixed by #634
