### ISSUE TITLE
unable to set logstashPipeline config 

### ISSUE THREAD

**Issue by MaxRink** [elastic/helm-charts#633]
**Chart version:**
7.7.0

**Kubernetes version:**
1.18.2

**Helm Version:**
3.1.2

**Describe the bug:**
Additional files from "logstashPipeline" dont get mounted into the pod and the pod fails to start.

Ive Set
```
    logstashPipeline: 
      logstash.conf: |
        input {
          exec {
            command => "uptime"
            interval => 30
          }
        }
        output { stdout { } }
      debug.conf: | 
        input {
          exec {
            command => "uptime"
            interval => 30
          }
        }
        output { stdout { } }
```
in my values and the configmap (logstash-logstash-pipeline) that gets created for that config is valid.
But the Container hangs on startup with this error: 
```
  Warning  Failed     16m (x5 over 17m)     kubelet, thordis-ref-1-workload-cluster-md-0-5c975f955f-jxx4l  Error: failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/e9f1a8eb-0e77-4a5d-94e2-cce8738d757f/volume-subpaths/logstashpipeline/logstash/0\\\" to rootfs \\\"/run/containerd/io.containerd.runtime.v2.task/k8s.io/logstash/rootfs\\\" at \\\"/run/containerd/io.containerd.runtime.v2.task/k8s.io/logstash/rootfs/usr/share/logstash/pipeline/debug.conf\\\" caused \\\"not a directory\\\"\"": unknown
```
**Steps to reproduce:**

1. set logstashPipeline config

**Expected behavior:**
logstash.conf and debug.conf get placed under /usr/share/logstash/pipeline/

**Comment by jmlrt** [comment]
Hi @MaxRink,
I couldn't reproduce your issue. Installing Logstash chart with the mentionned values is working fine for me.
Can you provides the result of `helm get <RELEASE_NAME>`?

**Comment by jmlrt** [comment]
Closing as this can't be reproduced and no answer from issue author.
