### ISSUE TITLE
[elasticsearch] "not enough master nodes" error with istio

### ISSUE THREAD

**Issue by jreyes** [elastic/helm-charts#64]
**Chart version:** 6.6.0-alpha1
**Istio version:** 1.1.0-snapshot.6

When deploying the chart on a Istio cluster, I get the error `"not enough master nodes discovered during pinging"`

After some debugging looks like since Elasticsearch is using `elasticsearch-master-headless` service to discover the master nodes, this service only has defined the port `9200` in its service definition. Adding the `transport` port of `9300` fixed this error.

**Comment by Crazybus** [comment]
Hi Johann,

Thanks a lot for reporting this and the fix! I have opened #74 to address this.
