### ISSUE TITLE
Helm charts for APM

### ISSUE THREAD

**Issue by roncohen** [elastic/helm-charts#68]
It would be great to have official helm charts for running APM Server on kubernetes.

**Comment by fr0der1c** [comment]
I agree. An official kubernetes YAML file(like what metricbeat does) for APM would also be good.

**Comment by nchudleigh** [comment]
I think that having both the kubernetes config and the helm charts are useful.  Though people with experience can jump from one to the other its nice to not have to.

I can contribute my config if there isnt one that is preferred.

**Comment by Crazybus** [comment]
Just confirming that there are plans for an apm-server helm chart. In the meantime I would recommend checking out the community version: [helm/charts](https://github.com/helm/charts/tree/master/stable/apm-server). It seems like there is an open issue that it isn't possible to [access the service](https://github.com/helm/charts/issues/9295) but there is an [open PR](https://github.com/helm/charts/pull/11661) that is addressing this. 

The next charts will be:

* filebeat
* metricbeat
* logstash
* apm-server

**Comment by ceastman-ibm** [comment]
+1 for apm server helm chart

**Comment by botzill** [comment]
Hi.

Any updates on this feature?

Thx a lot!

**Comment by jmlrt** [comment]
👍

**Comment by umomany** [comment]
+1

**Comment by jmlrt** [comment]
FYI, we are planning to merge elastic/helm-charts#324 in a few days and we expect to release this chart in Alpha for 7.6.0.

**Comment by jmlrt** [comment]
#324 has been merged. I'll close this issue.
