### ISSUE TITLE
Support deployment annotations

### ISSUE THREAD

**Issue by kernkonzentrat** [elastic/helm-charts#684]
**Describe the feature:**
It would be very nice, if deployment annotations would be supported

**Describe a specific use case for the feature:**
We're using [Wave](https://github.com/pusher/wave) to manage deployments in our k8s cluster, which will trigger a Rolling Update, if related Config Maps or Secrets are updated. Unfortunately Wave keeps track of the managed deployments by targeting a specific deployment annotation. Would be super cool, if we could open a small pull request for this behavior :)

**Comment by kernkonzentrat** [comment]
Could you please give some feedback, if this is feasible or not - we have to manually restart pods in production, whenever a configuration or secret changes.

**Comment by fatmcgav** [comment]
@kernkonzentrat so according to https://github.com/pusher/wave/issues/59#issuecomment-526607098, `wave` will look for the annotations on the `Statefulset` aswell.

So you should be able to use the existing `podannotations` support.

Which charts were you looking at using with `wave`?

**Comment by kernkonzentrat** [comment]
@fatmcgav ...thanks for the reply. We're using metricbeat charts from `v7.7.1` - I already came across [pusher/wave/issues/#59](https://github.com/pusher/wave/issues/59) but `podannotations` won't work, as they only label the created `pods` within a `deployment`/ `daemonset`...`wave` only looks at the labels of a `deployment`/ `daemonset` / `statefulset` to support monitoring (at least in my understanding)

**Comment by fatmcgav** [comment]
@kernkonzentrat Ah, ok...

In that case, and based on the [example](https://github.com/pusher/wave#quick-start) in the Wave docs, this should be a relatively trivial addition.

Something like adding this additional block:
```yaml
      annotations:
        {{- range $key, $value := .Values.deploymentAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
```
after this line: https://github.com/elastic/helm-charts/blob/75263dd4776430d63c2b4cdb1b95be74cb385eaa/metricbeat/templates/deployment.yaml#L10

Also set a default value in `values.yml`: 
```
# Annotations to apply to the deployment
deploymentAnnotations: {}
```

And then adding a test to make sure the values are being set correctly. Something similar to https://github.com/elastic/helm-charts/blob/75263dd4776430d63c2b4cdb1b95be74cb385eaa/metricbeat/tests/metricbeat_test.py#L960-L975 should work, just with the correct paths.

If you fancy taking a stab at opening a PR with these changes, we can review and provide feedback as appropriate.

**Comment by kernkonzentrat** [comment]
@fatmcgav cool...will open the PR within the next few days 👍

**Comment by jmlrt** [comment]
Closing as #713 was merged
