### ISSUE TITLE
Pods created by Elasticsearch chart require privileged container access

### ISSUE THREAD

**Issue by ol-metaswitch** [elastic/helm-charts#689]
**Chart version:**
7.7.0
**Kubernetes version:**
1.17.6
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
On Premises
**Helm Version:**
3.2.1
**Describe the bug:**
When deploying the Elasticsearch Helm Chart pods fail to start as they don't adhere to our default Pod Security Policy of not having privileged container access to the hosts. I don't think that a pod of this nature should require privileged access as they shouldn't be using the hosts capabilities to run the elasticsearch appication.
**Steps to reproduce:**

1. Have a Pod Security policy that requires non-privileged pods deployed on the cluster, such as the recommended [baseline policy](https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/policy/baseline-psp.yaml) in the kubernetes documentation 
2. Deploy the elasticsearch helm chart, `helm upgrade --install elasticsearch elastic/elasticsearch -f values.yaml --version 7.7.0`
3. Describe one of the stateful sets created by the chart, e.g. `kubectl describe statefulset/<elasticsearch-cluster-name>-master`
4. See the following error: `create Pod <elasticsearch-cluster-name>-master-0 in StatefulSet <elasticsearch-cluster-name>-master failed error: pods "<elasticsearch-cluster-name>-master-0" is forbidden: unable to validate against any pod security policy: [spec.initContainers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]`

**Expected behavior:**
Pods created by this helm chart not to require privileged container access.

**Comment by fatmcgav** [comment]
@ol-metaswitch Thank you for opening an issue.

Looking at the error you included, this appears to be coming from one of the `initContainers`, specifically the `configure-sysctl` container:
https://github.com/elastic/helm-charts/blob/fa72b483f8b2476877a8490b32dcbcc5fc384b94/elasticsearch/templates/statefulset.yaml#L151-L161

As per the chart [README](https://github.com/elastic/helm-charts/tree/master/elasticsearch#configuration), this container can be disabled if you are setting the correct `vm.max_map_count` sysctl value via another method:

Adding the following to your `values.yaml` should get things working for you:
```yaml
sysctlInitContainer:
  enabled: false
```

Let us know if that doesn't work for you.

**Comment by ol-metaswitch** [comment]
Ah I see. I should've known it was just trying to stop me from shooting myself in the foot. Thanks for the clarification and solution.

**Comment by Thilaknath** [comment]
@ol-metaswitch How are you setting the vm.max_map_count during the helm install?

**Comment by ethai** [comment]
> @ol-metaswitch Thank you for opening an issue.
> 
> Looking at the error you included, this appears to be coming from one of the `initContainers`, specifically the `configure-sysctl` container:
> https://github.com/elastic/helm-charts/blob/fa72b483f8b2476877a8490b32dcbcc5fc384b94/elasticsearch/templates/statefulset.yaml#L151-L161
> 
> As per the chart [README](https://github.com/elastic/helm-charts/tree/master/elasticsearch#configuration), this container can be disabled if you are setting the correct `vm.max_map_count` sysctl value via another method:
> 
> Adding the following to your `values.yaml` should get things working for you:
> 
> ```yaml
> sysctlInitContainer:
>   enabled: false
> ```
> 
> Let us know if that doesn't work for you.

This would solve the privilege user constraint issue, but wondering then what are some of the options to configure the vm.max_map_count to set the required minimum of 262144

**Comment by admincasper** [comment]
For anyone coming to this issue:
If you have a Debian based node like Ubuntu, [this setting](https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html#vm-max-map-count) is set automatically and so the init-container is not required.
