### ISSUE TITLE
Official Logstash Helm chart feature request

### ISSUE THREAD

**Issue by jjtdepaul** [elastic/helm-charts#69]
Are you working on Logstash Helm chart by chance?  I found this one, but it's not working right:  https://github.com/helm/charts/tree/master/stable/logstash - it's got some issues....

**Comment by jjtdepaul** [comment]
Perhaps you know of another stable HChart we could try?

**Comment by Crazybus** [comment]
> Are you working on Logstash Helm chart by chance?

Not just yet, however it is planned. The next charts will be filebeat and metricbeat and then the plan is to start working on a logstash chart. 

> it's got some issues....
> Perhaps you know of another stable HChart we could try?

For now this appears to be the main chart so I would recommend opening an issue in the helm/charts repo in the meantime. 

I'll leave this issue open and update it once work starts on logstash.

**Comment by james-crowley** [comment]
@jmlrt Any update on Logstash? Seems like Filebeat and Metricbeat both have been added to the repo.

**Comment by james-crowley** [comment]
@Crazybus Any progress/insights you could give on the Logstash Chart status? To my knowledge it seems Filebeat and Metricbeat look like they had a code pushed for 7.2.1 release and thus they are added to the charts here. 

Is logstash the next chart slotted for development or has the plan changed?

**Comment by Crazybus** [comment]
Correct, Metricbeat and Filebeat are done so Logstash is up next. When development begins we will be sure to leave a note in this issue with a link to the WIP pull request just like with the other charts.

**Comment by jmlrt** [comment]
No I'm sorry, we don't have any ETA neither for development start nor for beta release, Logstash chart development is in our internal backlog and we'll start it as soon as we'll find time for it.

**Comment by ceastman-ibm** [comment]
@jmlrt +1 on the updated logstash helm chart.

**Comment by demisx** [comment]
@ceastman-ibm Please make sure to upvote the original issue from @jjtdepaul  instead.

**Comment by jmlrt** [comment]
Hi all!
This is just to let you know that we will start Logstash Helm Chart development pretty soon.

**Comment by ceastman-ibm** [comment]
@jmlrt if you need help testing it :) im ready

**Comment by jmlrt** [comment]
Hi all!
FYI first draft PR for Logstash Helm Chart is #333

**Comment by jmlrt** [comment]
FYI, https://github.com/elastic/helm-charts/pull/333 has been merged and Logstash Helm Chart is now available using `git clone https://github.com/elastic/helm-charts.git && helm install --name logstash helm-charts/logstash` (will be released in https://helm.elastic.co/ with 7.5.0 release).
