### ISSUE TITLE
Mutliple CVE vulnerabilities in the elasticsearch docker image(v7.7.1 & v7.8.0)

### ISSUE THREAD

**Issue by anshu14** [elastic/helm-charts#698]
**Chart version:** 7.7.1 & 7.8.0

**Kubernetes version:** 1.16.9

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine): AKS

**Helm Version:** v3.0.2

**`helm get release` output**

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting.*

*If you find some secrets in plain text in `helm get release` output you should use [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) to managed them is a secure way (see [Security Example](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/security/security.yml#L23-L38)).*

<details>
<summary>Output of helm get release</summary>

```
```

</details>

**Describe the bug:** When i am trying to install elasticsearch using helm install command, it tries to pull the image from "docker.elastic.co/elasticsearch/elasticsearch:7.7.1". This image has in total 33 CVE violations(Common Vulnerabilities and Exposures). Due to this, i cannot proceed ahead and it is kind of blocker for me. These violations are mainly in libxml2 and python library. 
I updated the image version from 7.7.1 to 7.8.0, but this image version also has same CVE issues.
Please help me in resolving these CVE issues.

**Expected behavior:** The image should get downloaded without any CVE issues.

**Provide logs and/or server output (if relevant):**

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting*

```
```

**Any additional context:**

**Comment by jmlrt** [comment]
Hi @anshu14, thanks for reporting this issue. This charts are using the official Elasticsearch Docker images which are based on the latest CentOS 7 ([Dockerfile](https://github.com/elastic/dockerfiles/blob/7.8/elasticsearch/Dockerfile).

Can you create an issue to Elasticsearch repo using [this template](https://github.com/elastic/elasticsearch/issues/new?labels=%3Ebug%2Cneeds%3Atriage&template=bug.md)?

**Comment by jmlrt** [comment]
I'm closing the issue as it's not related to the Helm charts themselves.
