### ISSUE TITLE
Not able to add data nodes to existing master cluster 

### ISSUE THREAD

**Issue by guptaalok20** [elastic/helm-charts#707]
Hi, 

I successfully deployed ELK 7.7.1 cluster with TLS enabled using the default values for nodeGroup and roles which means i have cluster with 3 nodes with all roles assigned with cluster name "elasticsearch-new"

Now I need to add specific data nodes into this cluster. I changed the following:
nodeGroup: "data"
masterService: "elasticsearch-new-master" // Also tried without updating this in the new nodes which I'm trying to add. 
roles:
  master: "false"
  ingest: "false"
  data: "true"

keeping the cluster name same. 

But the data nodes are not able find the master nodes. 
Below are the logs i see:
`{"type": "server", "timestamp": "2020-07-02T20:19:13,779Z", "level": "WARN", "component": "r.suppressed", "cluster.name": "elasticsearch-new", "node.name": "elasticsearch-new-data-0", "message": "path: /_cluster/health, params: {wait_for_status=green, timeout=1s}", 
"stacktrace": ["org.elasticsearch.discovery.MasterNotDiscoveredException: null",
"at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.onTimeout(TransportMasterNodeAction.java:220) [elasticsearch-7.7.1.jar:7.7.1]",
"at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:325) [elasticsearch-7.7.1.jar:7.7.1]",
"at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:252) [elasticsearch-7.7.1.jar:7.7.1]",
"at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:598) [elasticsearch-7.7.1.jar:7.7.1]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633) [elasticsearch-7.7.1.jar:7.7.1]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
"at java.lang.Thread.run(Thread.java:832) [?:?]"] }
{"type": "server", "timestamp": "2020-07-02T20:19:19,385Z", "level": "WARN", "component": "o.e.c.c.ClusterFormationFailureHelper", "cluster.name": "elasticsearch-new", "node.name": "elasticsearch-new-data-0", "message": "master not discovered yet: have discovered [{elasticsearch-new-data-0}{yco4SeTUT2mgy-ubL5S75w}{p_tcbimmTcaOyIRKSl5Dhg}{192.168.46.171}{192.168.46.171:9300}{dlrt}{ml.machine_memory=4294967296, xpack.installed=true, transform.node=true, ml.max_open_jobs=20}]; discovery will continue using [] from hosts providers and [] from last-known cluster state; node term 0, last-accepted version 0 in term 0" }
{"type": "server", "timestamp": "2020-07-02T20:19:22,356Z", "level": "DEBUG", "component": "o.e.a.s.m.TransportMasterNodeAction", "cluster.name": "elasticsearch-new", "node.name": "elasticsearch-new-data-0", "message": "no known master node, scheduling a retry" }
`

**Comment by jmlrt** [comment]
Hi @guptaalok20,

In order to help you, we need more details. Can you post all the details required in https://github.com/elastic/helm-charts/issues/new?template=bug_report.md?

**Comment by ebuildy** [comment]
Can you check that the generated ``statefulset.yaml`` contains the right ``discovery.seed_hosts`` (according to https://github.com/elastic/helm-charts/blob/master/elasticsearch/templates/statefulset.yaml#L306).

Also, can you ``curl http://elasticsearch-new-master-headless:9200`` from a data container?

**Comment by jmlrt** [comment]
closing as stale
