### ISSUE TITLE
Error syncing catalog elastic

### ISSUE THREAD

**Issue by MATTI68** [elastic/helm-charts#709]
When we try to add catalog to our rancher, we get the "Error syncing catalog elastic". Also our other rancher installation, where we had add this in the past, we get also this error.

**Comment by fatmcgav** [comment]
@MATTI68 Thank you for opening an issue.

Unfortunately, we don't use Rancher internally, so wouldn't be able to provide any help or guidance on how to solve this issue.

I'd suggest investigating this further on Rancher's side first.

Feel free to update this issue if we can be of any further assistance.

**Comment by MATTI68** [comment]
We get this detail error:

"links": {
"exportYaml": "…/v3/clusterCatalogs/c-w48jc:elastic/exportyaml",
"remove": "…/v3/clusterCatalogs/c-w48jc:elastic",
"self": "…/v3/clusterCatalogs/c-w48jc:elastic",
"templates": "…/v3/templates?clusterCatalogId=c-w48jc%3Aelastic",
"update": "…/v3/clusterCatalogs/c-w48jc:elastic"
},
"name": "elastic",
"namespaceId": null,
"state": "refreshed",
"transitioning": "error",
"transitioningMessage": "Error syncing catalog elastic",
"type": "clusterCatalog",
"url": "https://github.com/elastic/helm-charts/",
"uuid": "35518117-0b7e-41aa-a43d-775b4122e648"
}

**Comment by fatmcgav** [comment]
@MATTI68 Have you tried pointing at https://helm.elastic.co/ which is where the charts actually get published to?
