### ISSUE TITLE
[elasticsearch] imagePullSecrets not supported?

### ISSUE THREAD

**Issue by jolson787** [elastic/helm-charts#71]
It does not look like imagePullSecrets tag in values.yaml is being processed. We need this because we pull from an internal Docker store, rather than the public ones.

Steps to reproduce:

1. Modify values.yaml:

```
image: "docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "6.6.0"
imagePullPolicy: "IfNotPresent"
imagePullSecrets: "somesecret"
```

2. Execute:

```
helm install elasticsearch --debug --dry-run --name elasticsearch
```

Output:

```
image: docker.elastic.co/elasticsearch/elasticsearch
imagePullPolicy: IfNotPresent
imagePullSecrets: []
imageTag: 6.6.1
```

I tried several permutations (double quotes, no quotes, newline with the '  - somesecret ' notation, etc) to no avail.

The Kibana chart also suffers from the same problem. If someone fixes the Elasticsearch chart, I'll fix the Kibana chart.

**Comment by Crazybus** [comment]
Hi @jolson787 

You need to specify the full imagePullSecrets as you see in https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod 


Here is an example of the formatting that needs to be used. I think you might have been missing the `- name: secretname` part. 

https://github.com/elastic/helm-charts/blob/226911d36f9e453bc2148370ef7f82a39ad56367/elasticsearch/tests/elasticsearch_test.py#L297-L303

If it still doesn't work could you post the exact yaml configuration you have. And also any error that you might be getting? And could you also include the output of `kubectl get secrets`

**Comment by Crazybus** [comment]
Closing this one out as it is certainly working and supported. Feel free to reopen if you are still having trouble getting it working.
