### ISSUE TITLE
[logstash] Reload k8s pod if the k8s secrets changed

### ISSUE THREAD

**Issue by kksudo** [elastic/helm-charts#714]
**Describe the feature:**
Restart k8s pod when secrets changed
Should to add `secretsechecksum` to the statefulset annotation.    

**Describe a specific use case for the feature:**
We updated secrets which mounted to the statefulset, but pod know about the only old secrets, pod should be restarted as in the case of `logstash-config` changed.

I can prepare  the **PR**.

**Comment by jmlrt** [comment]
Hi @kksudo, that make sense. It would be great if you can do the PR for that 👍

**Comment by kksudo** [comment]
Yes, it's easy. I'll be doing **PR** soon.
