### ISSUE TITLE
StatefulSetSpec ValidationError

### ISSUE THREAD

**Issue by lishitiancn** [elastic/helm-charts#719]
**Chart version:*7.8.0*

**Kubernetes version:*1.17*

**Kubernetes provider:*Kubernetes*

**Helm Version:*v3.2.0*

helm install logstash logstash-7.8.0.tgz

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec

**Comment by jmlrt** [comment]
Hi @lishitiancn,
This is fixed by https://github.com/elastic/helm-charts/pull/695 which will be released with 7.8.1.
Note that Helm 3 is still not officially supported as stated in https://github.com/elastic/helm-charts#helm-versionshttps://github.com/elastic/helm-charts#helm-versions
