### ISSUE TITLE
Support global.imageRegistry

### ISSUE THREAD

**Issue by vpartington** [elastic/helm-charts#720]
**Describe the feature:**

Many Helm charts allow the image registry to be configured globally, most through a value called `global.imageRegistry`:

https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml#L7
https://github.com/bitnami/charts/blob/master/bitnami/kafka/values.yaml#L7
https://github.com/helm/charts/pull/8465/files

**Describe a specific use case for the feature:**

When deploying a Helm chart, especially one with a lot of dependencies, on EKS or AKS I'd like to configure my pods so that they get their images from an ECR or ACR instance close to my K8s cluster. This improves startup time of my pods (e.g. when scaling out) and reduces the dependency on remote resources (docker.io, quay,io, etc.).

This is also a common thing with Bitnami charts:
https://docs.bitnami.com/aws/get-started-charts-eks-marketplace/

For the chart that we publish, we've created a script to copy all images used by the chart to a configurable image registry:
https://github.com/StackVista/helm-charts/blob/master/stable/stackstate/installation/copy_images.sh

We use ElastichSearch and we have forked the chart to add this capability, but I'd rather integrate that functionality into the main branch:
https://github.com/StackVista/helm-charts/tree/master/stable/elasticsearch
https://github.com/StackVista/helm-charts/blob/master/stable/elasticsearch/templates/_helpers.tpl#L30

I can certainly make a PR (that is backwards compatible). Before I do, I'd like to get the feedback/input from the other users of this chart.

Regards, Vincent.

**Comment by jmlrt** [comment]
Hi @vpartington,
I'm not sure to get the point of this `global.imageRegistry` value. You already can use the `image` value for that:

https://github.com/elastic/helm-charts/blob/9c878167a95898062d845df1815bb6f8cb2e1c88/elasticsearch/values.yaml#L53

If you are copying `docker.elastic.co/elasticsearch/elasticsearch:7.6.2` Docker image to your ECR registry, you just need to override this value with `<ECR registry host>/elasticsearch/elasticsearch`

**Comment by ebuildy** [comment]
You are talking about https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#global-chart-values?

**Comment by mot256** [comment]
Yes most charts now use the global.imageRegistry value to refer to the commonly used registry. This way you can set only one registry value used by all sub-charts (useful when scenarios where a public registry is not used). If you there is no "global" value, you have to set the registry for each sub-chart of an umbrella chart, and that could be very tedious, especially if you have many sub-charts.

**Comment by jmlrt** [comment]
OK that make sense for umbrella charts.
PR is welcome to implement `global.imageRegistry` in a backward compatible way.
Not that this should be added to all charts or none for consistency.
