### ISSUE TITLE
how to create/deploy logstash with mapping template file

### ISSUE THREAD

**Issue by teebu** [elastic/helm-charts#722]
Describe the feature:
Provide a way to load index templates, mappings

Describe a specific use case for the feature:
To allow things like setting a default index template, ILM, mappings etc etc.

I know one suggested way is to use postStart script in ES, but that's not a good solution. I know you can include a template parameter in logstash, how do I copy that template from my helm deploy? Is that something the logstash chart can already do, and if not, can be added?

Example logstash output:
```
output {
  elasticsearch {
    hosts => ["{ES_DOMAIN_ENDPOINT}"]
    index => "cloudfront-logs-%{+YYYY.MM}"
    template => "/path-to-file/cloudfront.template.json"
  }
}
```

How do I locally create this template file, in my charts, and let deploy handle it?

**Comment by teebu** [comment]
As a workaround, I'm using the `--set-file` in the Makefile to pass the template.

**Comment by jmlrt** [comment]
Hi @teebu,
Thanks for opening this issue.
Unfortunately we currently don't have time to investigate every tickets so please be patient.
