### ISSUE TITLE
[metricbeat] Follow migration from kube-state-metrics charts out of stable repo

### ISSUE THREAD

**Issue by jmlrt** [elastic/helm-charts#733]
Metricbeat chart currently use [kube-state-metrics](https://github.com/helm/charts/tree/master/stable/kube-state-metrics) chart as subchart to get metrics from K8S.

As [Stable repo](https://github.com/helm/charts/tree/master/stable/) will be deprecated in November 2020 (see [Deprecation timeline](https://github.com/helm/charts#deprecation-timeline)), kube-state-metrics chart will need to migrate to another repository.

This work seem to be tracked in https://github.com/kubernetes/kube-state-metrics/issues/1153.

When the migration will be over, Metricbeat chart will need to be updated to get kube-state-metrics subchart from its new home.

**Comment by jmlrt** [comment]
While waiting for kube-state-metrics chart migration to a new GitHub repository, We need to update Metricbeat chart requirements to retrieve the subchart from the new stable Helm repos url => #882

**Comment by jmlrt** [comment]
still valid

**Comment by jmlrt** [comment]
For later reference, kube-state-metrics chart is now hosted at https://github.com/kubernetes/kube-state-metrics/tree/master/charts/kube-state-metrics

**Comment by christophercutajar** [comment]
While deploying an ECK cluster using terraform, I've deployed `kube-state-metrics` v2.13.0 using the official chart from https://kubernetes.github.io/kube-state-metrics. One breaking change I've encountered in the official helm chart is in below line: https://github.com/elastic/helm-charts/blob/0ff3a3c348b2cfe4fd65a17717bf8fc3e15c466d/metricbeat/templates/deployment.yaml#L121

As a solution, I've changed the aforementioned line to read as follows: `"$(KUBE_STATE_METRICS_SERVICE_HOST):$(KUBE_STATE_METRICS_SERVICE_PORT_HTTP)"`

Metricbeat deployment was deployment successfully with this change. 

Happy to help in fully testing and performing the necessary changes!

**Comment by jmlrt** [comment]
still valid

**Comment by jmlrt** [comment]
still valid

**Comment by christophercutajar** [comment]
@jmlrt let me know how can I help in achieving this!

**Comment by jmlrt** [comment]
Hi @christophercutajar, 
Sorry I totally missed your previous comment.
Thanks for your help!

I didn't try the new kube-state-metrics yet. It seems you did it. 

Do you think you could create a PR?

Also, the most important things to check is to ensure that metrics are reported correctly with this new version and to check if metricbeat upgrade tests are successful (https://devops-ci.elastic.co/view/Helm%20Charts/job/elastic+helm-charts+pull-request+integration-metricbeat/1067/).

**Comment by jmlrt** [comment]
For the records, the new chart code is here:
- https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics
- https://artifacthub.io/packages/helm/prometheus-community/kube-state-metrics/

**Comment by christophercutajar** [comment]
We've been using `kube-state-metrics` v2.13.0 it productions since March - https://github.com/elastic/seceng/issues/2028 and didn't had any issues but we need to perform testing with the latest version. 

I'll work on it in the next couple of days and will create the necessary PR.

**Comment by christophercutajar** [comment]
Haven't been able to dedicate time to this. Will plan for this during January

**Comment by jmlrt** [comment]
This was done in https://github.com/elastic/helm-charts/pull/1524.
