### ISSUE TITLE
[logstash] Invalid ports in headless service

### ISSUE THREAD

**Issue by laevilgenius** [elastic/helm-charts#765]
**Chart version: 7.8.1**

**Kubernetes version: 1.18**

**Helm Version: 3.3.0-rc.2**

Logstash headless service uses container ports from `.Values.extraPorts` which are incompatible with the service spec.

**Comment by ebuildy** [comment]
Hello,

it seems there is ``httpPort``: https://github.com/elastic/helm-charts/blob/master/logstash/templates/service-headless.yaml#L20

**Comment by laevilgenius** [comment]
I meant this part:
https://github.com/elastic/helm-charts/blob/c5660f410ca108c05ce884d257639d77d55fb89a/logstash/templates/service-headless.yaml#L21-L23
https://github.com/elastic/helm-charts/blob/c5660f410ca108c05ce884d257639d77d55fb89a/logstash/values.yaml#L156-L159

**Comment by ebuildy** [comment]
What is the problem exactly? service supports multi-ports.

**Comment by laevilgenius** [comment]
`.Values.extraPorts` is a container port [spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#containerport-v1-core) used in statefulset:
https://github.com/elastic/helm-charts/blob/c5660f410ca108c05ce884d257639d77d55fb89a/logstash/templates/statefulset.yaml#L151-L156

Service has a different [spec ](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#serviceport-v1-core)for ports, so chart installation fails when `.Values.extraPorts` is specified due to invalid service spec.

**Comment by disaster37** [comment]
+1

**Comment by autarchprinceps** [comment]
The non-headless service uses .Values.service.ports, which is what the headless service also needs to use.

**Comment by itssimon** [comment]
This issue prevents the Logstash Helm chart to be used when extra ports need to be opened (e.g. for a Beats input). I just submitted a PR to address it as suggested by @autarchprinceps.

Can this please be merged and released ASAP so that the chart becomes usable again?

**Comment by acartapanis** [comment]
+1

**Comment by adri** [comment]
I'm having the same problem :/ 

The `extraPorts` is used in a service definition and on a pod container definition. That doesn't work because these are two different APIs.

1. service port https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#serviceport-v1-core
2. container port https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#containerport-v1-core

**Comment by paprickar** [comment]
Same for me:
**Chart version: 7.9.0
Kubernetes version: 1.18
Helm Version: 3.2.0**

**Comment by adri** [comment]
It works when downgrading 2 versions. I'm using `6.8.10` instead of `6.8.12` with Helm 3. I wanted to configure an extra UDP port. This is a working config:

```
extraPorts:
  - name: logs # UDP port to send GraphQL logs to
    containerPort: 11111

service:
  ports:
    - name: logs
      port: 11111
      protocol: UDP
      targetPort: 11111
```
