### ISSUE TITLE
How to resize ES storage volume?

### ISSUE THREAD

**Issue by teebu** [elastic/helm-charts#772]
I know resizing volumes is possible, but is there a suggested method for resizing a volume for an ES cluster? Is that a feature that can be added to the chart?

Changing the volumeClaimTemplate storage size throws the error: 

```Error: UPGRADE FAILED: cannot patch "elasticsearch-master" with kind StatefulSet: StatefulSet.apps "elasticsearch-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden```

I did notice it was being discussed there, just not sure if its something that needs to be implemented in the ES helm chart. https://github.com/kubernetes/kubernetes/issues/68737

**Comment by sanvir10** [comment]
I have the same question

**Comment by fabio-filho** [comment]
@jmlrt , do you know if it is possible?

**Comment by jmlrt** [comment]
Hi,
Indeed the recommended way is to deploy a new chart release / node group in the same cluster with the good size, drain the nodes and delete the old chart release as mentionned by @krishopper.

Resizing volumes is potentially possible with K8S for some storage class but may not be possible in the case of StatefulSets with the limitations of immutable fields.

At least it hasn't been studied/tested internally.
