### ISSUE TITLE
Create Kibana livenessProbe

### ISSUE THREAD

**Issue by nikitakazantsev12** [elastic/helm-charts#773]
I would like to suggest an implementation of a livenessProbe into the chart. Might be useful for this or that use case.

**Comment by jmlrt** [comment]
Hi @nikitakazantsev12,
Can you add more details?
Knowing which chart you are mentioning and what use case would need it would help us to be able to answer you.

**Comment by nikitakazantsev12** [comment]
@jmlrt, sorry I didn't realize that's a general charts topic. So, I am talking about the Kibana chart. There is a readiness probe implemented, but no liveness probe, so we have to roll it out additionally patching existing Helm deployment, which is not exactly comfortable.

The use case:

- We have sometimes troubles with an Elasticsearch cluster because of some development/testing activities. That makes a Kibana to come into a failure state (503 Error in GUI). After restarting a Pod the Kibana comes up healthy. A Liveness-Probe would let us automate that process to increase an availability.

**Comment by jmlrt** [comment]
Related to https://github.com/elastic/helm-charts/pull/575
