### ISSUE TITLE
Rename for Fork Use Case

### ISSUE THREAD

**Issue by kbintermx** [elastic/helm-charts#784]
**Describe the feature:**

As a technologist, I would like to fork the elastic helm charts in a matter that avoids ambiguity within my company's account, so that I may manage our helm-k8s based elastic deployment, contribute PRs back, and not create confusion as to the scope of the "helm-charts" project within our github account.

**Describe a specific use case for the feature:**

When forking, the resulting project within our account is "helm-charts". However, this project is specifically about elastic helm charts. Ideally the fork would product a more specific project - "elastic-helm-charts" for example.

**Comment by fatmcgav** [comment]
@kbintermx once you have forked the repo, it should be possible to rename your fork under the repo settings.

However I believe GitHub will set up automatic redirects, so you may well not be able to reuse the `helm-charts` repo name.

**Comment by kbintermx** [comment]
Thanks @fatmcgav. This worked perfectly. And the loss of use for "helm-charts" is okay for the same reason prompting me to raise an issue.

Closing this now.
