### ISSUE TITLE
apm-server: Run as non-root user

### ISSUE THREAD

**Issue by caiconkhicon** [elastic/helm-charts#785]
**Describe the feature:**
I want to run apm-server as a non-root user, same as described here: https://github.com/helm/charts/pull/18366

Currently, if I set `podSecurityContext`, the Pod fails with the error:
 ```
Exiting: error loading config file: open apm-server.yml: permission denied
```

**Comment by jmlrt** [comment]
Hi @caiconkhicon, thanks for submitting this issue.

Can you provide more details about your environment by answering to all the questions asked in the [bug report template](https://github.com/elastic/helm-charts/issues/new?template=bug_report.md)?

**Comment by caiconkhicon** [comment]
Hi @jmlrt , thank you for your reply. I am happy to provide necessary information. However, IMO, my request here is a feature request. 
What I expect is a change to make it possible to run as `apm-server` with a non-root user. My assumption is that the change should look like https://github.com/helm/charts/pull/18366 in the official Helm chart repository.

**Comment by jmlrt** [comment]
This is still valid, however we won't be able to handle it in the short run.
Would you be interested by creating a PR?

**Comment by caiconkhicon** [comment]
@jmlrt : I think I can. Give a one week, I will try to find a time when I can do it.

**Comment by caiconkhicon** [comment]
@jmlrt : There is another problem to let apm-server run as root: the binary is owned by `root` and cannot be ran by others:
```
-rwxr-x--- 1 root root 102M Nov 28 07:07 /usr/share/apm-server/apm-server
```

Thus, when running it as non-root, this error appears:
```
/usr/local/bin/docker-entrypoint: line 8: /usr/share/apm-server/apm-server: Permission denied
```

I think the fix should be in the `apm-server` image. Can you do it? or where to do it? I don't see it looks quite like https://github.com/elastic/apm-server/blob/master/Dockerfile

**Comment by jmlrt** [comment]
@caiconkhicon,
Can you open an issue [to apm-server repo](https://github.com/elastic/apm-server/issues/new?labels=enhancement&template=feature-request.md) for that?

**Comment by caiconkhicon** [comment]
@jmlrt : I created an issue in https://github.com/elastic/apm-server and discussed with ppl there. It seems that this is not a bug/issue there but a security limitation. Thus, the apm-server pod must run with `runAsGroup: 0`. Should we fix it in the Helm chart or let users do it freely (like currently https://github.com/elastic/helm-charts/blob/master/apm-server/values.yaml#L78)
