### ISSUE TITLE
Support for helm rollback?

### ISSUE THREAD

**Issue by aggarwalShivani** [elastic/helm-charts#792]
**Context:** Support for version downgrade of elasticsearch
Acc to the elastic [docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.8/rolling-upgrades.html), in order to downgrade elasticsearch version, the suggestion is - to backup the data using snapshot before upgrade. Reinstall an empty cluster of the version before the upgrade, and restore its contents from a snapshot.

**Issue:** **How do we achieve this with elasticsearch helm chart?**
Lets say, elasticsearch chart is a part of a bigger umbrella helm chart that deploys other applications too. I can trigger snapshot creation to backup the data at pre-upgrade of the helm chart. **But, in order to support helm rollback (version downgrade) after upgrade, we cannot simply delete the helm release as suggested because it would delete other applications too.**

Is there a way we could still achieve downgrade without a reinstall? For ex. if before triggering downgrade, we could delete some data?
Lets say, we have a helm release installed with elk 7.0 version chart that can be upgraded to 7.8 version. We also want to achieve helm rollback between the two revisions of the helm release. Any thoughts on how we could handle this with elasticsearch helm chart?
**Expected behavior:**  Helm rollback event to be supported

**Comment by jmlrt** [comment]
Hi @aggarwalShivani, thanks for submitting this request.

I'm not sure this is something that could be easily and safely automatized using Helm charts technology.

IMO, this is something that should stay a manual operation (delete charts and datas then redeploy and restore datas from youre backup).

As for the case of umbrella charts, I would guess that the application charts should have some dependency to Elasticsearch and not work without it so it should be safer to delete these charts also and redeploy them if we need to delete and redeploy Elasticsearch chart.

**Comment by jmlrt** [comment]
For later reference, this [post](https://discuss.elastic.co/t/reason-for-version-downgrade-not-supported/245200/2) specify why Elasticsearch downgrade cannot be supported.

I'm closing this issue as we won't implement Elasticsearch downgrade using Helm rollback.
