### ISSUE TITLE
HELM chart import in Rancher fails because of CAPS in 8.0.0-SNAPSHOT naming

### ISSUE THREAD

**Issue by twobombs** [elastic/helm-charts#796]
**Chart version:**
8.0.0-snapshot from master
**Kubernetes version:**
1.8.x
**Kubernetes provider:** 
Rancher 2.4

**Helm Version:**
2 ( 3 gives the same error )

**Describe the bug:**
<img width="1370" alt="Screenshot 2020-08-24 at 11 19 49" src="https://user-images.githubusercontent.com/12692227/91027122-f2b93f00-e5fb-11ea-8b60-a437d1a823eb.png">

**Steps to reproduce:**

1. import ES HELM URL into Rancher Catalog
2. ..wait..
3. error

**Expected behavior:**
a happy import

**Provide logs and/or server output (if relevant):**
see screenshot

**Any additional context:**

HELM chart import in Rancher 2.x does not like the ALLCAPS name given for 8.0.0-SNAPSHOT as aparently they are registered in DNS, using lowercase in the naming would solve this.

However: changing all the SNAPSHOT to lowercase ( see [here](https://github.com/twobombs/helm-charts/commit/152018939ff41fafeb5d92d2cebfc845575459d7) )causes a 404 on the image name, because the image name commited in registry has been named with CAPS.....

**Comment by jmlrt** [comment]
Hi @twobombs, thanks for submitting this issue.

I'm not aware of how Rancher is working as we don't use it internally.
However charts from master branch are development versions intended to test future Elastic major versions and shouldn't be used outside of charts/products development. That's what explains the `-SNAPSHOT` chart version.

I recommend you to use released version from our Helm repository or GitHub tags as mentionned in the README files:

https://github.com/elastic/helm-charts/blob/master/apm-server/README.md#install-released-version-using-helm-repository:

>### Install released version using Helm repository
>
>* Add the Elastic Helm charts repo:
>`helm repo add elastic https://helm.elastic.co`
>
>* Install it:
>  - with Helm 2: `helm install --name apm-server elastic/apm-server`
>  - with [Helm 3 (beta)][]: `helm install apm-server elastic/apm-server`

**Comment by twobombs** [comment]
Thanks for the reply, the idea was/is to run the snapshot version in Rancher :) 
I'll create a lowercase repo to go with that lowercase helm fork and work from there.

thanks again for you time, you ppl have a wonderfull product.
