### ISSUE TITLE
Elasticsearch: Ability to keep matchLabel.app name and object.metadata.name separate

### ISSUE THREAD

**Issue by iantheparker** [elastic/helm-charts#813]
**Describe the feature:**
[The Bitnami Elastic chart keeps `matchLabels` and `elasticsearch.master.fullname` separate](https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/templates/master-svc.yaml#L26). I'm not attached to this implementation, but might prefer metadata.name being derived by Release.Name and app for matchLabels being derived from nameOverride?

**Describe a specific use case for the feature:**
I have an app named `foo` and it has frontend, backend and elasticsearch deployments. The frontend is called `foo-frontend`, backend is `foo-backend` etc. I'd like to be able to have the same matchLabel of `app: foo` across all deployments / stateful sets to easily connect basic services, but still be able to keep the name of `foo-elastic`. At the moment, if I pass a fullnameOverride to this chart of `foo-elastic` it has a matchLabel of `app: foo-elastic` so its service isn't accessible to our backend without more static IP stuff.

**Comment by jmlrt** [comment]
Hi @iantheparker,
Thanks for opening this issue.
We could use a `matchLabels` value and default to `{{ template "elasticsearch.uname" . }}` if `matchLabels` isn't defined. Would you be interested to submit a PR for that?
