### ISSUE TITLE
"https://helm.elastic.co" is not a valid chart repository or cannot be reached

### ISSUE THREAD

**Issue by apollie** [elastic/helm-charts#814]
**Chart version:**
NA

**Kubernetes version:**
`Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}`

`Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}`

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
RKE

**Helm Version:**
`version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"clean", GoVersion:"go1.14.9"}`

**`helm get release` output**
NA

**Describe the bug:**
After upgrading to Catalina, whenever i run `helm repo add elastic https://helm.elastic.co`
i get error message:
`Error: looks like "https://helm.elastic.co" is not a valid chart repository or cannot be reached: Get "https://helm.elastic.co/index.yaml": x509: certificate signed by unknown authority`

**Expected behavior:**
The repo is added to the list.

**Any additional context:**
Downgrading openssl to 1.0.2t does not help.
On helm v2 the issue still persists.
Cache was cleared multiple times and helm was re-installed after the cleanup as well.
There is absolutely no issues adding other chart repositories (e.g. stable, incubator, haproxytech, local chart musem, etc.).

**Comment by fatmcgav** [comment]
@apollie So the specific error you're seeing (`x509: certificate signed by unknown authority`) sounds like an issue with the CA certificates on the host.

The server cert for `https://helm.elastic.co` is signed by the `DigiCert SHA2 Secure Server CA` CA, which in turn is signed by `DigiCert Global Root CA`.
So it's worth checking the the `DigiCert Global Root CA` is in whatever certificate store your system is using.

**Comment by apollie** [comment]
@fatmcgav thanks for your reply!
I've checked the fingerprints of intermediate and root CA's in Mac's Keychain and they correspond to the ones, defined on DigiCert site.
But I wonder if helm uses keychain storage or some other (from openssl for instance), because i've noticed a cert storage file `/etc/ssl/cert.pem` where the intermediate certificate is not present, i'm not sure if it's being used by it though.

**Comment by fatmcgav** [comment]
So a quick google turned up https://github.com/helm/helm/issues/3792, which suggests it should be possible to specify a `--caCert` arg to Helm.

It's not obvious what certs are being used though. I'd assume the Mac system keystore, but I'm not on Mac so can't confirm.

**Comment by apollie** [comment]
ok, so using `--caCert` it did worked
But it's still weird why there should be such overhead with valid certificate and issuer.
I will keep investigating further, as today my colleague experienced same issue after upgrading his Mac to Catalina.

**Comment by apollie** [comment]
So if anyone else experience the same trouble as me, the workaround is to import the full certificate chain to System Keychain and explicitly select "Always trust" in its preferences.

**Comment by fatmcgav** [comment]
> So if anyone else experience the same trouble as me, the workaround is to import the full certificate chain to System Keychain and explicitly select "Always trust" in its preferences.

Ah, that's good to know... I'm glad you found a solution @apollie 

I'm going to close this one out for now :)
