### ISSUE TITLE
reindex kibana migration requires creating any index before index-patterns work

### ISSUE THREAD

**Issue by wimo7083** [elastic/helm-charts#825]
**Chart version:** 6.8.9

**Kubernetes version:** v1.16.13-gke.401

**Kubernetes provider:** GKE

**Helm Version:** 3.3.1

**`helm get release` output**

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting.*

*If you find some secrets in plain text in `helm get release` output you should use [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) to managed them is a secure way (see [Security Example](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/security/security.yml#L23-L38)).*

<details>
<summary>Output of helm get release</summary>

```bash
$ helm get values kibana -n elasticsearch
USER-SUPPLIED VALUES:
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: instancegroup
          operator: In
          values:
          - elasticsearch
elasticsearchHosts: http://elasticsearch-master:9200
healthCheckPath: /app/kibana
httpPort: 5601
image: gcr.io/apexclearing/mirror/docker.elastic.co/kibana/kibana
imagePullPolicy: IfNotPresent
imageTag: 6.8.9
kibanaConfig: {}
nodeSelector: {}
protocol: http
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5
replicas: 1
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 500Mi
serverHost: 0.0.0.0
service:
  labels: {}
  loadBalancerSourceRanges: []
  port: 5601
  targetPort: 5601
  type: NodePort
tolerations:
- effect: NoSchedule
  key: dedicated
  value: elasticsearch
updateStrategy:
  type: Recreate

```

</details>

**Describe the bug:**

I take a fresh ELK cluster running in GKE(6.8.9), kibana is running with a clean .kibana_1 index.

I have a snapshot from from a 5.4 baremetal cluster. In that snapshot I have `.kibana-5` index.

When I correctly restore the `.kibana-5` index into the ELK cluster, and then reindex that index onto `.kibana_1`, the migration appears to work without any errors or warnings. 

When I go to the kibana dashboard and try to use the index patterns migrated from the Discover tab I am told that I need to create index-patterns before I can use them. In the same screen it shows my imported index-patterns. 

When I create a simple index pattern, all the other imported index patterns are still there, and the Discover tab becomes usable.

**Steps to reproduce:**

1. Snapshot ELK 5.4 cluster -> GCS
2. Create GKE 6.8.9 cluster without kibana running and all `*kibana` indexes deleted
3. snapshot restore `.kibana-5` -> `.kibana-5` in new GKE cluster
4. Perform [kibana upgrade](https://www.elastic.co/guide/en/kibana/6.0/migrating-6.0-index.html) with slight changes in that the input you want == `.kibana-5`, and you desire a `.kibana-6`as the final transformed index. 
5. Start up kibana in cluster, wait for `.kibana_1`, and `.kibana_task_manager` to appear and the pod to be healthy.
6. reindex `source: .kibana-6, dest: .kibana_`
7. access kibana UI and attempt to use Discover tab, get the error about needing to create index-pattern, and in the same screen see the previously created patterns. When you attempt to access the discover tab it appears to redirect you to the management tab.
8. Create any index pattern that selects indexes.
9. Created index works in discover tab, along with all previously migrated index-patterns.

**Expected behavior:**

After migrating data, with index-patterns when I attempt to use the discover tab. I shouldn't have to create my first index-pattern as I have already created index-patterns.

**Any additional context:**
This kibana index is a migrated index from 2.4.5. In my 5.4 cluster the kibana index was originally 2.4.5. I managed to reindex/ upgrade this to a 5.4 without any problems. 

**Additional question:**
Is what I'm doing the correct procedure when I need to import a snapshotted index into a new GKE cluster? My knowledge of ELK is pretty basic and it seems like I might be doing something wrong-- but it's working.

**Comment by jmlrt** [comment]
Hi @wimo7083, Thanks for submitting this issue, however, this doesn't seem to be specific to the Helm charts.

Could you open an issue to [Kibana repo](https://github.com/elastic/kibana/issues) or post a question to [Elastic Discuss Forum](https://discuss.elastic.co/) instead?

**Comment by wimo7083** [comment]
> this doesn't seem to be specific to the Helm charts.

There are some components that aren't specific but the ability to control the initial restore of a kibana index is a problem I've had. 

I'll make a ticket in the kibana repo. Can you verify that what I'm doing is the correct way of introducing a kibana index to a fresh cluster?

**Comment by jmlrt** [comment]
Not an expert in Kibana, but I see nothing in your procedure which should be specific to Helm charts, AFAIK, there shouldn't be any difference for restoring a Kibana index between Kibana chart and a standard Kibana install.
