### ISSUE TITLE
Typo in logstash statefulset.yaml  template prevents extraPorts from being used.

### ISSUE THREAD

**Issue by Coder2323** [elastic/helm-charts#827]
**Chart version:**
7.8.1

**Describe the bug:**
 File:   /logstash/templates/statefulset.yaml
 Line: 155

      {{- if .Values.extraPorts }}
        {{- toYaml .Values.extraPorts | nindent 8 }}
      {{- end }}

Should be:

      {{- if .Values.extraPorts }}
        {{- toYaml .Values.extraPorts | indent 8 }}
      {{- end }}

**Comment by Coder2323** [comment]
Sorry my bad.

**Comment by jacquesvdm7** [comment]
why, is this a type or not. I saw same reference to nindent  in serviceaccount.yaml. Should this be changed or not
