### ISSUE TITLE
have anyone used istio for running xpack elasticsearch and kibana? im facing ssl routine error when i configure Gateway and Virtual service? Not sure if this is correct platform to ask this question.

### ISSUE THREAD

**Issue by aii-ssvinoth22** [elastic/helm-charts#828]
Hey, stop right there!

We use GitHub to track feature requests and bug reports. Please do not submit issues for questions about how to use features of these helm charts, best practices, or development related help.

However, we do want to help! Head on over to our official forums and ask your questions there. In additional to awesome, knowledgeable community contributors, core helm chart developers are on the forums every single day to help you out.

The forums are here: https://discuss.elastic.co/

We can't stop you from opening an issue here, but it will likely linger without a response for days or weeks before it is closed and we ask you to join us on the forums instead. Save yourself the time, and ask on the forums today.

**Comment by jmlrt** [comment]
Hi @aii-ssvinoth22,
As mentionned in the issue template, these kind of questions should be asked to https://discuss.elastic.co forum.

**Comment by ebuildy** [comment]
Relate to #841 ?
