### ISSUE TITLE
Add the ECK helm-chart

### ISSUE THREAD

**Issue by D3N14L** [elastic/helm-charts#829]
As the readme states:

> Elastic Cloud on Kubernetes which is based on Operator pattern and is Elastic recommended way to deploy Elasticsearch, Kibana and APM Server on Kubernetes.

and ECK also has a helm-chart: https://github.com/elastic/cloud-on-k8s/tree/master/deploy. Why is this helm chart not available here or in https://hub.helm.sh/charts/elastic/?

If it is the preferred way of deploying the stack I kindly request it to be added to the usual helm-chart repositories.

**Comment by jmlrt** [comment]
Hi @D3N14L,
ECK Helm chart is developped by the team in charge of the operator and so it makes sense that its code is in ECK repository.

Note that this chart isn't yet officially released, and should be available in https://helm.elastic.co and https://artifacthub.io/packages/search?page=1&repo=elastic when it will be released.

**Comment by jmlrt** [comment]
FYI ECK Helm chart has been released with ECK 1.3.0 and can be installed using the following instructions: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-install-helm.html
