### ISSUE TITLE
Deployed Coordinator nodes only not set with the ES helm chart

### ISSUE THREAD

**Issue by bamb00** [elastic/helm-charts#832]
In the ES helm chart all node roles is set to "false" with replicas '3'.  Querying the cluster nodes...I don't see the '-' assigned to the coordinator node.  The coordinator nodes name is elasticsearch-coordinator-0,1,2.  I've also noticed pvc was created for coordinator nodes only.

From the output below I could not determined if the three nodes (elasticsearch-coordinator-*) is designate as an coordinator only nodes.  I look at the pods log to verify if the nodes were coordinator but no infos returned.  Also, How do I test or run command to verify if is a coordinator node?

```
$ kubectl exec elasticsearch-coordinator-0 -- curl -X GET 'http://localhost:9200/_cat/nodes?pretty'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current  Dload  Upload   Total   Spent    Left  Speed                                 
100   649  100   649    0     0  24571      0 --:--:-- --:--:-- --:--:-- 24961
10.2.1.101 41 25 2 0.00 0.00 0.00  lr - elasticsearch-coordinator-0
10.2.1.72  46 25 3 0.00 0.00 0.00  lr - elasticsearch-coordinator-1
10.2.1.129 54 25 3 0.07 0.12 0.10  lr - elasticsearch-coordinator-2
10.2.0.236 16 46 1 0.00 0.01 0.04  ilr - elasticsearch-ingest-1
10.2.1.44  38 68 2 0.09 0.17 0.13  dlrt - elasticsearch-data-1
10.2.1.23  12 46 1 0.02 0.09 0.09  ilr - elasticsearch-ingest-0
10.2.0.106 32 68 2 0.18 0.07 0.08 dlrt - elasticsearch-data-2
10.2.0.88  40 47 2 0.88 0.47 0.23 lmr * elasticsearch-master-0
10.2.0.174 26 68 2 0.05 0.09 0.10 dlrt - elasticsearch-data-0
10.2.0.20  44 46 2 0.72 0.36 0.28 lmr - elasticsearch-master-1
```

**Comment by jmlrt** [comment]
Hi @bamb00,
We generally recommend that questions such as this are asked on our Discuss forums at discuss.elastic.co.

**Comment by dcvtruong** [comment]
Hi @jmlrt, When I post question related to helm chart? Most of the time no response from the forum.  Since this is a helm related configuration deployment I'm almost positive there would be no response.

**Comment by jacquesvdm7** [comment]
I feel for you, I had the same experience when posting a problem it seems like either no one knows or no one cares.

**Comment by jmlrt** [comment]
So I guess your coordinator value file contains:
```yaml
roles:
  master: "false"
  ingest: "false"
  data: "false"
```

Regarding `http://localhost:9200/_cat/nodes` response, it seems that all nodes including coordinator do have `lr` role which match machine learning and remote cluster client roles following the [_cat/nodes API doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html).

Not an expert but I think these roles are only used when [machine learning](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/ml-settings.html) and [remote clusters](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/modules-remote-clusters.html) are enabled. If you aren't using these features, then the nodes should act as a coordinating node.

If you prefer disabling these roles you can update your values with:
```yaml
roles:
  master: "false"
  ingest: "false"
  data: "false"
  ml: "false"
  remote_cluster_client: "false"
```

**Comment by jmlrt** [comment]
As for coordinator nodes having pvc, you can disable persistence in their value file using:
```yaml
persistence:
  enabled: false
```

**Comment by jmlrt** [comment]
@dcvtruong @jacquesvdm7 I feel sorry for the experience you had with Elastic forum.

The number of helm-charts maintainers at Elastic is very narrow, so we don't have the bandwith (neither the expert knowledge of every Elastic products) to answer all questions here.

There is a lot more contributors with better Elastic products knowledge in the forum despite few of them have helm-charts knowledge.

As for this issue, while the 2nd question about pvc is really helm-charts related and may not have found an answer in the forum, the first part about node role request more Elasticsearch knowledge than helm-charts and may have found answer in the forum.

**Comment by dcvtruong** [comment]
@jmlrt I have the ES cluster with the above nodes configuration.  To make sure the coordinator nodes is the actual coordinator nodes...How would I tested? Do you know the command to test? I look in the ES docs but could not find an example.

**Comment by jmlrt** [comment]
> @jmlrt I have the ES cluster with the above nodes configuration. To make sure the coordinator nodes is the actual coordinator nodes...What is the command to test? I look in the ES docs but could not find an example.

@dcvtruong, I'm sorry, this is above my Elasticsearch knowledge and I can only refer to the documentation for that type of question.
