### ISSUE TITLE
Support for hostAliases

### ISSUE THREAD

**Issue by jcon321** [elastic/helm-charts#840]
Hello,

My output has ssl => true, a certificate, and a host with an IP address. The host gave me a self-signed cert with a peer name such as 'elastic-server'. 

I would rather not use ssl_certificate_verfication => false. Is it possible to get an update to values.yaml to add hostAliases? Is there a way to modify hostAliases without modifying the helm chart?

Thanks

**Comment by jcon321** [comment]
for what it's worth, adding this to statefulset.yaml worked...

```
      hostAliases:
      - ip: 11.22.33.44
        hostnames:
        - "foo.bar"
```


I know it doesnt pull in from values.yaml and it's bit of a hack, but just showing that it's possible.

```
# Kubernetes-managed hosts file.
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
fe00::0 ip6-mcastprefix
fe00::1 ip6-allnodes
fe00::2 ip6-allrouters
10.42.0.23      logstash-logstash-0

# Entries added by HostAliases.
11.22.33.44     foo.bar
```

**Comment by jmlrt** [comment]
Hi @jcon321,
Thanks for openning this request.
Adding [HostAliases support](https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/) to Elastic charts could be great. Are you interested in creating a PR for that?
