### ISSUE TITLE
Readiness probe fail expected 200 got 200

### ISSUE THREAD

**Issue by ppiccolo** [elastic/helm-charts#852]
**Chart version:**
kibana 7.9.2
**Kubernetes version:**
1.18
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
BareMetal
**Helm Version:**
3.3.4

**Describe the bug:**

Readiness probe failed: Error: Got HTTP code 200 but expected a 200 sh: 11: [[: not found

**Steps to reproduce:**

1. Install chart 
2. That's all, never pass readiness probe

**Expected behavior:**

Successfully pass the check

**Comment by jmlrt** [comment]
Hi @ppiccolo 
Thank you for openning this issue.

Can you provide all details requested in the [Bug Report template](https://github.com/elastic/helm-charts/issues/new?template=bug_report.md) so we have enough informations to help you?

**Comment by jmlrt** [comment]
closing as stale
