### ISSUE TITLE
Kibana server.uuid and server.name configs 

### ISSUE THREAD

**Issue by ilhaan** [elastic/helm-charts#853]
**Chart version:** 7.9.2

**Kubernetes version:** 1.16.8

**Kubernetes provider:** Rancher

**Helm Version:** 3.2.4

**Describe the bug:** According to [this](https://www.elastic.co/guide/en/kibana/current/production.html#load-balancing-kibana) doc from Elastic, the following configs need to be unique for kibana installations being served from behind a load balancer:

```
server.uuid
server.name
```

The chart in this repo does not specify how these values can be set for kibana installations that use this chart.

**Comment by jmlrt** [comment]
Hi @ilhaan,
These settings should be defined in `kibana.yml` config files.
You can use `kibanaConfig` value for that:

```yaml
kibanaConfig:
  kibana.yml:
    server.uuid: <uuid>
    server.name: <name>
```

We recommend submitting these kind of questions on https://discuss.elastic.co forum where you have more chances to get answers and advices.

**Comment by ilhaan** [comment]
Hi @jmlrt, 
Thanks for the response. Defining these in the chart would mean all Kibana pods would have the same uuid and name. That seems to counter what is listed in documentation [here](https://www.elastic.co/guide/en/kibana/current/production.html#load-balancing-kibana): 
>Settings unique across each Kibana instance:
> ```
>server.uuid
> server.name
>```
Please advise. Will post in forum as well.

**Comment by jmlrt** [comment]
That's a good point.
I don't see how to do it currently, I'll reopen the issue.

**Comment by ilhaan** [comment]
This issue has not been resolved so it should not be marked stale.

**Comment by ilhaan** [comment]
@jmlrt any updates on this? We upgraded ES and Kibana to 7.11 today we see the following when we launch multiple kibana pods: 
```
"type":"log","@timestamp":"2021-02-16T19:35:56+00:00","tags":["warning","savedobjects-service"],"pid":7,"message":"Another Kibana instance appears to be migrating the index. Waiting for that migration to complete. If no other Kibana instance is attempting migrations, you can get past this message by deleting index .kibana_task_manager_7 and restarting Kibana."}
```

**Comment by jmlrt** [comment]
Hi @ilhaan, unfortunately no we don't have time to work on that currently.

**Comment by jmlrt** [comment]
still valid

**Comment by oxyrox** [comment]
We addressed this adding some extraEnvs:
```
extraEnvs:
- name: SERVER_NAME
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
- name: SERVER_UUID
  valueFrom:
    fieldRef:
      fieldPath: metadata.uid
```

This would set `SERVER_NAME` to the current pod name and SERVER_UUID to the pod uuid. Of course this doesn't persist the name or uuid through pod restarts/deployments. But I don't think it has to.

Does anyone see a problem doing it this way?

**Comment by zlcnju** [comment]
> We addressed this adding some extraEnvs:
> 
> ```
> extraEnvs:
> - name: SERVER_NAME
>   valueFrom:
>     fieldRef:
>       fieldPath: metadata.name
> - name: SERVER_UUID
>   valueFrom:
>     fieldRef:
>       fieldPath: metadata.uid
> ```
> 
> This would set `SERVER_NAME` to the current pod name and SERVER_UUID to the pod uuid. Of course this doesn't persist the name or uuid through pod restarts/deployments. But I don't think it has to.
> 
> Does anyone see a problem doing it this way?

will it create too many indexs if the deploy update? And do too many indexs has a side effect?
