### ISSUE TITLE
Provide 7.9.3 chart

### ISSUE THREAD

**Issue by davidkarlsen** [elastic/helm-charts#864]
**Describe the feature:**
Update chart with latest version 

**Describe a specific use case for the feature:**
run latest by default (Yes I know I can change the values)

**Comment by jmlrt** [comment]
Hi @davidkarlsen 7.9.3 charts have been released along with the Elastic Stack:
<img width="499" alt="Screenshot 2020-10-26 at 08 55 35" src="https://user-images.githubusercontent.com/8582351/97149959-bc1fb200-176d-11eb-8e7f-69b8b807a92c.png">

**Comment by davidkarlsen** [comment]
awesome - thanks a lot!
