### ISSUE TITLE
ElasticSearch: Allow to install plugins via values.yaml

### ISSUE THREAD

**Issue by clausa20** [elastic/helm-charts#869]
Old unofficial helm allowed to install plugins specifying a list in the values.yaml (cluster: plugins: []).
Now the official helm does not allow it, recommending to use a custom Dockerfile.
Using a custom Dockerfile seems not to be a good idea, because it forces to fork the original and stable ES image and it is harder to maintain in a separated manner.

You can use as old helm, an init-container that installs the necessary plugins when the pod is starting.

**Comment by ebuildy** [comment]
Can you share old Helm chart URL please?

Also, about "custom Dockerfile seems not to be a good idea" , this is the best practice recommanded by Docker it-self, the idea behind container is immutability! 

It's also a good practice to package OS/Softwares/Config/App code,vendors within the Docker image.

A (good) production infrastructure should never allow a container to make Internet call, for security reason, in the case of Elasticsearch plugin, imagine if someone add bad code in the plugin JAR, or even, if S3/Github is not available when you spaw new pod!
