### ISSUE TITLE
esJavaOpts vs jvm.options

### ISSUE THREAD

**Issue by boernd** [elastic/helm-charts#89]
I have set `esJavaOpts` to `-Xmx8g -Xms8g"` which correctly sets the env var in the container: `ES_JAVA_OPTS=-Xmx8g -Xms8g`

There also exists a `jvm.options` configuration which sets `-Xms1g` and `-Xmx1g`. This seems to cause the following settings when starting Elasticsearch:

```
1000290+      1      0 99 07:36 ?        04:12:54 /opt/jdk-11.0.1/bin/java -Xms1g -Xmx1g 
[...]
-Xmx8g -Xms8g 
[...]
```

**Comment by Crazybus** [comment]
This is coming from the default `jvm.options` that ships with Elasticsearch. Is your heapsize being set correctly? The latest flag wins so anything specified in `esJavaOpts` should be overriding `jvm.options`.

```
[root@elastic-apps-master-0 config]# curl -u elastic:$ELASTIC_PASSWORD -sS -XGET "localhost:9200/_cat/nodes?h=heap*&v"
heap.current heap.percent heap.max
       1.6gb           41    3.9gb
         2gb           52    3.9gb
       1.3gb           34    3.9gb
```

**Comment by j14ncn** [comment]
` ps aux |grep elastic`

`elastic+     1 65.7 44.2 38395368 7201648 ?    Ssl  02:01 180:16 /usr/share/elasticsearch/jdk/bin/java -Xms1g -Xmx1g  [...] -Des.cgroups.hierarchy.override=/ -Xmx6g -Xms6g [...]`
