### ISSUE TITLE
7.10.0 charts

### ISSUE THREAD

**Issue by davidkarlsen** [elastic/helm-charts#892]
**Describe the feature:**
charts with elk components running version 7.10.0 by default.

**Describe a specific use case for the feature:**
run latest release.
it would be good if the charts could be synchronized with the releases.

**Comment by jmlrt** [comment]
Hi @davidkarlsen, 
Thanks for creating this issue 👍 
We usually release Helm charts in the same time as the stack, but for 7.10.0 we need a bit more time to ensure full Helm 3 support. 7.10.0 should be released soon.

**Comment by mcmarkj** [comment]
Hey @jmlrt 

Do you know the rough timescales for the 7.10.0 release? 😄

**Comment by jmlrt** [comment]
We don't have any date yet but I expect 7.10.0 release to happen pretty soon, before the end of the month for sure.

**Comment by ebuildy** [comment]
BTW you can still set``imageTag`` value to 7.10.0  in order to deploy this version.

**Comment by jmlrt** [comment]
7.10.0 has been released yesterday: https://github.com/elastic/helm-charts/releases/tag/7.10.0
