### ISSUE TITLE
Add doc to manage PVC in Elasticsearch FAQ

### ISSUE THREAD

**Issue by jmlrt** [elastic/helm-charts#894]
There is a lot of questions about the procedure to resize Elasticsearch PVC by migrating to new chart release (https://github.com/elastic/helm-charts/issues/647#issuecomment-636778450).
This should be documented in the FAQ.

In the same way, we should document the way to create PVC matching `VolumeClaimTemplates` naming convention outside of Elasticsearch chart (https://github.com/elastic/helm-charts/issues/518#issuecomment-726109728).

This should fix  #772,  #851, #518 & #656

**Comment by MaxymVlasov** [comment]
Here is a workaround for EKS

<sup>I use `helmfile`, but for the vanilla helm, it should not very different.</sup>

1. Make sure that `helmfile -f helmfile.yaml diff` not produce changes
2. https://www.jeffgeerling.com/blog/2019/expanding-k8s-pvs-eks-on-aws
3. Change `storage` in Elasticsearch values.<br>  
4. Fix apply error (`Error: UPGRADE FAILED:..`) by removing old helm-chart revisions  
For this:
4.1. Comment all releases in `helmfile` except Elasticsearch 
4.2. `helmfile -f helmfile.yaml delete`
4.3. `helmfile -f helmfile.yaml apply`
4.4. Uncomment releases

**Comment by jmlrt** [comment]
still valid

**Comment by jmlrt** [comment]
still valid

**Comment by jmlrt** [comment]
still valid

**Comment by MaxymVlasov** [comment]
Hey, @jmlrt, I see that you work in Elastic as SRE. Maybe you can be able to ping folks in internal slack etc. to escalate that issue?
I know that docs writing can be more difficult than implementing feature/bug fixes, but 1 year for docs issue... it time to escalation, I think 🙂

**Comment by czomo** [comment]
I managed to resize volumes in kubernetes using ALLOWVOLUMEEXPANSION available in later versions
```
kubectl get Storageclass
NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   true                   93d
```
if ALLOWVOLUMEEXPANSION is not set to true add `allowVolumeExpansion: true`
`kubectl edit storageclass`
and add
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: true
```

Then go to PVC and change volume size. WARNING: Do not change size 2 in one row, i managed to get errors.
```
AWS modifyVolume failed for vol-adasdasdasdasd with IncorrectModificationState: Volume vol-adasdasdasdasd cannot be modified in modification state OPTIMIZING
```

**Comment by MaxymVlasov** [comment]
botelastic, nope.

**Comment by MaxymVlasov** [comment]
.
