### ISSUE TITLE
[filebeat] - Support ServiceMonitor for metrics collection

### ISSUE THREAD

**Issue by ryan-dyer-sp** [elastic/helm-charts#895]
**Describe the feature:**
Add a servicemonitor template to the helm chart so those using prometheus can easily scrape metrics using the filebeat helm chart.

**Describe a specific use case for the feature:**
As a user of the filebeat helm chart I want a way for my prometheus cluster to readily scrape the metrics from filebeat.  As filebeat does not have native openmetrics support, I have added the trustpilot/beats-exporter as an extraContainer via the helm chart.  Now I just need to scrape that endpoint using a prometheus ServiceMonitor.

Will submit PR shortly with changes.

**Comment by jmlrt** [comment]
Hi @vinothayyavoo, thank you for this feature request.
`ServiceMonitor` isn't a Kubernetes standard but is specific to Prometheus.
We may revisit it later, but want to avoid managing integration with third party resources outside of Elastic products and Kubernetes standard resources in Elastic charts currently.
