### ISSUE TITLE
helm upgrade --install fails with error "panic: interface conversion: interface {} is string, not map[string]interface {}"

### ISSUE THREAD

**Issue by jacquesvdm7** [elastic/helm-charts#905]
**Chart version:**
7.9.3

**Kubernetes version:**
v1.15.11-rancher1-3

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
Rancher

**Helm Version:**
3.4

**`helm get release` output**
PS C:\Development\rancher-v2.2.0> .\helm get all release
Error: query: failed to query with labels: secrets is forbidden: User "u-3aishzuwzg" cannot list resource "secrets" in API group "" in the namespace "default"
Unfortunately I do not have access to view this info

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)
N/A We are not installing Elastic but only Logstash

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting.*

*If you find some secrets in plain text in `helm get release` output you should use [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) to managed them is a secure way (see [Security Example](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/security/security.yml#L23-L38)).*

**Describe the bug:**
When installing the logstash helm charts I get this error
+ helm upgrade --install logstash-container .sub/orchestration/logstash-container/charts --atomic --kubeconfig=/kubeconfigs/mycluster/kubeconfig.yaml --namespace=orchestration-orchestration-dev --set image.repository=harbor.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/orchestration/orchestration_logstash-container --set image.tag=dev-97-1969b140349 --values .sub/orchestration/logstash-container/charts/values.yaml --values .sub/orchestration/logstash-container/charts/values-dev.yaml --set ingress.fqdn=logstash-container.orchestration-dev.mycluster --set buildID=dev-97-1969b140349
+ sub_build_tools kube watch-deployment --namespace=orchestration-orchestration-dev --kube_config_file=/kubeconfigs/mycluster/kubeconfig.yaml --deployment_name=logstash-container-docker
**panic: interface conversion: interface {} is string, not map[string]interface {}**

goroutine 1 [running]:
helm.sh/helm/v3/pkg/strvals.(*parser).key(0xc000577780, 0xc000aad830, 0x166192d, 0x1931a80)
	/home/circleci/helm.sh/helm/pkg/strvals/parser.go:211 +0xdea
helm.sh/helm/v3/pkg/strvals.(*parser).parse(0xc000577780, 0xc000aad830, 0x0)
	/home/circleci/helm.sh/helm/pkg/strvals/parser.go:133 +0x38
helm.sh/helm/v3/pkg/strvals.ParseInto(0x7fffce44e161, 0x65, 0xc000aad830, 0x17a92a0, 0xc00000e5e0)
	/home/circleci/helm.sh/helm/pkg/strvals/parser.go:70 +0xbe
helm.sh/helm/v3/pkg/cli/values.(*Options).MergeValues(0xc0004f6ea0, 0xc0004cfcc0, 0x2, 0x2, 0xc0002a58c0, 0x1, 0x1)
	/home/circleci/helm.sh/helm/pkg/cli/values/options.go:62 +0x22b
main.newUpgradeCmd.func1(0xc000290dc0, 0xc0000e65a0, 0x2, 0x12, 0x0, 0x0)
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:124 +0x325
github.com/spf13/cobra.(*Command).execute(0xc000290dc0, 0xc000141e60, 0x12, 0x12, 0xc000290dc0, 0xc000141e60)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0006fe000, 0x1d6ad20, 0xc000100630, 0x7fffce44e13b)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:83 +0x206

**Steps to reproduce:**

1. We have a dockerfile which does the following
FROM harbor.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/bks-logging/logstash:7.9.2
RUN rm -f /usr/share/logstash/pipeline/logstash.conf
COPY pipeline/ /usr/share/logstash/pipeline/
COPY config/ /usr/share/logstash/config/

EXPOSE 9999 5044 9600
This image is then pushed to docker registry and used within the values.yaml file as the image
e.g. image: "harbor.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/orchestration_logstash-container"
this is in the logstash.yml file copied in the docker file
`http.host: "0.0.0.0"`

This is in the logstash.conf file
```
input {
  tcp {
    port => 9999
    codec => line
  }
  beats{
    port => 5044
  }
}

# filter {
#   kv {
#     source => "message"
#     recursive => "true"
#   }
# }

output {
  elasticsearch {
    hosts => ["http://elasticserver1:9200","http://elasticserver2:9200","http://elasticserver3:9200"]
    index => "orc_logstash_dev_logs-%{+YYYY.MM.dd}"
    user => "myuser"
    password => "*********"
  }
}
```

2. then I start the build which runs my jenkinsfile (I cant share the jenkinsfile due to proprietary rules of our company)
3. The install then fails
+ helm upgrade --install logstash-container .sub/orchestration/logstash-container/charts --atomic --kubeconfig=/kubeconfigs/mycluster/kubeconfig.yaml --namespace=orchestration-orchestration-dev --set image.repository=harbor.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/orchestration/orchestration_logstash-container --set image.tag=dev-97-1969b140349 --values .sub/orchestration/logstash-container/charts/values.yaml --values .sub/orchestration/logstash-container/charts/values-dev.yaml --set ingress.fqdn=logstash-container.orchestration-dev.mycluster --set buildID=dev-97-1969b140349
+ sub_build_tools kube watch-deployment --namespace=orchestration-orchestration-dev --kube_config_file=/kubeconfigs/es-platformengineering-nonprod-270-kubeconfig/kubeconfig.yaml --deployment_name=logstash-container-docker
panic: interface conversion: interface {} is string, not map[string]interface {}

**Expected behavior:**
The logstash pods should be created in the Rancher cluster

**Any additional context:**
I hope this is enough info as I cannot share everything you want

**Comment by jmlrt** [comment]
Hi XXX,
Thanks for opening this issue.
I'll try to investigate it soon.

**Comment by jmlrt** [comment]
@jacquesvdm7,
I don't see any command or value which seem related to [Logstash Helm chart](https://github.com/elastic/helm-charts/tree/master/logstash) in your issue description which make it impossible to investigate.

Could you reproduce it with the non modified chart outside of rancher and paste your `helm install` command and `values`?

**Comment by jacquesvdm7** [comment]
Unfortunately I cannot just run helm install manually to install to the company Rancher cluster, I am not authorized to perform helm install outside of the our Jenkins build . I will have to build my own Rancher cluster and test it there.

**Comment by kullwindergit** [comment]
I was testing forgerock devops version 7.0 and getting same stderr while running skaffold delete or skaffold run

running [kustomize build ./kustomize/overlay/7.0/all]
 - stdout: ""
 - stderr: "panic: interface conversion: interface {} is string, not map[string]interface
