### ISSUE TITLE
Logstash ExtraVolumes are broken

### ISSUE THREAD

**Issue by MaxRink** [elastic/helm-charts#912]
**Describe the bug:**
The "ExtraVolumes" Values section in the helm chart is broken and just outputs 
'''
 template: logstash/templates/statefulset.yaml:131:14: executing "logstash/templates/statefulset.yaml" at <.Values.extraVolumes>: wrong type for value; expected string; got []interface {}
'''
**Steps to reproduce:**

1. Comment out the example in the values yaml
2. run helm template .

**Expected behavior:**

ExtraVolumes work and get correctly templated

**Comment by jmlrt** [comment]
Hi @MaxRink, as mentioned in the error message and in the value description, `Statefulset` expect `extraVolumes` to be a string and not a map.

>Templatable string of additional `volumes` to be passed to the `tpl` function 

When uncommenting the example, you should add a `|` to make yaml use the value as a string.

```
extraVolumes: |
  - name: extras
    emptyDir: {}
```

**Comment by jmlrt** [comment]
closing as stale
