### ISSUE TITLE
[elasticsearch] Real rolling upgrade (pod + ES cluster-aware)

### ISSUE THREAD

**Issue by ebuildy** [elastic/helm-charts#917]
**Describe the feature:**

When running a "helm update", pods are replaced 1 by 1, hence ES cluster is not broken during the upgrade (which is cool^^).

But ES cluster have no idea of what is going on, when a node have left, cluster is rebalancing data shards across the cluster.

The feature would be to apply a real "cluster upgrade / restart", as described at https://www.elastic.co/guide/en/elasticsearch/reference/current/restart-cluster.html when doing the helm update operation.

**Comment by jmlrt** [comment]
Hi @ebuildy,
Thank for submitting this request.
That makes sense, however I don't think that's something we can easily do with Helm.
I would recommend using our [ECK operator](https://github.com/elastic/cloud-on-k8s) for this kind of advanced rollout needs.
