### ISSUE TITLE
README.md needs an update

### ISSUE THREAD

**Issue by a139786** [elastic/helm-charts#93]
heml install line still has 6.6.2-alpha1

**Comment by a139786** [comment]
Of course, that should read helm vs heml

**Comment by jethr0null** [comment]
6.6.2-alpha1 is still correct as it is the current version of the chart itself. The image value can be overridden to specify the desired image version (though other configuration values may also need to be changed depending on which version is specified). 

That said, we have plans to bump the chart version to 7.0.0-alpha1 on Monday. In this version of the chart, the default image will be the version 7.0.0 (GA) image and the README will also be updated at that point. 

Thanks so much!
