### ISSUE TITLE
[elasticsearch] Add a way for the readiness check to accept yellow state temporarily

### ISSUE THREAD

**Issue by mtruneck** [elastic/helm-charts#933]
**Describe the feature:**
Enable manually allowing the readiness check to accept yellow state temporarily. E.g. by creating a file inside the pod, which would be deleted automatically once it reaches the green state.

**Describe a specific use case for the feature:**
When all the nodes crash and then are starting again, e.g. after depleting memory/heap on all nodes, all the nodes wait for the green state, even though the cluster is operational once it reaches the yellow state.

Updating the statefulset with `clusterHealthCheckParams` set without `wait_for_green` isn't the best solution as it entails another restart of the whole cluster.

**Comment by jmlrt** [comment]
Hi @mtruneck,
Thanks for submitting this request, unfortunately we won't have time to think about it soon so please be patient.

**Comment by abdennour** [comment]
ok @jmlrt ! we are waiting

**Comment by jmlrt** [comment]
still valid

**Comment by jmlrt** [comment]
still valid

**Comment by cocuba** [comment]
still valid

**Comment by travnewmatic** [comment]
i want this too

i'm running a single node intentionally

`yellow` is acceptable for me.
