### ISSUE TITLE
[filebeat] Allow running as Deployment as an anternative to DaemonSet

### ISSUE THREAD

**Issue by utkuozdemir** [elastic/helm-charts#934]
**Describe the feature:**
Introduce a new key `kind` into the `values.yaml` which is set to `DaemonSet` by default, but can be set to `Deployment` instead - so the application runs as a Deployment.

**Describe a specific use case for the feature:**
I have a use case where I need to run only a single instance of Filebeat, which would tail a single file in a specific location in a PVC. For a such use case, it would be good to have this feature (similar to what [fluent-bit](https://github.com/fluent/helm-charts/blob/master/charts/fluent-bit/values.yaml#L4) does).

**Comment by jmlrt** [comment]
Duplicates of https://github.com/elastic/helm-charts/issues/821
