### ISSUE TITLE
elastic helm repo cannot be proxied thru Sonatype Nexus

### ISSUE THREAD

**Issue by abdennour** [elastic/helm-charts#947]
**Kubernetes version:** 1.17

**Kubernetes provider:** on-prem
**Helm Version:** 3.2.4

**Describe the bug:**

- The chartmuseum helm.elastic.co cannot be proxied thru Sonatype Nexus.

**Steps to reproduce:**

1.  Create helm(proxy) repo in Sonatype Nexus with name `helm-charts-elastic` and original URL `https://helm.elastic.co`
2. add repo `helm repo elastic-offline http://mynexus:8081/repository/helm-charts-elastic`
3. Run `helm search elasticsearch` works, however running `helm fetch elastic-offline/elasticsearch` does not work. Also, running `helm install|pull|...` does not work.

**Expected behavior:**

The expected behavior is that the Helm repo should behave behind proxy as it behaves without proxy.

**Any additional context:**

I opened the issue here and no Sonatype , because all other Helm repos are proxied perfectly. Except elastic helm repo.

**Comment by jmlrt** [comment]
Hi @abdennour,
Thanks for opening this issue.
AFAIK, I don't see any reason why this wouldn't work. Elastic Helm repo is pretty standard.
Not sure that we'll be able to help here as we don't use and don't have knowledge of Sonatype Nexus for Helm.

**Comment by abdennour** [comment]
Thank you @jmlrt ! I suggest to migrate now to OCI image format  instead of chart museum
