### ISSUE TITLE
wrong type for value; expected string; got map[string]interface {}

### ISSUE THREAD

**Issue by saidev680** [elastic/helm-charts#949]
We are using filebeat from leastic search and using version 7.10.0.
while deploying the the filebeat using helm, getting below error:

 filebeat/templates/daemonset.yaml" at <include (print .Template.BasePath "/configmap.yaml") .>: error calling include: template: filebeat/templates/configmap.yaml:15:20: executing "filebeat/templates/configmap.yaml" at <4>: wrong type for value; expected string; got map[string]interface {}

looks like there is syntax error in filebeat/templates/configmap.yaml

We got the above issue when are upgrading helm2 charts to helm3 through terraform.

**Comment by jmlrt** [comment]
Hi @saidev680, can you fill the [bug report](https://github.com/elastic/helm-charts/issues/new?template=bug_report.md) template with all details requested?

**Comment by jmlrt** [comment]
Replaced by #962

**Comment by saidev680** [comment]
@jmlrt can you please comment what is the error?
