### ISSUE TITLE
Badly named metadata.name gives error in loop in Rancher, and fill up the hard drive

### ISSUE THREAD

**Issue by metal3d** [elastic/helm-charts#953]
**Chart version:**
master

**Kubernetes version:**
1.17

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
Bare metal cluster, with Rancher 2.2.6

**Helm Version:**
3

**Describe the bug:**

Since several days, the git repository is not usable with Rancher, there is a problem with `metadata.name`. Rancher logs in loop and ***fills up the hardrive with errors**.

**Steps to reproduce:**

1. Install Rancher
2. Add this repository as helm repository
3. Wait synchronisation (that fails since 5 days)
4. See Rancher Docker container logs

**Expected behavior:**
No error...

**Provide logs and/or server output (if relevant):**

```
[ERROR] ClusterCatalogController c-t6c42/es-catalog [clusterCatalog] failed with : failed to update templates. Multiple error occurred: [CatalogTemplateVersion.management.cattle.io "es-catalog-apm-server-8.0.0-SNAPSHOT" is invalid: metadata.name: Invalid value: "es-catalog-apm-server-8.0.0-SNAPSHOT": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') CatalogTemplateVersion.management.cattle.io "es-catalog-elasticsearch-8.0.0-SNAPSHOT" is invalid: metadata.name: Invalid value: "es-catalog-elasticsearch-8.0.0-SNAPSHOT": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') CatalogTemplateVersion.management.cattle.io "es-catalog-filebeat-8.0.0-SNAPSHOT" is invalid: metadata.name: Invalid value: "es-catalog-filebeat-8.0.0-SNAPSHOT": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') CatalogTemplateVersion.management.cattle.io "es-catalog-kibana-8.0.0-SNAPSHOT" is invalid: metadata.name: Invalid value: "es-catalog-kibana-8.0.0-SNAPSHOT": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') CatalogTemplateVersion.management.cattle.io "es-catalog-logstash-8.0.0-SNAPSHOT" is invalid: metadata.name: Invalid value: "es-catalog-logstash-8.0.0-SNAPSHOT": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') CatalogTemplateVersion.management.cattle.io "es-catalog-metricbeat-8.0.0-SNAPSHOT" is invalid: metadata.name: Invalid value: "es-catalog-metricbeat-8.0.0-SNAPSHOT": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
```

In Rancher, the synchronisation continuously fails:
![image](https://user-images.githubusercontent.com/100080/100747370-3df4a200-33e2-11eb-97c6-871c2dc72149.png)

**Any additional context:**

The problem appears since several days, that was not the case days ago, it worked without any problem

**Comment by jmlrt** [comment]
Hi @metal3d,

> Add this repository as helm repository

Can you give more details about this? We aren't using Rancher and don't know how it's working.

Just a note that master branch of this git repository is using snapshot versions of the charts and Elastic Docker images and is for developments only.

Regarding your error message with references to SNAPSHOT (`Invalid value: "es-catalog-apm-server-8.0.0-SNAPSHOT"`), this seems related.

Please remember that only the released charts coming from [Elastic Helm repo](https://helm.elastic.co) or
[GitHub releases](https://github.com/elastic/helm-charts/releases) are supported as mentioned in https://github.com/elastic/helm-charts/blob/master/README.md#supported-configurations.

**Comment by metal3d** [comment]
Hi @jmlrt,

Thanks for you answer.

Rancher allows the usage of a git repository as a helm chart source. https://www.rancher.co.jp/docs/rancher/v2.x/en/catalog/#add-custom-git-repositories

I actually didn't use helm repository (because I didn't found it months ago when we added this repository) and that's a bit complicated now to switch to helm repo source. Because the "old" installations will not find the repository that I will remove.

I didn't know that this git repository was for development, so I will have a lot of problems to switch...

Can you please leave this issue opened, the time I make some tries to switch repo without data loss? (hoping that `values.yaml` form is not different from the git repository to helm repository...)

**Comment by jmlrt** [comment]
> Can you please leave this issue opened, the time I make some tries to switch repo without data loss? (hoping that `values.yaml` form is not different from the git repository to helm repository...)

sure 👍 

Note that if you can't migrate your setup to the Helm repo, maybe you can use the Git repo with the Git tag used to create released version instead a development branch.

For example you could try replace `master` branch by `7.10.0` to checkout the tag used to create 7.10.0 Helm version (https://github.com/elastic/helm-charts/tree/7.10.0).

**Comment by metal3d** [comment]
I will try in a couple of minutes, thanks a lot

**Comment by metal3d** [comment]
Ok it seems that using the right branch works (7.7 for this cluster).
Thanks a lot for your help.

**Comment by jmlrt** [comment]
> Ok it seems that using the right branch works (7.7 for this cluster).
> Thanks a lot for your help.

Great! Note that I would recommand using the [GitHub tags](https://github.com/elastic/helm-charts/tags) (ie: `7.7.1`) instead of branchs if rancher allows it.
