### ISSUE TITLE
 error calling include: template: filebeat/templates/configmap.yaml:15:20: executing "filebeat/templates/configmap.yaml" at <4>: wrong type for value; expected string; got map[string]interface {}

### ISSUE THREAD

**Issue by saidev680** [elastic/helm-charts#962]
**Chart version:**  - latest ( 7.10.0)

**Kubernetes version:**.   Client Version: v1.19.4
                                            Server Version: v1.17.9-eks-a84824

**Kubernetes provider:* - Amazon EKS

**Helm Version:** -  v3.4.1

**`helm get release` output**

e.g. `helm install filebeat`

```
```

Syntax error while installing filebeat helm chart
**Describe the bug:**
                I am installing the filebat helm chart using repository "https://helm.elastic.co". I am doing this installation from terraform and used terraform helm provider plugin for that.
Also overriding the values in values.yaml using 
      values = [
     templatefile("modules/filebeat/values.yaml", 
       { hosts    =  "${var.values["hosts"]}",
         username = "${var.values["username"]}",
         password = "${var.values["password"]}"
         protocol = "${var.values["protocol"]}", 
         index    = "${var.values["index"]}"
        })
      ] 

But after applying terraform I got below error:

   Error: template: filebeat/templates/daemonset.yaml:29:27: executing "filebeat/templates/daemonset.yaml" at <include (print .Template.BasePath "/configmap.yaml") .>: error calling include: template: filebeat/templates/configmap.yaml:15:20: executing "filebeat/templates/configmap.yaml" at <4>: wrong type for value; expected string; got map[string]interface {}

**Steps to reproduce:**

1.
2.
3.

**Expected behavior:**
in the configmap.yaml file its showin error at below line

 4.     kind: ConfigMap

Its is expected to helm charts successfully deployed or give more description of  syntax error in the file.

**Comment by saidev680** [comment]
@jmlrt  can you please comment what is causing this syntax error?

**Comment by saidev680** [comment]
@jmlrt  can you please help me with this?

**Comment by jmlrt** [comment]
Hi @saidev680, the syntax error means that the configmap expect to have values in string format but you provide values in map format.

I can't help more because you don't provide your values here.

Can you reproduce it outside of terraform and post your values?

**Comment by saidev680** [comment]
Thanks @jmlrt, it is resolved.
