### ISSUE TITLE
Logstash Exporter - ServiceMonitor - PrometheusRules - Kubernetes deployment

### ISSUE THREAD

**Issue by alexandre-vaussant-axway** [elastic/helm-charts#963]
**Describe the feature:**

Why we don't have the capability to have an exporter from elastic with the official logstash helm chart.

**Describe a specific use case for the feature:**

All the metrics are centralized on Prometheus/Grafana stack.
Elastic allows to use metricbeats, but in my case i need to use prometheus operator for metrics scraping.
With this implementation we need an exporter, some other teams in the opensource community have this kind of sidecar 
Retrieving the metrics directly from logstash replica.

Do you plane to have this kind of feature ??

**Comment by eroteme** [comment]
I hope this functionality is also added but in the meantime I'm trying the following:

I have made the elastic chart a subchart of my own and added the missing `service` and `service monitor` manifests from the deprecated stable chart. This seems to be working to get the missing manifests but I can't seem to use the `extraContainers` helm value on the elastic chart to create the prometheus exporter container in the daemonset manifest. It just seems to ignore the text value, am wondering if this is a problem with using the `tpl` function on sub charts. Maybe this PR (https://github.com/elastic/helm-charts/pull/906) will help with my issue ? . 

But if you know how to get the `extraContainers` value to work with subcharts that would be great!

**Comment by jmlrt** [comment]
Hey @alexandre-vaussant-axway, as mentioned in #895, #802 and #231, `ServiceMonitor` isn't a Kubernetes standard but is specific to Prometheus. We want to avoid managing integration with third party resources outside of Elastic products and Kubernetes standard resources in Elastic charts currently.
