### ISSUE TITLE
elasticsearch multiple ingress rules.

### ISSUE THREAD

**Issue by kevinsmithwrs** [elastic/helm-charts#979]
Would be nice for the elasticsearch ingress.yaml to support multiple host/path rules like logstash ingress.yaml.

**Comment by jmlrt** [comment]
Hi @kevinsmithwrs,
Thanks for opening this issue.
Would you be interested to submit a PR for that?

**Comment by kevinsmithwrs** [comment]
Submitted: https://github.com/elastic/helm-charts/pull/994
