### ISSUE TITLE
Publish new version of elasticsearch chart

### ISSUE THREAD

**Issue by tlvenn** [elastic/helm-charts#98]
@Crazybus any chance to publish the new chart if it's ready ?

I saw you committed all the changes for ES7 and I am hoping to use the new chart asap without cloning the repo.

Thanks in advance.

**Comment by Crazybus** [comment]
Someone is excited :)

I was just waiting for the master build to pass: https://devops-ci.elastic.co/job/elastic+helm-charts+master/32/

And doing some final testing to make sure the upgrade paths are working properly to get from the previous release to this one. Almost ready to go though so expect a release in the next 30 minutes.

**Comment by Crazybus** [comment]
The release has now been published.

**Comment by tlvenn** [comment]
Thanks !
