### ISSUE TITLE
[elasticsearch] Add "service.enabled" parameter

### ISSUE THREAD

**Issue by ebuildy** [elastic/helm-charts#998]
**Describe the feature:**

service.yaml should be optional.

**Describe a specific use case for the feature:**

In case of a pure data nodes Helm release, service is useless (I believe ..).

**Comment by jmlrt** [comment]
Hi @ebuildy, Elasticsearch chart use 2 different services, the ["standard" service](https://github.com/elastic/helm-charts/blob/ffd109085023a37211c259302e2d076d84eeca94/elasticsearch/templates/service.yaml#L2-L45) which is used for external access and the ["headless" service](https://github.com/elastic/helm-charts/blob/ffd109085023a37211c259302e2d076d84eeca94/elasticsearch/templates/service.yaml#L47-L75) which is mandatory for statefulsets (we had to add one for Logstash charts, see https://github.com/elastic/helm-charts/pull/695 for more details).

While the "headless" need to stay, the "standard" service could be optional, I think we'll need to investigate a bit more to ensure that's OK before creating a PR for that.
